### ISSUE TITLE
Trufont not opening

### ISSUE THREAD

**Issue by VanillaandCream** [trufont/trufont#1]
Hello.,
I tried installing Trufont today. My comp specs are as below. When I double click nothing is happening. Please do look into it.

Thanks and Best.
<img width="279" alt="screen shot 2015-10-11 at 11 58 21 pm" src="https://cloud.githubusercontent.com/assets/8214702/10419618/9f686e9a-7074-11e5-83b8-b36590405b7b.png">

**Comment by davelab6** [comment]
Seems to work on 10.10, this may be a 10.9 issue

**Comment by LettError** [comment]
Same here. 10.9.5. Very little in the logs to help:
12/10/15 08:28:29,621 com.apple.launchd.peruser.502[163]: ([0x0-0x1e21e20].TruFont[82048]) Exited with code: 255

**Comment by adrientetar** [comment]
I froze it on Yosemite, it might be that. pyinstaller just told me it would be 10.6+ because of 64bit Python.

**Comment by adrientetar** [comment]
I'll have a look when I'm back home.

**Comment by adrientetar** [comment]
Can you try https://github.com/trufont/trufont/releases/download/v0.1.0/TruFont-0.1.0-darwin-10.9.5-x64.zip and tell me if this solves your problem?

**Comment by LettError** [comment]
Hi,

this solves the immediate crash at application launch. Saving the ufo gives me a different crash :)
Hey, UFO3. Cheers, Erik 



Erik

**Comment by adrientetar** [comment]
It works for me. It is either specific to OSX or to your ufo. I can't use OSX just yet but I'll try when I can.

**Comment by adrientetar** [comment]
Feel free to install the packages so as to get a backtrace by yourself. I put explanations in the README that you can have multiple version of python at once on your system (Python 3 is just called with the `python3` command).

**Comment by VanillaandCream** [comment]
Works fine for me, thanks for the update Adrien.

**Comment by davelab6** [comment]
Can be closed?

**Comment by adrientetar** [comment]
There's still these app is crashing reports but essentially yes.
