### ISSUE TITLE
[spacecenter] Adjusting width should adjust left and right equally

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#10]
When I decrement the Width value with the down arrow key, only the Right value is decremented. It would be better to decrement both left and right equally by 1 unit and Width by 2 (or each by 0.5 and width by 1)

![screen shot 2015-10-12 at 5 14 36 pm](https://cloud.githubusercontent.com/assets/261579/10438970/ea263eea-7104-11e5-90b2-785c23c1b247.png)

**Comment by pathumego** [comment]
+1 for .5 from each

**Comment by davelab6** [comment]
@adrientetar I guess your "NAK" label means "Negative Acknowledgement," does that mean if we prepare a pull request for this, you'll not accept it? :) 

If you prefer de/incrementing the width to only change the Right value, would you accept a chord key (eg Ctrl) to change both left and right values?

**Comment by adrientetar** [comment]
> @adrientetar I guess your "NAK" label means "Negative Acknowledgement," does that mean if we prepare a pull request for this, you'll not accept it? :)

Yes.

**Comment by adrientetar** [comment]
> If you prefer de/incrementing the width to only change the Right value, would you accept a chord key (eg Ctrl) to change both left and right values?

I will think about shortcuts.

**Comment by davelab6** [comment]
I suggest to close the issue, then :)

**Comment by davelab6** [comment]
FYI, in http://typedrawers.com/discussion/1171/free-fontlab-vi-public-preview-for-mac-os-x-available-now Ramiro said,

> the kerning interface [should be] fully controllable by key shortcuts so we can use game pads as it can be currently done in MetricsMachine. 
> Moving up and down kerning text files and moving horizontally along each line using only the keyboard should be made possible. Also, of course, assigning kerning values increments with different key combinations.
