### ISSUE TITLE
Add a folder with example UFO projects

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#100]
- [ ] Store some UFO example projects at /usr/share/trufont/examples/ (or equivalent folder in other operating systems).
- [ ] Provide a menu "File -> Examples -> filename.ufo" for loading the examples.

**Comment by felipesanches** [comment]
Should we make the glyph outline fit the window area? (what if the outline is small like a comma, should we get a big comma onscreen?)
Or should we make the glyph box fit instead?

**Comment by felipesanches** [comment]
Does NAK mean you won't do it yourself while others can contribute the feature?
Or does it mean you don't want to have the feature at all?
Also, does it mean you're open to discussion with some chance of perhaps changing your mind depending on the other people's opinions?

**Comment by davelab6** [comment]
I suggest renaming "NAK" to "Extension Idea"

**Comment by adrientetar** [comment]
It means I don't want this but I'm leaving the issue open for now so people can discuss and eventually bring compelling arguments to the table.

**Comment by davelab6** [comment]
Okay, that makes sense. I'll add that to the FAQ.

**Comment by davelab6** [comment]
> I suggest renaming "NAK" to "Extension Idea"

No?
