### ISSUE TITLE
Save in Glyph View

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#106]
If i hit Cmnd+S in glyph window it does not save the file. I have to open Font window to save file. I think FIle menu should be available in Glyph window too.

**Comment by davelab6** [comment]
I continue to think that a single menu bar for all windows, with inappropriate top level menu items greyed out, would provide a better - consistent - experience; and a single set of hotkeys.

**Comment by pathumego** [comment]
Moved to #203
