### ISSUE TITLE
Indicate Export format

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#109]
I think indicating it is exporting .otf when you hit save would be nice. Either have a default file name with <FamilyName>.otf or rename the title bar to Export otf.

And
- If core editor is only going to export otf's we can rename the `Export...` to `Export OTF` and have the extensions listed in a separate menu item.

**Comment by adrientetar** [comment]
This issue is similar to #94 and seems to only affect GNU (file formats are not displayed in the file dialog combobox).

**Comment by pathumego** [comment]
Nope On OSx I dont see the format in the box

**Comment by adrientetar** [comment]
5a7c2a4b9b4d7f84efa67b898b3287b7e8e26b58
