### ISSUE TITLE
Wishlist for switching to Trufont

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#114]
We'd like to switch some of our(mooniak) font production based on Fontforge to Trufont. WIth current HEAD version in mind, if following is implemented we could do that :) Hopefully can help with more bug reports and developing extensions. 

- [ ] See countour order, and change contour order. (For master compatibility)
- [ ] Edit multiple glyphs at once in Glyph WIndow
- [ ] Edit Kerning in Metrics window
- [ ] Standards for extensions and scripting

**Comment by pathumego** [comment]
wil post as separate issues

**Comment by davelab6** [comment]
I would order them as

- Edit multiple glyphs at once in Glyph WIndow
- Edit Kerning in Metrics window
- Standards for extensions and scripting
- Extension to show countour order, and change contour order. (For master compatibility)

**Comment by pathumego** [comment]
@davelab6 +1 i closed this because issues are listed in other issues. Anyway I had chat with the team and if we can have the basic functions and tools related to drawing, we all love to switch. As listed in #42  Interpolation nudge would be a luxury at this point. For drawing I would list, copy/paste/ contours, change direction, align points, boolean operations, make line as my top picks.
