### ISSUE TITLE
About Dialog display bug & text suggestion

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#117]
https://github.com/trufont/trufont/blob/9551e20b7c92c79906815a66b99757c322db518b/Lib/defconQt/fontView.py#L1236-L1241 says,

        text = "<h3>About {}</h3>" \
               "<p>I am a new UFO-centric font editor and I aim to bring " \
               "the <b>robofab</b> ecosystem to all main operating systems, " \
               "in a fast and dependency-free package.</p>" \
               "<p>Version {} – Python {}.".format(
                   name, __version__, platform.python_version())

which on OS X looks like this in 0.1.0 

<img width="420" alt="robofab?" src="https://cloud.githubusercontent.com/assets/261579/10988651/dd68f11e-8470-11e5-8b12-6f87ebacdef0.png">

and this in git head today

<img width="420" alt="screen shot 2015-11-06 at 13 27 37" src="https://cloud.githubusercontent.com/assets/261579/10990862/31f820ce-848a-11e5-8273-599e545bcacd.png">

- [ ] This appears to be all bold; maybe a bug?
- [ ] I think "robofab ecosystem" is inaccurate, given we hardly use RoboFab at all... I suggest,

               "<p>TruFont is a UFO font editor platform that aims to bring " \
               "a high quality Python ecosystem to all operating systems " \
               "in a fast and dependency-free package.</p>" \

**Comment by adrientetar** [comment]
0181c81a31ab88c594fc85c75194b468cc68dd9c

**Comment by davelab6** [comment]
"<h3>About {n}</h3>" \
        "<p>{n} is a cross-platform, modular typeface design software.</p>" \

I suggest s/software/application, or removing 'a'; in English 'software' is plural. 

        "<p>{n} is built on top of defcon and includes scripting support " \
        "with a <a href='http://robofab.com/'>robofab</a>-like API.</p>" \
        "<p>Version {} {} – Python {}.".format(

I suggest linking defcon to https://github.com/typesupply/defcon because searching 'defcon' will not turn up this link on the first page of results.

**Comment by adrientetar** [comment]
39878e40f806fb26971c1f54fddca4b73b82bd8e

**Comment by davelab6** [comment]
Thanks!

**Comment by pathumego** [comment]
@adrientetar Is git version supposed to show up on the about dialog?

**Comment by adrientetar** [comment]
It will if the program is in its git folder.

**Comment by davelab6** [comment]
Pathum, please could you make a pr on the Readme that explains how to run
the program from its git directory

**Comment by adrientetar** [comment]
Maybe the git hash should be frozen when installing, somehow.
