### ISSUE TITLE
display/edit quadratic splines with more than 2 control points

### ISSUE THREAD

**Issue by anthrotype** [trufont/trufont#125]
This may be a known issue to many, but I'd like to raise it here, especially now as @behdad has released their [cu2qu](https://github.com/googlei18n/cu2qu) cubic to quadratic curves converter.

So, if one loads a UFO which contain TrueType quadratic splines, Trufont's glyph view will only display a max of two off-curve control points per curve, even when the latter may contain more than two:

![screenshot](https://www.dropbox.com/s/82oca0329vyjm91/Screenshot%202015-11-07%2018.13.14.png?raw=1)

I'm not sure if this limitation comes from defcon or not, though it seems to be shared with Robofont as well. At least the latter warns the user when opening a quadratic UFO, like that:

> Importing UFO with quadratic curves.
> RoboFont will convert TrueType splines to splines with 2 offcurve points.

And then upon save, RF will also split -- i.e. add on-curve points to -- the quadratic splines which have more than 2 off-curves, or even force the curves which have only one off-curve to always have two... which is kind of silly, I think.

FontLab 5 and FontForge do show the quadratic splines as they are and also allow to edit them.

I wonder, what is there to do in Trufont in order to make it show quadratic splines in their full extent?

**Comment by adrientetar** [comment]
> I'm not sure if this limitation comes from defcon or not,

No, it comes from OutlineInformationPen in representationFactories.

The only real limitation in defcon is that removePoint does not support preserveShape on qCurve segments.

How does cu2qu compare to QuadraticConverter?

**Comment by anthrotype** [comment]
> How does cu2qu compare to QuadraticConverter?

I haven't done this systematically yet, though It's difficult to compare the two since the latter was explicitly made for Robofont, and therefore it works within the above mentioned 2-off-curve-points-per-qcurve limitation. On the other hand, cu2qu doesn't have such limitation, so for example, it is free to choose only 1 off curve point when a cubic curve is be exactly the same as a simple, degree-elevated quadratic curve. Or it can add more than 2 off curve points whenever it's necessary to approximate a cubic.
Besides, the name is cooler.

**Comment by adrientetar** [comment]
I see, [there's a comment](https://github.com/sansplomb/QuadraticConverter/blob/master/QuadraticConverter.roboFontExt/lib/QuadraticConverter.py#L557) about this indeed.

**Comment by anthrotype** [comment]
I see...
This `OutlineInformationPen` returns a list of segments for each on-curve point in the glyph:
```python
[Point(x=644, y=323, contourIndex=1, pointIndex=0, isSmooth=True, isFirst=True, prevCP=(644, 222), nextCP=(644, 423)),
 Point(x=347, y=655, contourIndex=1, pointIndex=4, isSmooth=True, isFirst=False, prevCP=(436, 655), nextCP=(257, 655)),
 Point(x=50, y=323, contourIndex=1, pointIndex=8, isSmooth=True, isFirst=False, prevCP=(50, 423), nextCP=(50, 222)),
 Point(x=347, y=-10, contourIndex=1, pointIndex=12, isSmooth=True, isFirst=False, prevCP=(257, -10), nextCP=(436, -10))]
```

however the input `_rawData` may also contain `qcurve` segments which can have more than two control points, e.g.:
```
[{'name': None, 'point': (644, 323), 'segmentType': 'qcurve', 'smooth': True},
  {'name': None, 'point': (644, 423), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (570, 572), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (436, 655), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (347, 655), 'segmentType': 'qcurve', 'smooth': True},
  {'name': None, 'point': (257, 655), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (123, 572), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (50, 423), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (50, 323), 'segmentType': 'qcurve', 'smooth': True},
  {'name': None, 'point': (50, 222), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (123, 72), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (257, -10), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (347, -10), 'segmentType': 'qcurve', 'smooth': True},
  {'name': None, 'point': (436, -10), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (570, 72), 'segmentType': None, 'smooth': False},
  {'name': None, 'point': (644, 222), 'segmentType': None, 'smooth': False}]]
```

The thing is attributes like `prevCP` and `nextCP` don't play nicely with TrueType quadratic splines, as these also contain "implied" on-curve points interpolated between pairs of off-curve points.
I'm not sure how to solve this.
Maybe we could add another attribute to `CPoint` class which says whether it's one such implied point, and consequently treat complex quadratic splines as sequences of atomic quadratic curves each having a single off-curve point?

**Comment by adrientetar** [comment]
> This OutlineInformationPen returns a list of segments for each on-curve point in the glyph:

Well these aren't really segments, otherwise I wouldn't have had to write a custom factory. It's a sort of point tree, the idea is to group offCurves with their onCurve siblings and number point index and so forth.

> The thing is attributes like prevCP and nextCP don't play nicely with TrueType quadratic splines,

Yeah I made this model for Postscript curves specifically.

I'm not familiar with TTF editing, but looking at e.g. [this screenshot](http://www.geocities.jp/meir000/fontforge/img/screenshot.png) I would say that the implicit onCurve point could be made as the root of a Point structure, only passing sibling offCurve two times, one time on the onCurve and one time of the implied onCurve. Then the caller in glyphView.py should be altered to use the same OffCurvePointItem for duplicate neighbors (speaking of which the OutlineInformationPen could be changed to store references to points instead of just position tuples, this would make things simpler and allow eq comparisons simply as well, I think this would involve breaking away from the standard pointpens which are meant to pass informations in a rather app-agnostic way). 
The real problem is in glyphView because I don't think that a QGraphicsItem can be the child of two items at once and the current display relies on that to move offCurve with their parent, propagate smooth point changes etc.

**Comment by adrientetar** [comment]
https://github.com/trufont/defcon/commit/3048fc10b12c25d3b84b8f288349094c2323fa00
https://github.com/adrientetar/defconQt/commit/8ef8d03fe92b1cff2a2884c24be2008167ac4e5f
https://github.com/trufont/trufont/commit/8d62e359dfbddf7cb68d3405db99aec50699be0d

should allow display and edition of all qCurve segments.

**Comment by anthrotype** [comment]
Excellent! I'll give it a try :100:

**Comment by anthrotype** [comment]
Thanks Adrien, it looks good!
For the future,  it'd be nice if the "handles" between the quadratic off-curves were also displayed. When there's only one off-curve, the handles touch themselves on the off-curve (which is correct); however, when there are more than two off-curves, those in the middle are not connected by any handle and look like they are floating.

It'd be also nice if the interpolated on-curves were displayed as such, like FontForge does I think.

**Comment by adrientetar** [comment]
> those in the middle are not connected by any handle and look like they are floating.

Right but handles are semantic: they show that moving offCurve will move neighboring offCurves as well. Afaict, only the interpolated onCurves change position in that case.

**Comment by moyogo** [comment]
In FontForge, if one wants to edit quadratic outlines for any reason, it’s nice being able to click on the interpolated on-curve point and move it, thus splitting the curve and making it a normal on-curve point.

**Comment by adrientetar** [comment]
Please open up another issue for these things, I'm working on other things at the moment.
