### ISSUE TITLE
Select Only Points with Alt+Drag Select

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#128]
In GlyphView if I drag select area, it selects both points and handles. I suggest `alt+Drag Select` to select only points, without handles.

**Comment by adrientetar** [comment]
@pathumego Does Glyphs have this functionality? If so, does it use the Alt key for it?

**Comment by pathumego** [comment]
@adrientetar Yep, it's in Glyphs and uses Alt

**Comment by adrientetar** [comment]
Cool, thanks. I'll implement something similar;

**Comment by adrientetar** [comment]
@pathumego Also, why do you need to not select off curve points?

**Comment by pathumego** [comment]
Its a preference and how I'm used to work on FF. SOmetimes I just need to move only the on curve points on a specific part, It is a pain to select one by one. I can ask from a few others how often they need that feature if you think it is not useful. I think it is very useful.

**Comment by adrientetar** [comment]
But when you move an onCurve, doesn't it move the offCurves as well already?

**Comment by pathumego** [comment]
Yes, Actually it is more convenient when selecting, specific parts of glyph.

See the following examples, it is easier to accidentally select off curve points that you don't want to move around. 

<img width="512" alt="screen shot 2015-11-23 at 8 51 22 pm" src="https://cloud.githubusercontent.com/assets/6846609/11369067/0867f610-92b5-11e5-9a5c-96464e536fbd.png">
<img width="563" alt="screen shot 2015-11-23 at 8 51 13 pm" src="https://cloud.githubusercontent.com/assets/6846609/11369068/086b01f2-92b5-11e5-82c0-98ca0d215455.png">
