### ISSUE TITLE
Harmonize usage of SizeGripItem widget

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#135]
Adrien had requested a Qt widget that provides a set of resizing handles. One specific aspect of the request was that it should be generic so we could use it for both resizing pixmaps and for resizing glyph curves. I did it by porting the C++ reference implementation that Adrien pointed out here: https://github.com/felipesanches/sizegripitem_python

Over the weekend, though, Adrien merged a portion of that code into TruFont, but including some changes to use it for scaling pixmaps. The issue is that these changes break the overall structure and generality of the widget. I've spent quite a large ammount of time today trying to re-harmonize the two usages of the widget. But instead of simply doing it quietly, I preffer to explain here the design of the widget so that we can see if we agree on these terms.

The glyph is built with 2 classes: **SizeGripItem** which is the main one and which instantiates several **ResizeHandleItem**s (which are the control nodes of the resizer widget).

The SizeGripItem class holds a reference to a resizer object that must be passed to it in its constructor.

The purpose of this resizer object is to make the widget generic. The resizer object is responsible for providing a resize() method that does whatever specific-purpose operation that a specific tool may need. So, in the case of the pixmap usage, this would be performing the resizing operation on the selected pixmap. In the glyph outline usage, it means re-evaluating the coordinates of all curve nodes that belong to the selection.

Adrien's implementation with pixmaps simply does not use this mechanism and the changes affect the usage of the SizeGripItem for glyph curves resizing (which is my current work in progress). I'd like to discuss it here so that we reach a consensus on the correct way of handling this in a generic way.

**Comment by adrientetar** [comment]
Current widget is made to work with a RectItem. I implemented setRect on PixmapItem. For bounding box scaling you can just draw a bbox rect and when setrect is called react to geometrychange by moving the points inside the rect. So the intel is in the scaling rect.
