### ISSUE TITLE
Write a tracking undo manager

### ISSUE THREAD

**Issue by adrientetar** [trufont/trufont#14]
That makes use of defcon `undoManager` calls as well. Then cleanup current hackish system in glyphView.
- should have undo/redo notifications for observers (GC)

**Comment by adrientetar** [comment]
@graphicore, feel free to work on this if you want to.

**Comment by graphicore** [comment]
Yeah, there's no defcon undoManager anymore in defcon ufo3. So this is a major task that requires heavy work on defcon. At least if you want to have the real deal, in terms of a command based undo/redo queue. I'd also prefer to do this in sync with @typesupply. And it will be time consuming.

**Comment by adrientetar** [comment]
I noticed glyphs has glyph.beginUndo() and glyph.endUndo(), this seems sensible API.

**Comment by adrientetar** [comment]
Also currently we stack an undo state on each mouse click even if no modification ends up being done which creates duplicates &ndash; something we ought to fix too.

**Comment by typesupply** [comment]
> I noticed glyphs has glyph.beginUndo() and glyph.endUndo(), this seems sensible API.

I started an undo manager a long time ago in Defcon but ran into some issues. Undo/redo is usually presented to the user at the application level and the application level usually has its own undo manager (ie NSUndoManager in Cocoa). The issue became: where does the state stack live? App level? Object level? Both? If both, how do they stay in sync and WHY BOTH!? It made my head hurt so I gave up.

I'm still not sure. I guess it might be useful for defcon to have an optional undo manager that would exist for each object. This would let purely Pythonic environments, such as direct object scripting, to have undo support. Then again, is undo really necessary in that kind of environment?

Anyway, off the top of my head, an object would need to be able to do the following:

- store an initial state
- store a state with a description of the action performed before the state was saved
- restore from a previous state

The serialization support that we discussed would do most of this work. The big issue would be the stack manager.

**Comment by adrientetar** [comment]
> Then again, is undo really necessary in that kind of environment?

It can be useful if you are doing scripting embedded into an app. Push an undo for your script that smoothes up Béziers or something, and if you don't like the result you can revert.

I would say the undoStack should live at application level but we should leave the possibility to attach whatever stack no matter whether if it's application-level or python.

Then you could pass arguments e.g.:

```
font.registerUndoStack(undoStack, undoMethod="undo", redoMethod="redo")
```

> This would let purely Pythonic environments, such as direct object scripting, to have undo support.

And this would also make sure that undo commands are sent for each change in defcon (e.g. if defcon decides the data is the same and so state doesn't change, the idea is to not have to issue undo commands in a way that is completely disconnected from defcon, which is what stores the font objects).

**Comment by adrientetar** [comment]
@graphicore I think I'll work on this. Right now I am working on rewriting glyphView w/o QGraphicsView/QGraphicsScene and I'll do that afterwards.

**Comment by graphicore** [comment]
Yeah sure! I'm dancing a bit around this anyways, so I'm happy if you take it on.

**Comment by davelab6** [comment]
@adrientetar can this be closed?

**Comment by adrientetar** [comment]
11af7427ed1fc05be182bcb516e1874f742437cb
