### ISSUE TITLE
Cannot add new glyph set: crashes and/or overwrites Latin-default

### ISSUE THREAD

**Issue by madig** [trufont/trufont#146]
So I wanted to add the character sets found on https://adobe-type-tools.github.io/adobe-latin-charsets/. However, when I click the "+" in the settings -> glyph set pane, first I get a warning on the console:

```
Traceback (most recent call last):
  File "/home/nikolaus/Entwicklung/trufont/Lib/defconQt/fontView.py", line 1453, in updateGlyphSetContents
    text = " ".join(self.glyphSets[glyphSetName])
TypeError: can only join an iterable
```
This can also crash immediately. When I give the new set a name and click "OK" and re-enter the pane, Latin-default has been given the new name and the new glyph set is called the default name and contains "f a l s e".

**Comment by adrientetar** [comment]
Thanks for reporting, 2ae3efc1e37001029a9c5abf61092dc7ebe80f94.

**Comment by madig** [comment]
Thanks for the quick fix :) Interested in adding the Adobe Latin character sets (precomposed only)?

**Comment by adrientetar** [comment]
> Interested in adding the Adobe Latin character sets (precomposed only)?

Not at this point, we have what I consider a reasonable base character set with combining diacritics &ndash; Adobe glyph sets generally quite good but they make choice in what they support and prioritize and our goal is not to make choice in lieu of the designer.
