### ISSUE TITLE
Update build on trufont.github.io

### ISSUE THREAD

**Issue by jackjennings** [trufont/trufont#151]
Is it possible to update the build on the website? I just recommended TruFont to a non-technical friend, whom I know will not be able to compile from source.

**Comment by adrientetar** [comment]
Yeah I'll do that very soon, I want to make a release before merging the new glyph view.

**Comment by davelab6** [comment]
@jackjennings if you'd like to look into https://github.com/trufont/trufont/issues/90 that would be awesome help for the next release :)

**Comment by adrientetar** [comment]
OSX: http://d-h.st/waqn  
Other platforms will follow.

**Comment by davelab6** [comment]
These file distribution sites are really awful, full of adware links :)
Github releases has a 'prerelease' option, I recommend to use that :)

**Comment by adrientetar** [comment]
https://github.com/trufont/trufont/releases/tag/0.2.0
