### ISSUE TITLE
How to get both handles of a point when drawing a glyph?

### ISSUE THREAD

**Issue by madig** [trufont/trufont#152]
I'm trying to draw something and one problem is, how do I get at both control handles? Ctrl-dragging a point gets me just one.

**Comment by adrientetar** [comment]
Ctrl gets you previous point, Alt next point. In the new incoming glyphView (#150), this is changed to < and >.

**Comment by adrientetar** [comment]
Ah, just saw the "when drawing" part. Well it's Alt as well. I believe that this is consistent with other apps e.g. Illustrator.

**Comment by madig** [comment]
Slightly related maybe: I drew a path out of corner points and double-clicked one to turn it into a smooth point. How do I get at the control handles to curve stuff around?

**Comment by adrientetar** [comment]
I haven't made this possible yet under the new glyphView but the idea would be to double-click on segment to add handles for which I need distance algorithms. I have a working one for lines already but the algebraic algorithm for curves (on branch dist2curve) I couldn't get to work yet. I'll try to solve this soon. I'm working on many fronts already and I have exams next week but I'll look into it.

**Comment by madig** [comment]
Woah, take it easy. I like the idea by the way, Glyphs does it that way iirc.

**Comment by adrientetar** [comment]
Yea. Under robofont and FontForge you can drag a line segment to "bend" it into a curve which yields off curve points too.

**Comment by davelab6** [comment]
> I haven't made this possible yet under the new glyphView but the idea would be to double-click on segment to add handles for which I need distance algorithms. I have a working one for lines already but the algebraic algorithm for curves (on branch dist2curve) I couldn't get to work yet. I'll try to solve this soon. I'm working on many fronts already and I have exams next week but I'll look into it.

I noticed the branch dist2curve still exists, with 2 commits not yet merged to master... What's the status of that now? :)
