### ISSUE TITLE
Remove `None` on title bar when there is no `Family Name`

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#164]
If user don't input a family name, on the glyphs window  title bar says `<Glyph Name> None None`

<img width="670" alt="screen shot 2015-12-19 at 10 36 26 pm" src="https://cloud.githubusercontent.com/assets/6846609/11915505/27b7a1f0-a6a1-11e5-9f37-d5b1404ba755.png">

I suggest to replace it by `Untitled` or `New Font` I like `New Font` better.

**Comment by adrientetar** [comment]
It's working as intended, just says that the font has no familyName or styleName defined. I don't see the need to paraphrase (also None familyName doesn't necessarily mean that the font is "new").

**Comment by davelab6** [comment]
None None is user hostile.

Nothing would be better.
