### ISSUE TITLE
A Fill mode in glyph window

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#165]
Implement a fill mode in glyph view. 
- Ideally to be triggered by holding down 'Space'. 
- Space + some key to lock to fill mode.

**Comment by pathumego** [comment]
https://github.com/trufont/trufont/commit/bd8d032db31fffe0f8bd982246ea857b0224f022

**Comment by anthrotype** [comment]
👍

**Comment by davelab6** [comment]
Yes!
