### ISSUE TITLE
Drop robofab dependency

### ISSUE THREAD

**Issue by adrientetar** [trufont/trufont#167]
We could switch to ufoLib without a problem now except defcon still uses robofab in a couple of places (for pens like the clockwise pen, mostly). It'd be easy to drop those few pens onto defcon. Hm.

**Comment by davelab6** [comment]
I think this is a good idea

**Comment by adrientetar** [comment]
dc5b740c93e592a5bc00240fd39a29117873b561

One thing less to maintain separately.
