### ISSUE TITLE
Enable/force gamma correction for glyph display?

### ISSUE THREAD

**Issue by madig** [trufont/trufont#170]
The display of glyphs seems to not do any gamma correction. Do you draw them "manually" or with the help of Qt's font drawing thingies? Is it possible to do gamma correction for the display of glyphs? It's quite important when judging antialiased glyphs.

If you rely on Qt5's font facilities, Qt5 comes with QPlatformIntegration::FontSmoothingGamma, can this be set from Python? Adobe's internal testing suggests a value of 1.8 for good results across a wide range of screens that try to imitate sRGB. By default, it's set to 1.0 on X11, which is annoying.

**Comment by adrientetar** [comment]
It's not font rendering, it's a QPainterPath.

**Comment by madig** [comment]
Hm. Can the surface it draws on be talked into doing gamma correction? I know little of Qt5.

**Comment by adrientetar** [comment]
I do not know, I've never looked into gamma settings.

**Comment by madig** [comment]
I skimmed the docs. It seems like https://doc.qt.io/qt-5/qpainter.html#CompositionMode-enum is what I'm looking for and QPainter::CompositionMode_SourceOver is what I want: "This is the default mode. The alpha of the source is used to blend the pixel on top of the destination". There is no occurence of "setCompositionMode" so it seems like the default is in effect. Consider this report misguided.
