### ISSUE TITLE
Point display bug 

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#175]
When I zoom in extrelemy this happens, i dont know if its something matters. 
<img width="1012" alt="screen shot 2015-12-27 at 4 23 46 pm" src="https://cloud.githubusercontent.com/assets/6846609/12011029/5d84d008-acb6-11e5-8e65-1f0ab57a809e.png">
<img width="1012" alt="screen shot 2015-12-27 at 4 23 31 pm" src="https://cloud.githubusercontent.com/assets/6846609/12011030/5da1f75a-acb6-11e5-8802-949ad17c0d56.png">

**Comment by adrientetar** [comment]
387603c1f3544a8228a3a7ba59e31b4d437fc17d
