### ISSUE TITLE
[extension] set vertical metrics using template strategies

### ISSUE THREAD

**Issue by madig** [trufont/trufont#182]
https://glyphsapp.com/tutorials/vertical-metrics lists the "Adobe", "Microsoft", "Webfonts" strategies. Maybe offer the user to calculate the metrics values automatically according to these selectable strategies and offer a custom mode on top, complete with explanations and maybe a preview.

**Comment by davelab6** [comment]
An extension to set vertical metrics (and other things that GF needs set a certain way) will eventually emerge :)
