### ISSUE TITLE
Help menu

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#187]
Add a help menu
- [ ] Link to website
- [ ] Report bugs and suggestions (link to Github)
- [ ] Follow on Twitter
- [ ] Support (Ideally direct to a web page on supporting the project)

**Comment by davelab6** [comment]
I'm happy to offer the TUG Libre Fonts Fund for collecting financial
support

**Comment by madig** [comment]
- [ ] Cheat sheet listing all possible editing interactions in the glyph view

**Comment by adrientetar** [comment]
383b41f3e10da5cf620e6e164cbedec472404ad2
