### ISSUE TITLE
Error notification opens a new file

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#199]
After this error notification it opens a new `Untitled.ufo` file. I think it shouldnt do anything.
<img width="419" alt="screen shot 2016-01-15 at 10 20 35 pm" src="https://cloud.githubusercontent.com/assets/6846609/12367099/8a5f107c-bbd7-11e5-9383-0df82835bede.png">

**Comment by adrientetar** [comment]
c21fe0ea331e5ca304b6a69d47753df829d2601b
