### ISSUE TITLE
Unable to delete offcurve points

### ISSUE THREAD

**Issue by arialcrime** [trufont/trufont#2]
Hello there!

I just started testing Trufont and also drew some curves with it, but now I am struggling with converting them back to straight segments by deleting the offcurve points. Delete and backspace somehow do not work to get rid of them.

Do you have a suggestion?

Best wishes
Benedikt

**Comment by adrientetar** [comment]
TODO ;)

**Comment by adrientetar** [comment]
I've been thinking about this lately and it would require some rearchitecturing.

Also, you can grab the offCurves that are behind and onCurve (if the segment is a line it will make it a curve) but pressing Ctrl (prevOffCurve) or Alt (nextOffCurve).

**Comment by adrientetar** [comment]
oke I just implemented this, but let me first release the current version.

**Comment by adrientetar** [comment]
19aab2d0ad7c546cad6bc31bf4f1ea4b211918bd
