### ISSUE TITLE
Handling files with errors 

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#200]
Files with erros are now given a error message and not opend
<img width="419" alt="screen shot 2016-01-15 at 10 20 35 pm" src="https://cloud.githubusercontent.com/assets/6846609/12367307/dbd3938c-bbd8-11e5-8d90-960c029fac23.png">
- What happens if there are multiple errors?
- Can we point out exact glyphs with errors? so a user could easily fix the files. 
- Can we smooth out these errors and open the file and flag the glyphs with errors. (Introducing error flag to Font view would be useful later on)
- And error messages could be improved.

**Comment by adrientetar** [comment]
> What happens if there are multiple errors?

It will stop upon first error and display it.

> Can we point out exact glyphs with errors?

unified-font-object/ufoLib#10. I'll work on that.

> Can we smooth out these errors

No. The point of UFO is the be editable manually so you can fix your things and hopefully not loose data, e.g. here would the autofix mark the segment as curve or drop the offCurves and have a line segment? Additionally, if you have e.g. an off-by-one error that corrupts the whole file autofix can kill it.

**Comment by pathumego** [comment]
@adrientetar Awesome, it makes sense if I get data on what should be corrected. Thanks! Ideally an info button that directs to 'how to manually fix the errors' tutorial on website would be useful.

**Comment by davelab6** [comment]
Showing all the first error for each glyph would be better, I think, so you
know the scale of the problem.

This would mean having a "Notices" window that messages are logged to
(like fontforge and Fontlab and robofont) instead or in addition to a
dialog

**Comment by adrientetar** [comment]
fixed in wx/ tfont & ufoLib2
