### ISSUE TITLE
Menus 

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#203]
Hey @adrientetar since there is no movement on #24 I would like to clarify two things.

- Is a single window mode in your plans? (Atleast for Glyph window, when I open multiple glyphs I expect them to be in the same window with multiple tabs, even if we have multi glyph edit.)

- Menus : In #37 and also in the hangout a unified menu was not in your plans. But I would like to point out a few things. Becuse the current structure is very annoying :)
- Familiarity of the implementation: Many applications are single window now and therefore have the same menu strucutre.
- Regardless of the window, there are many things that I would need to accsess, and this list will only keep growing.( ie:Save File, Glyph Info, Copy, paste.)
- Having a single menu strucutre would be the best way to make a menu system that makes sens to the user. (grouping different functions)

In the FontForge new menu proposal @larsenwork and I grouped exsisting FF menu items into these groups. And irrelavant menu items will be grayed out in each window.

```
File
Edit
Font
Glyph
Path
Point
Matrics
Extensions
Window
Help
```

Glyphs and new fontlab menues follows a similar strucutre. And Glyphs has this feature where you can see extra menu items when you hold alt.

I don't see any isadvantage of having the same menus, in UX. It is easier for the user and it makes sense. And makes it easier to manage new functions and features coming from extentions in the future. The current menu structure could easily become a clutter if we dont implement a logic. :)

**Comment by pathumego** [comment]
cc @davelab6

**Comment by pathumego** [comment]
@adrientetar With fast development more and more menu items are showing up :) WIth this issues like #225 could become common. If you could tell me your thoughts on my initial comment here. I can start putting together a menu structure and some UI wireframes. Im not a UI or UX desinger. But I can do some ground work with your feedback :)

**Comment by davelab6** [comment]
I agree with @pathumego about a single menu structure.

**Comment by adrientetar** [comment]
I have working implementation for this.

**Comment by pathumego** [comment]
@adrientetar Waiting for it :)

**Comment by davelab6** [comment]
Im curious what "this" is :)

**Comment by pathumego** [comment]
I assumed `single menu structure` :)

**Comment by adrientetar** [comment]
383b41f3e10da5cf620e6e164cbedec472404ad2
