### ISSUE TITLE
Funding

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#207]
In [here](http://typedrawers.com/discussion/comment/15208/#Comment_15209) @adrientetar wrote he is open to funding and indicated that no funding infrastructure  is in place yet.

And @davelab6 wrote in #187 that we can use [TUG Libre Fonts Fund](https://www.tug.org/fonts/librefontfund.html) for funding. 

We have Bountysource as an option to raise funds for specific features, or enhancements. 

EIther way If @adrientetar can decide on something we can add a section to the website and keep it open.

**Comment by davelab6** [comment]
I think having a 'tip jar' open on the homepage is a fine idea. 

But its hard to say what the funds could actually be used for in terms of paying wages for code. At the moment @adrientetar wants to keep time spent on writing code, not raising money. As a student (and well paid intern this summer ;) he isn't concerned with paying himself a wage, and if the fund did reach a good target amount (say $5k) then he doesn't want to spend time administering a fund, nor too much on administering other people's projects. 

I think the funds could be well used for funding community travel expenses for hackweeks and summits at libre conferences; apart from me, Felipe and Khaled, all the big contributors so far will be at LGM in London this year, and their travel expenses will be pretty cheap. FOSDEM is also coming up soon and I guess that would be a great opportunity to learn more from other PyQt5 devs and bring more interest to the project.

**Comment by adrientetar** [comment]
> apart from me, Felipe and Khaled

You won't be at LGM?

**Comment by davelab6** [comment]
Not sure, but looks like I'll be stuck in the US :/

**Comment by davelab6** [comment]
Github.com/davelab6/lemonade-stand :)
