### ISSUE TITLE
Fails to launch on my Mac (osx 10.6.8)

### ISSUE THREAD

**Issue by ultrasquid** [trufont/trufont#210]
I get the following on my console when I try to launch TruFont (which bounces a few times in the dock and disappears):

1/26/16 6:16:32 PM	[0x0-0x64064].io.github.trufont[601]	Error loading Python lib '/var/folders/UC/UCRMVtfAGCW8myg2ESQOLU+++TI/-Tmp-/_MEIwbKtYZ/Python': dlopen(/var/folders/UC/UCRMVtfAGCW8myg2ESQOLU+++TI/-Tmp-/_MEIwbKtYZ/Python, 10): Symbol not found: ___sincos_stret
1/26/16 6:16:32 PM	[0x0-0x64064].io.github.trufont[601]	  Referenced from: /var/folders/UC/UCRMVtfAGCW8myg2ESQOLU+++TI/-Tmp-/_MEIwbKtYZ/Python
1/26/16 6:16:32 PM	[0x0-0x64064].io.github.trufont[601]	  Expected in: /usr/lib/libSystem.B.dylib
1/26/16 6:16:32 PM	[0x0-0x64064].io.github.trufont[601]	 in /var/folders/UC/UCRMVtfAGCW8myg2ESQOLU+++TI/-Tmp-/_MEIwbKtYZ/Python
1/26/16 6:16:32 PM	com.apple.launchd.peruser.501[130]	([0x0-0x64064].io.github.trufont[601]) Exited with exit code: 255

Maybe I have a bad Python lib, or it could be something else, but I don't know what to do about it.

**Comment by adrientetar** [comment]
Binaries are 10.9+.

**Comment by davelab6** [comment]
https://github.com/trufont/trufont.github.io/pull/6/files

**Comment by ultrasquid** [comment]
It's swell that the information is in there somewhere, but system
requirements do not actually appear on the trufont.github.io website. Just
two link buttons, one directly to the Mac download and the other to the
Github releases page.

On Wed, Jan 27, 2016 at 4:39 AM, Dave Crossland <notifications@github.com>
wrote:

> https://github.com/trufont/trufont.github.io/pull/6/files
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trufont/trufont/issues/210#issuecomment-175598567>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by pathumego** [comment]
@ultrasquid Dave's PR will fix this :)

**Comment by adrientetar** [comment]
They're not system requirements, it's just I compiled the binaries on 10.9 because that's what I could get access to. Does Apple offer free OS upgrades anyway?

**Comment by davelab6** [comment]
Looks like Windows users can run 10.6 in VMware
https://www.youtube.com/watch?v=Qq7WaRKKut4

**Comment by ultrasquid** [comment]
Apple does offer free OS upgrades, but they charge through the nose for the
hardware it runs on.Mac OSX will not install past 10.6 on my old iMac, and
I can't afford a new one right now

On Wed, Jan 27, 2016 at 1:35 PM, Adrien Tétar <notifications@github.com>
wrote:

> They're not system requirements, it's just I compiled the binaries on 10.9
> because that's what I could get access to. Does Apple offer free OS
> upgrades anyway?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trufont/trufont/issues/210#issuecomment-175868700>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by davelab6** [comment]
Jason, can you run the latest development version from source?

**Comment by ultrasquid** [comment]
@davelab6 Despite having gone through the process of building packages from
source before, I was either lucky or had detailed guidance. I have no idea
what I'm trying to do to compile TruFont.

On Thu, Jan 28, 2016 at 2:23 AM, Dave Crossland <notifications@github.com>
wrote:

> Jason, can you run the latest development version from source?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trufont/trufont/issues/210#issuecomment-176108695>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by adrientetar** [comment]
From INSTALL.md:

```
brew install pyqt5
pip3 install -r requirements.txt
cd Lib && python -m defconQt
```

**Comment by ultrasquid** [comment]
My Homebrew installation is broken. I have to fix that before I can proceed with the rest. Thank you all for your patience with me.

**Comment by davelab6** [comment]
brew doctor;
brew update

etc

**Comment by ultrasquid** [comment]
I started with a clean install of OSX 10.6 on an empty partition, then
downloaded the applicable software updates. I applied the recommended
add-ons in the correct sequence with the recommended methods, and I can't
get Homebrew to install. I need help, but this has gone beyond the scope of
a TruFont problem.


On Fri, Jan 29, 2016 at 7:12 AM, Dave Crossland <notifications@github.com>
wrote:

> brew doctor;
> brew update
>
> etc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trufont/trufont/issues/210#issuecomment-176802751>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by pathumego** [comment]
Can you post any messages you get from homebrew? I've had lot of problems
with homebrew, but managed to fix it with info on forums.

On Sat, Jan 30, 2016, 9:51 AM Jason P. <notifications@github.com> wrote:

> I started with a clean install of OSX 10.6 on an empty partition, then
> downloaded the applicable software updates. I applied the recommended
> add-ons in the correct sequence with the recommended methods, and I can't
> get Homebrew to install. I need help, but this has gone beyond the scope of
> a TruFont problem.
>
>
> On Fri, Jan 29, 2016 at 7:12 AM, Dave Crossland <notifications@github.com>
> wrote:
>
> > brew doctor;
> > brew update
> >
> > etc
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/trufont/trufont/issues/210#issuecomment-176802751>.
> >
>
>
>
> --
> --
> Jason Pagura
> zimbach at gmail dot com
>
> —
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/trufont/trufont/issues/210#issuecomment-177134012>.
>
-- 

෴ ජය! ෴
පැතුම් එගොඩවත්ත
Pathum Egodawatta
pathum@mooniak.com

**Comment by ultrasquid** [comment]
That's interesting. After repeated failed installations this time the
installation script ran successfully, but git still won't report its
version.


Jason-Paguras-iMac:~ jpagura$ /usr/bin/ruby -e "$(curl -fsSL
https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1
==> The following directories will be made group writable:
/usr/local/bin
/usr/local/share
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
/usr/local/share/man/man7
==> The following directories will have their owner set to jpagura:
/usr/local/bin
/usr/local/share
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
/usr/local/share/man/man7
==> The following directories will have their group set to admin:
/usr/local/bin
/usr/local/share
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
/usr/local/share/man/man7

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/share
/usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3
/usr/local/share/man/man5 /usr/local/share/man/man7
Password:
==> /usr/bin/sudo /usr/sbin/chown jpagura /usr/local/bin /usr/local/share
/usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3
/usr/local/share/man/man5 /usr/local/share/man/man7
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/share
/usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3
/usr/local/share/man/man5 /usr/local/share/man/man7
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown jpagura /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
==> Installation successful!
==> Next steps
Run `brew help` to get started
Jason-Paguras-iMac:~ jpagura$ brew help
Example usage:
  brew [info | home | options ] [FORMULA...]
  brew install FORMULA...
  brew uninstall FORMULA...
  brew search [foo]
  brew list [FORMULA...]
  brew update
  brew upgrade [FORMULA...]
  brew pin/unpin [FORMULA...]

Troubleshooting:
  brew doctor
  brew install -vd FORMULA
  brew [--env | config]

Brewing:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

Further help:
  man brew
  brew home
Jason-Paguras-iMac:~ jpagura$ git --version
Illegal instruction



On Sat, Jan 30, 2016 at 3:12 AM, Pathum Egodawatta <notifications@github.com
> wrote:

> Can you post any messages you get from homebrew? I've had lot of problems
> with homebrew, but managed to fix it with info on forums.
>
> On Sat, Jan 30, 2016, 9:51 AM Jason P. <notifications@github.com> wrote:
>
> > I started with a clean install of OSX 10.6 on an empty partition, then
> > downloaded the applicable software updates. I applied the recommended
> > add-ons in the correct sequence with the recommended methods, and I can't
> > get Homebrew to install. I need help, but this has gone beyond the scope
> of
> > a TruFont problem.
> >
> >
> > On Fri, Jan 29, 2016 at 7:12 AM, Dave Crossland <
> notifications@github.com>
> > wrote:
> >
> > > brew doctor;
> > > brew update
> > >
> > > etc
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/trufont/trufont/issues/210#issuecomment-176802751
> >.
> > >
> >
> >
> >
> > --
> > --
> > Jason Pagura
> > zimbach at gmail dot com
> >
> > —
> >
> >
> > Reply to this email directly or view it on GitHub
> > <https://github.com/trufont/trufont/issues/210#issuecomment-177134012>.
> >
> --
>
> ෴ ජය! ෴
> පැතුම් එගොඩවත්ත
> Pathum Egodawatta
> pathum@mooniak.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trufont/trufont/issues/210#issuecomment-177150662>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by ultrasquid** [comment]
and this is the brew doctor report:

Jason-Paguras-iMac:~ jpagura$ brew doctor
Please note that these warnings are just used to help the Homebrew
maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The system curl on 10.8 and below is often incapable of supporting
modern secure connections & will fail on fetching formulae.

We recommend you:
  brew install curl

Warning: Your XQuartz (2.3.6) is outdated
Please install XQuartz 2.7.8:
  https://xquartz.macosforge.org

Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
sh: line 1:   729 Segmentation fault      git status --untracked-files=all
--porcelain -- Library/Homebrew/ 2> /dev/null


On Sat, Jan 30, 2016 at 9:29 AM, Jason Pagura <zimbach@gmail.com> wrote:

> That's interesting. After repeated failed installations this time the
> installation script ran successfully, but git still won't report its
> version.
>
>
> Jason-Paguras-iMac:~ jpagura$ /usr/bin/ruby -e "$(curl -fsSL
> https://raw.githubusercontent.com/Homebrew/install/master/install)"
> ==> This script will install:
> /usr/local/bin/brew
> /usr/local/Library/...
> /usr/local/share/man/man1/brew.1
> ==> The following directories will be made group writable:
> /usr/local/bin
> /usr/local/share
> /usr/local/share/man
> /usr/local/share/man/man1
> /usr/local/share/man/man3
> /usr/local/share/man/man5
> /usr/local/share/man/man7
> ==> The following directories will have their owner set to jpagura:
> /usr/local/bin
> /usr/local/share
> /usr/local/share/man
> /usr/local/share/man/man1
> /usr/local/share/man/man3
> /usr/local/share/man/man5
> /usr/local/share/man/man7
> ==> The following directories will have their group set to admin:
> /usr/local/bin
> /usr/local/share
> /usr/local/share/man
> /usr/local/share/man/man1
> /usr/local/share/man/man3
> /usr/local/share/man/man5
> /usr/local/share/man/man7
>
> Press RETURN to continue or any other key to abort
> ==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/share
> /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3
> /usr/local/share/man/man5 /usr/local/share/man/man7
> Password:
> ==> /usr/bin/sudo /usr/sbin/chown jpagura /usr/local/bin /usr/local/share
> /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3
> /usr/local/share/man/man5 /usr/local/share/man/man7
> ==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/share
> /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3
> /usr/local/share/man/man5 /usr/local/share/man/man7
> ==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
> ==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
> ==> /usr/bin/sudo /usr/sbin/chown jpagura /Library/Caches/Homebrew
> ==> Downloading and installing Homebrew...
> ==> Installation successful!
> ==> Next steps
> Run `brew help` to get started
> Jason-Paguras-iMac:~ jpagura$ brew help
> Example usage:
>   brew [info | home | options ] [FORMULA...]
>   brew install FORMULA...
>   brew uninstall FORMULA...
>   brew search [foo]
>   brew list [FORMULA...]
>   brew update
>   brew upgrade [FORMULA...]
>   brew pin/unpin [FORMULA...]
>
> Troubleshooting:
>   brew doctor
>   brew install -vd FORMULA
>   brew [--env | config]
>
> Brewing:
>   brew create [URL [--no-fetch]]
>   brew edit [FORMULA...]
>
> https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md
>
> Further help:
>   man brew
>   brew home
> Jason-Paguras-iMac:~ jpagura$ git --version
> Illegal instruction
>
>
>
> On Sat, Jan 30, 2016 at 3:12 AM, Pathum Egodawatta <
> notifications@github.com> wrote:
>
>> Can you post any messages you get from homebrew? I've had lot of problems
>> with homebrew, but managed to fix it with info on forums.
>>
>> On Sat, Jan 30, 2016, 9:51 AM Jason P. <notifications@github.com> wrote:
>>
>> > I started with a clean install of OSX 10.6 on an empty partition, then
>> > downloaded the applicable software updates. I applied the recommended
>> > add-ons in the correct sequence with the recommended methods, and I
>> can't
>> > get Homebrew to install. I need help, but this has gone beyond the
>> scope of
>> > a TruFont problem.
>> >
>> >
>> > On Fri, Jan 29, 2016 at 7:12 AM, Dave Crossland <
>> notifications@github.com>
>> > wrote:
>> >
>> > > brew doctor;
>> > > brew update
>> > >
>> > > etc
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/trufont/trufont/issues/210#issuecomment-176802751
>> >.
>> > >
>> >
>> >
>> >
>> > --
>> > --
>> > Jason Pagura
>> > zimbach at gmail dot com
>> >
>> > —
>> >
>> >
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/trufont/trufont/issues/210#issuecomment-177134012>.
>> >
>> --
>>
>> ෴ ජය! ෴
>> පැතුම් එගොඩවත්ත
>> Pathum Egodawatta
>> pathum@mooniak.com
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/trufont/trufont/issues/210#issuecomment-177150662>.
>>
>
>
>
> --
> --
> Jason Pagura
> zimbach at gmail dot com
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by ultrasquid** [comment]
And right when I think I'm making progress having finally successfully installed Homebrew and Python 3, this comes up:

Jason-Paguras-iMac:~ jpagura$ brew install pyqt5
Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
qt5: OS X Mountain Lion or newer is required.
Error: An unsatisfied requirement failed this build.

**Comment by ultrasquid** [comment]
I'm unsure of whether I persuaded qt5 and pyqt5 to install. I downloaded earlier installers from their respective websites but I don't know if they were installed where they need to be.

Whatever I did wasn't good enough, though. Still couldn't build Trufont

**Comment by pathumego** [comment]
@ultrasquid did you manage to run it? README.md has latest instructions.

**Comment by adrientetar** [comment]
The binaries may be 10.7+ with the Qt build system.

**Comment by ultrasquid** [comment]
The snag is with Qt5. It requires a newer OS than my Mac is able to run. If
it could be built with an earlier Qt it might work for me, but I have no
idea whether Qt4 has the necessary resources.

On Tue, Apr 19, 2016 at 6:58 AM, Adrien Tétar <notifications@github.com>
wrote:

> The binaries may be 10.7+ with the Qt build system.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/trufont/trufont/issues/210#issuecomment-211932730>
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com
