### ISSUE TITLE
Drawing paths: Undo should activate previously active point so I can just continue drawing

### ISSUE THREAD

**Issue by madig** [trufont/trufont#211]
Currently when I place points and misplace one, I usually undo and click where I want the point to actually be. Unfortunately, this starts a new path. I have to leave pen mode and go to select mode, select the previous point and go to pen mode again. Please reactivate the previously selected point on undo so I don't have to switch modes.

**Comment by adrientetar** [comment]
trufont/defcon#1 discusses the infrastructure for this.

**Comment by davelab6** [comment]
Wouldn't this be better solved by the TruFont UI having chord keys for
tools - eg hold space for hand/panning tool, ctrl for select tool ?

**Comment by pathumego** [comment]
I agree with @davelab6 about adding that funcinailty. But still reactivating the point is needed.

**Comment by madig** [comment]
I really like the chord keys idea. The modes I use most often are selecting (and shuffling points about) and measuring distances. Where to put this wish?

**Comment by davelab6** [comment]
In Glyphs, the measure tool is on chord ctrl-alt-super

**Comment by pathumego** [comment]
@madig I added it to #176. I think @adrientetar is looking at the suggestions there. :)

**Comment by adrientetar** [comment]
I'm not sure how but this works these days.
