### ISSUE TITLE
Can't import fonts: "No module named 'extractor'"

### ISSUE THREAD

**Issue by marnen** [trufont/trufont#215]
I just downloaded the TruFont 0.2.0 Mac application from the website; I'm running it on El Capitan. When I choose File | Import…, I see an alert that says "No module named 'extractor'", and the import operation ceases. Help?

**Comment by davelab6** [comment]
@marnen please install https://github.com/typesupply/extractor

**Comment by pathumego** [comment]
@adrientetar we will pakage extractor for next release?

**Comment by marnen** [comment]
@davelab6 Thanks, I'll try that.

**Comment by codeman38** [comment]
Is there a way to install this package in the pre-packaged Mac version, or do I need to build from source?

**Comment by adrientetar** [comment]
The packaged version is old anyway. I'll look at this soon.

**Comment by adrientetar** [comment]
Fixed.

**Comment by davelab6** [comment]
Win!

**Comment by marnen** [comment]
Confirmed: font importation works fine on the current Mac version (0.4.0). Thanks.
