### ISSUE TITLE
Snapping to integers?

### ISSUE THREAD

**Issue by madig** [trufont/trufont#218]
Should there be a mode that snaps points and control handles to integers? Given that recommended practice seems to be to keep to integers, maybe it should be the default mode?

One of the more annoying behaviors of FontForge is that various operations result in floats. I like to forget to run "round to int" after each one.

**Comment by pathumego** [comment]
:+1:

**Comment by adrientetar** [comment]
Points are now snapped to integer when moving on the canvas and there is a snap function on the sidebar.
