### ISSUE TITLE
UI: "delete glyph" should be integrated into a context-menu, should not work on empty glyphs.

### ISSUE THREAD

**Issue by madig** [trufont/trufont#219]
Found this piece of functionality while setting up translation. It even works on non-existant glyphs.

**Comment by adrientetar** [comment]
I did some changes in 9bd6ba390e2e8afe3a0b5116935930ea6c7a4ce0, but there are two levels of deletion: soft with Suppr. that keeps the glyph in the glyphOrder and hard with Shift+Suppr which deletes it completely.

**Comment by madig** [comment]
Please mark user-visible text with `self.tr`! This will make integration easier.
