### ISSUE TITLE
App preferences should be separate window

### ISSUE THREAD

**Issue by brawer** [trufont/trufont#22]
TruFont’s app preferences are currently shown a document-modal dialog. However, app preferences are about the app, not any particular document; so TruFont’s behavior is a little confusing (and inconsistent with other apps). Compare eg. to the preferences window in Finder, Preview or TextEdit.

https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/WindowDialogs.html

**Comment by adrientetar** [comment]
Thanks, fixed in 3521c99123faff7592c799c585aab3162850e934.
