### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#223]
As suggested by @madig on #187 we can draft a mini tutorial on drwaing on TruFont first. With 0.3.0 we can publish it on website. Later on expanding that would make sense.

**Comment by madig** [comment]
Yes! This can also help track down usability bugs and inconsistent behavior :)

**Comment by pathumego** [comment]
Following discussions with @adrientetar I started making a list of available commands and shortcuts (here)[https://docs.google.com/spreadsheets/d/1-_vfac84YzPBcFuLQ8SDcwgnu7awm8zKBu-s5fzzzN0/edit?usp=sharing] following [this structure](http://doc.robofont.com/documentation/workspace/glyph-editor/) more or less. If you have any suggestions for a better structure, please comment.

This will be useful for UI overhaul and planning final defaults. And can be converted to UI tutorial down the line. I will complete it in coming weeks. If devs can add any new commands and shortcuts to the doc, its easy to maintain.

Anybody who wants to edit/add please request permission on the doc.
cc @madig @davelab6

**Comment by adrientetar** [comment]
Closing in favor of #520.
