### ISSUE TITLE
HiDPI on Linux?

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#231]
I just switched to using a machine with HiDPI display, things look good so far out of box (much to my surprise, but Gnome seems to have been done a good job here).

Anyway, I don’t have any Qt applications other than Trufont, and when I tried it didn’t seem to be HiDPI aware (everything looks small). _UPDATE_: When I tried to take a screenshot I found that things got improved and it looks much better now (no idea what happened), the text and the icons are OK, but the initial window size is too small and the glyph cells look small and cramped:

![2016-02-05 16-17-14](https://cloud.githubusercontent.com/assets/93914/12846091/ee253f62-cc23-11e5-86be-1df559fccf12.png)

Are there any Qt settings I’m missing or is it just Trufont/Qt bugs? What is the situation with HiPDI displays on others platforms?

**Comment by madig** [comment]
Modern GTK and Qt versions should work well enough in HiDPI environments but need to be triggered in different ways: https://wiki.archlinux.org/index.php/HiDPI#Qt_5

Launching Trufont this way gives me a bigger window and stuff with the same text size as before. Hm.

**Comment by khaledhosny** [comment]
Yup, setting `QT_DEVICE_PIXEL_RATIO=2` yesterday gave me bigger window but text was kept small, now both are big (since text is already big). Not sure what changed. Things look almost good now, but the icons are pixilated, need to figure this one out.

**Comment by khaledhosny** [comment]
It seems that having an ~/.Xresources file breaks things in Qt somehow. Anyway, waiting for Qt 5.6 to see how the improved HiDPI support fares:
https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

**Comment by davelab6** [comment]
Off topic but I'm also keen to see what http://pyparallel.org  can do for
us :)

**Comment by adrientetar** [comment]
#283 #284 #286
