### ISSUE TITLE
Constrain cutting angle in scissor tool while Shift key is pressed

### ISSUE THREAD

**Issue by brawer** [trufont/trufont#236]
In the scissor tool, after having started to cut, it would be nice if the cutting angle was constrained to 45 or 90 degrees while Shift is pressed. When Shift is released, the cutting angle would be unconstrained again.

**Comment by adrientetar** [comment]
Are you using the binary? It's pretty old actually and I'd advise running from source if you can.

I'd need to reimplement picture support in the new glyphView to keep feature-parity with the old version before releasing, I don't know if that's too important.

**Comment by adrientetar** [comment]
This is already implemented in master.
