### ISSUE TITLE
Scissor/Knife: Icon does not match tooltip

### ISSUE THREAD

**Issue by brawer** [trufont/trufont#237]
When hovering over the scissor tool, the tooltip says “Knife” which is inconsistent with the icon. Either the icon should depict a knife, or the tooltip should say “Scissor”.

**Comment by adrientetar** [comment]
Are you using the binary? It's pretty old actually and I'd advise running from source if you can.

I'd need to reimplement picture support in the new glyphView to keep feature-parity with the old version before making a new release, I don't know if that's too important.

**Comment by adrientetar** [comment]
Fixed in master.
