### ISSUE TITLE
Keyboard shortcut for editing tools

### ISSUE THREAD

**Issue by brawer** [trufont/trufont#238]
Could the tools have keyboard shortcuts? The Glyphs editor uses Select=V; Pen=P; Ruler=L; Knife=E. It would be nice to show the shortcut in the tooltip, eg. “Select (V)” or so.

**Comment by adrientetar** [comment]
Hey, S! Nice to see you trying out TruFont.

Currently it's 1, 2, 3, 4 keys for the main tools.

**Comment by adrientetar** [comment]
By the way shortcuts will be made editable in the future, I think.

**Comment by pathumego** [comment]
Yeah editable would be nice. With an external prefs file. I posted an issue
a while ago

**Comment by pathumego** [comment]
I started making a list of available commands and shortcuts [here](https://docs.google.com/spreadsheets/d/1-_vfac84YzPBcFuLQ8SDcwgnu7awm8zKBu-s5fzzzN0/edit?usp=sharing)

**Comment by adrientetar** [comment]
da7291a9ba1d50fea5c4232460812a76e058690e
