### ISSUE TITLE
Define trufont's Human Interface Guidelines

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#24]
Today at lunch I was chatting with @brawer about trufont, and I'd like to organize a hangout when @adrientetar is available (perhaps early evening Paris time this week?) to start figuring out what the overall [Human Interface Guidelines](https://en.wikipedia.org/wiki/Human_interface_guidelines#Examples_of_HIGs) for trufont should be. 

Currently it seems to follow some of FontForge's UI, RoboFont's _'multiple window mode'_, FL5, Fontographer, and 'classic' MacOS: 

![5](https://cloud.githubusercontent.com/assets/261579/10567727/cc01cc28-75ea-11e5-9f3a-432fa2ab1a6e.png)

RoboFont also has a _'single window mode',_ which is more "Cocoa like" (and similar to Glyphs and FL6)

![7](https://cloud.githubusercontent.com/assets/261579/10567728/d42cf9e0-75ea-11e5-8ddd-bc718663eefa.png)

(images thanks to http://cu14.blogspot.com.br/2014/06/robofont-guide-pt-1.html)

I also wrote up an introduction to the 3 'big ideas' for font editor UIs in https://github.com/mattlag/Glyphr-Studio/issues/94 which might be relevant to this.

**Comment by adrientetar** [comment]
What's a convenient time for you?

**Comment by davelab6** [comment]
@brawer 's schedule is most constrained as he is in California this week.
I'm in Brasil and have a few open calendar

**Comment by brawer** [comment]
Meta-question: Is trufont interested in having a user interface that is easy to use, even if it might mean some dev work?

If trufont is interested in usability, I’d suggest that we all (re-)read the various platform-specific Human Interface Guidelines before we have meetings. Also, if trufont is interested, I could ask a friend of mine who has done usability at {Apple/Claris, Adobe, Google} before she quit corporate life. She might be interested in helping trufont, but of course I cannot promise anything here.

**Comment by adrientetar** [comment]
> Is trufont interested in having a user interface that is easy to use, even if it might mean some dev work?

Of course. I work on this whenever I have time though and there are many things to do so I could surely use help doing that work. But usability is one of the priorities of this project so I am definitely willing to get all advice you can bring in this domain.

**Comment by davelab6** [comment]
On Oct 19, 2015 5:58 PM, "Adrien Tétar" <notifications@github.com> wrote:
> usability is one of the priorities of this project

Where are these prioritis defined? :)

**Comment by davelab6** [comment]
I agree, the hig specs are all on the wp page I linked to :)

**Comment by davelab6** [comment]
@brawer next week will be tricky for me as I'll be in transit to Thailand; would sometime Monday morning PST work for you?

**Comment by davelab6** [comment]
@adrientetar how do you see trufont differing from robofont on its design principles? http://doc.robofont.com/documentation/welcome-to-robofont/robofont-design-principles/

**Comment by adrientetar** [comment]
It should be quite similar. (The changes I want to make [not in principles but widgets] besides what was done now in software are having the ability to write sentences in the glyphView, with optional harfbuzz shaping.)

**Comment by davelab6** [comment]
> having the ability to write sentences in the glyphView, with optional harfbuzz shaping.)

Similar to http://doc.robofont.com/extensions/download-extensions/ramsay-st/ and http://doc.robofont.com/extensions/download-extensions/feature-preview/ ?

**Comment by davelab6** [comment]
Hangout is tomorrow, 7.30pm Paris time: https://plus.google.com/u/0/events/c9o10ma8q659pbmdttbms3kk3ds

**Comment by pathumego** [comment]
Wrote this on #106, but seems the comment belongs here..

I think Menu system should be organised according to a clear logic, so extensions could also follow the same structure. The structure we developed for FF new menus seems ok to me as a starting point. It has a lot of tools and functions that we can expect to see on trufont down the line, as part of the core editor or extensions.

- File operations
- Contour/Point operations
- Glyph operations
- Font operations 
- Windows

**Comment by madig** [comment]
Labels in Font Info and elsewhere need to be right-aligned like in https://developer.gnome.org/hig/stable/visual-layout.html.

**Comment by davelab6** [comment]
> Labels in Font Info and elsewhere need to be right-aligned

I agree

**Comment by adrientetar** [comment]
QLabel.setAlignment(Qt.AlignRight)

**Comment by pathumego** [comment]
Hmm what HIG could we use as a base for the visual design and philosophy? 

http://doc.robofont.com/documentation/welcome-to-robofont/robofont-design-principles/ 

For visual styles/ interaction
https://developer.gnome.org/hig/stable/ could be a base. But with modifications to allow crossplatform performance/adaptation.

**Comment by madig** [comment]
I don't like the current glyph set settings tab, I find it hard to understand on first glance. I drafted a new one:
![bildschirmfoto vom 2016-02-05 20-10-33](https://cloud.githubusercontent.com/assets/380829/12856309/910d3ee4-cc44-11e5-8868-6b700b767551.png)
The left pane shows the available character sets, the right pane their content. The import button is supposed to open a pop-over with "import from current font" and "import from file" in it, the files could be .enc or other types of definition files. The "(un)set default" button makes the default-set-dropdown superfluous.

Oh, and, what's that "path to glyph list" even supposed to do?

**Comment by adrientetar** [comment]
> Oh, and, what's that "path to glyph list" even supposed to do?

glyph.autoUnicode()

**Comment by madig** [comment]
Ah, so it's a kind of .nam file that maps /glyphnames to Unicode code points? That needs to stay, yes :)

**Comment by davelab6** [comment]
See eg https://github.com/google/fonts/tree/master/tools/encodings

**Comment by pathumego** [comment]
Its not same as .nam. In #122 @adrientetar wrote the format should be something like `A;0041` one per line. Currently it works with that format. But I would prefer that something a bit complex that can be used to describe a complete glyph set including composite glyphs. Could help #172 too.

**Comment by adrientetar** [comment]
![trufont__](https://cloud.githubusercontent.com/assets/1250894/23343618/d85bd2dc-fc6e-11e6-9b93-5be02adcabce.PNG)

**Comment by davelab6** [comment]
I think it's premature to close this issue. Congrats on making a single window UI :) 

But there is still a need to "Define trufont's Human Interface Guidelines"
