### ISSUE TITLE
Zoom in Glyph view

### ISSUE THREAD

**Issue by brawer** [trufont/trufont#240]
- [ ] It would be nice if one could zoom into details in the glyph view. Maybe like this:

![trufontzoom](https://cloud.githubusercontent.com/assets/1527880/12930658/e4afb148-cf79-11e5-805d-ce2a8fbf50ee.png)
- [X] On MacOS, ⌘+ would zoom in; ⌘– would zoom out. Other platforms probably have similar conventions.
- [ ] By the way, the Glyphs font editor shows a nice grid at 10000 pt and above, with all editing snapped to the grid. Really convenient for editing.

<img width="458" alt="screen shot 2016-02-09 at 10 14 50 pm" src="https://cloud.githubusercontent.com/assets/1527880/12930827/d870f422-cf7a-11e5-95ad-c2620582e2ba.png">

<img width="465" alt="screen shot 2016-02-09 at 10 15 47 pm" src="https://cloud.githubusercontent.com/assets/1527880/12930841/e381a334-cf7a-11e5-8e62-ad33b1854890.png">

**Comment by anthrotype** [comment]
BTW, is there any way to zoom in/out in the current glyph view? I could look at the source code but I'm lazy.

**Comment by adrientetar** [comment]
It's Ctrl + wheel currently.

**Comment by adrientetar** [comment]
I'll add +/-.

**Comment by anthrotype** [comment]
Thanks!

**Comment by davelab6** [comment]
Yes, hotkeys - and = for out and in would be great :)

**Comment by anthrotype** [comment]
"z" and "x" hotkeys to zoom in/out would also be nice. I think both FontLab and Robofont use those. Maybe it could be user-configurable somehow.

**Comment by anthrotype** [comment]
btw, also FontForge uses "z" and "x"

**Comment by pathumego** [comment]
Editable shortcuts would be nice for all :)

**Comment by adrientetar** [comment]
8c063ed

**Comment by anthrotype** [comment]
I'd really like to have "z" and "x" shortcut for zoom in/out, like FontLab, Robofont and FontForge also do.
I could give this a go in the spare time. Any suggestions as to where I should be looking at is welcome.

**Comment by adrientetar** [comment]
e870842c1f93909fbf532358bd9330a02fa80965

**Comment by anthrotype** [comment]
Thanks!!! 🎉

**Comment by davelab6** [comment]
Love it :)
