### ISSUE TITLE
Grouping of tools

### ISSUE THREAD

**Issue by brawer** [trufont/trufont#241]
The tools in the glyph view look very unusual (at least on MacOS). Something like this would look more familiar:

![toolbox](https://cloud.githubusercontent.com/assets/1527880/12931604/eb98ac4e-cf7e-11e5-9df6-1b733a69dfe0.png)

**Comment by madig** [comment]
I'd be interested in something like this for the glyph list in the settings dialog. No idea if vanilla Qt can do that.

**Comment by adrientetar** [comment]
https://www.kdab.com/wp-content/uploads/stories/slides/DD12/qt-devdays2012-james-turner-mac.pdf

**Comment by adrientetar** [comment]
First attempt:

<img width="1098" alt="screen shot 2016-07-26 at 7 05 40 pm" src="https://cloud.githubusercontent.com/assets/1250894/17161658/22e72b44-5364-11e6-97cd-082f1ee730ae.png">

Don't worry I'm making it better.

**Comment by davelab6** [comment]
Looks like you'll need a list of icons for someone to draw :)

**Comment by adrientetar** [comment]
> Looks like you'll need a list of icons for someone to draw :)

hehe :) it's been a bit of a backburner lately.

**Comment by adrientetar** [comment]
We won't be grouping tools, but here's what I consider final:

![tools](https://cloud.githubusercontent.com/assets/1250894/23340765/407860c0-fc3c-11e6-8a69-ae247cf5fd81.PNG)
