### ISSUE TITLE
Pinch to zoom in OSx

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#244]
Pinch to zoom does not work on OSx at the moment. Would be nice to have it.

**Comment by anthrotype** [comment]
:+1:

**Comment by adrientetar** [comment]
It works for me on Windows, I'm not sure what's needed on OSX.

**Comment by adrientetar** [comment]
https://github.com/adrientetar/defconQt/commit/97a5dcec447dc4a34eb7c42ad962142de419dca3

I think the formula for calculating isn't the greatest though as on scale levels < 1 it starts to slow down..

**Comment by pathumego** [comment]
@adrientetar Pinch to zoom is not working on macOS
