### ISSUE TITLE
Nightlies

### ISSUE THREAD

**Issue by adrientetar** [trufont/trufont#245]
http://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci/33109519#33109519

**Comment by anthrotype** [comment]
Yeah, that'd be cool. Although we also need to configure travis for osx in addition to the current linux-only setup, and possibly set up appveyor for windows.

**Comment by adrientetar** [comment]
And there's still work to do on packaging. Should be made callable from setup.py too.

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/#on-travis also has some tips on this

**Comment by adrientetar** [comment]
Not happening anytime soon.
