### ISSUE TITLE
0.3.0 User Expectations Report

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#250]
When I open 0.3.0 and ran through some basic moves, I found the following things confusing/annoying/etc :)

Font Window
- [x] When I select a cell in the table with a single click, it is highlighted with a purple color, not the Mac OS X system preference highlight color. 
- [x] When I double click a cell in the table to open a glyph view, but the new window opens in a strange position, to the right and down from the center of the screen, so i have to move it up and left

Glyph Window
- [x] I can not zoom with the -/= keys, nor -/+, nor z/x, nor modifiers of these (ctrl/alt/apple) which have been standard in popular font and vector drawing applications for decades
- [x] When I press and hold the space bar, I can not pan around the window, neither moving the pointer nor clicking and dragging the pointer
- [x] When I zoom in too far, or pan too far, using the (apple-)scroll wheels, there is no "View, Fit" or Apple-F or other key to reset the viewport to a default view that fits all points in the view
- [x] The apple-w key does not close the window, but apple-q does - instead of quitting the whole application.
- [x] The file menu only has 'close' as an option, which is really weird. Not even save? Perhaps saving is done continually in the background, like a typical web app...
- [x] The application appears to have no preferences to adjust any settings, from the glyph editing window
- [x] Its possible to zoom out to a ridiculous amount

<img width="1185" alt="screen shot 2016-03-13 at 10 35 52" src="https://cloud.githubusercontent.com/assets/261579/13729275/910a44ca-e907-11e5-9dd5-9e60a89d8863.png">

- [x] when zooming out, at some point the BCPs and other spline indictions are not displayed, but this point is misconfigured to be too far out to make sense:

<img width="384" alt="screen shot 2016-03-13 at 11 07 54" src="https://cloud.githubusercontent.com/assets/261579/13729459/f96b078a-e90b-11e5-8e52-42cf3d12fc3f.png">
<img width="355" alt="screen shot 2016-03-13 at 11 07 58" src="https://cloud.githubusercontent.com/assets/261579/13729460/f9719bc2-e90b-11e5-84d0-ff942c298c41.png">

- [x] when zooming in, at no point is a grid is shown 
- [x] When I hold the space bar, or press ```, I do not see a filled in preview of the letter, and can find no way to do this
- [x] There is no indication of the starting point or contour direction. Oh wait, there is some really super light grey halo around the first point.

<img width="900" alt="screen shot 2016-03-13 at 10 44 34" src="https://cloud.githubusercontent.com/assets/261579/13729326/a068222e-e908-11e5-8931-8d0ad15369fd.png">

- [x] I can not figure out how to turn a line segment into a curve segment. I can see that double clicking a point changes its start from line to curve, but I can't see how to add the BCPs to the line. 
- [x] Its easy to draw a segment with only 1 BCP, which is bad; Glyphs helpfully prevents you from doing this easily.

<img width="734" alt="screen shot 2016-03-13 at 10 33 17" src="https://cloud.githubusercontent.com/assets/261579/13729279/9f03710a-e907-11e5-8f0d-027f74571306.png">

- [x] There is also something weird going on with the pen tool, where these segments with 1 BCP have the point moved when the 2nd point is moved... Video here, https://youtu.be/KNw4M-3pAJ8
- [ ] At rest, there is no visual indication of when a contour is open or closed
- [ ] When using the pen tool, there is no visual indication when the pointer position will mean closing the contour (vs placing the next point very close to the first one.)
- [x] The knife tool seems to only add 1 point where it intersects a contour, and 
- [x] there seems to be no way to break a contour open by removing a point; selecting a point and hitting the backspace key merges the point into the contour
- [x] When I press apple-a to selet all points in the glyph, and hit backspace to delete them all, nothing happens
- [x] I can't seem to double/triple click anywhere to select the whole contour
- [x] The measure tool 'at rest' doesn't show any measurements or point positions
- [x] The measure tool doesn't show intersections
- [x] The layers can only be seen one at a time, there's no way to them them color/alpha values to see several at once
- [x] When I go to Glyph menu, Layer Actions, and swap, the new points are not drawn as contours:

<img width="900" alt="screen shot 2016-03-13 at 11 15 20" src="https://cloud.githubusercontent.com/assets/261579/13729510/f19aaa6e-e90c-11e5-8b85-43b7bf6725b1.png">
- [x] When I run other Layer Actions, I have to select the pointer tool and click the canvas to see the result of the operation
- [x] After that, I pressed apple-a to select all and then backspace to delete, TruFont crashed, but there was no crash report information to report what happened
- [ ] When I launched TruFont after the crash, my work was lost
- [x] From the character table view, the pull down menus suddenly have lots more options! This is super confusing. 

Preferences, Glyph sets Window
- [x] The window title is not in Title Case unlike the others
- [ ] If 'default glyph set' checkmark is unchecked, then a new font has no glyphs by default. But if a user wants this, they can add a new glyph set with no glyphs and set that as the default. I recommend removing this checkmark from the UI as I think it is pointless clutter.
- [x] After unsetting 'default glyph set', I can not set it again. I mean I can, but when I click OK and then reopen preferences, it has not been remembered.
- [ ] When I add a new glyph set item, it can not be selected as the default without closing and opening the defaults window 

<img width="604" alt="screen shot 2016-03-13 at 11 30 31" src="https://cloud.githubusercontent.com/assets/261579/13729607/168431c2-e90f-11e5-8dbd-a6cac7fefe65.png">
- [x] Import dropdown, 'import from current font', always crashes, either if the font has zero or some glyphs
- [ ] Import from current font is weird as a drop down with only 1 item. It should be a button in this case.
- [x] `Glyph list path` seems to do nothing, until the next time I launch the app, then I see

<img width="373" alt="screen shot 2016-03-13 at 11 58 26" src="https://cloud.githubusercontent.com/assets/261579/13729756/033d2c6e-e913-11e5-97cc-1e808c4d4629.png">

so I recommend attempting to parse the file for correctness after the path is input.
- [ ] The + and - buttons are weirdly long, and overall the layout is oddly grid-like and needs rethinking

Preferences, Metrics Window
- [ ] The + and - buttons are weirdly long
- [ ] There's no way to import a set of lines from a text file
- [ ] There's no way to cut, copy or paste lines (although you can paste in line contents after double clicking to place the cursor in the line)

Preferences, Misc
- [ ] The + and - buttons are weirdly long
- [ ] The default colors are ghastly :) I recommend less than full brightness

Font Window
- [ ] File, Import can not import images
- [x] File, Export by default says `Attributes required for font generation are missing: familyName styleName` but should say `Export requires a familyName and styleName. Set them in Font Info`

<img width="610" alt="screen shot 2016-03-13 at 11 44 08" src="https://cloud.githubusercontent.com/assets/261579/13729668/efc10c8e-e910-11e5-907d-8b7711cd92c2.png">

Font Features

This window needs some love, but that love should probably be directed at an extension. I think scoping this window to a direct text editor view of the features.fea file is fine, but there are a couple of things that I think can make it more useful:
- [x] The syntax highlighting is all grey, I recommend a more colorful FEA syntax file
- [ ] The features.fea file can become VERY long, so having 'code folding' in the margins can help a lot when dealing with it

<img width="940" alt="screen shot 2016-03-13 at 11 51 30" src="https://cloud.githubusercontent.com/assets/261579/13729704/f12e4ee6-e911-11e5-9aa3-9c49c24f7ce3.png">

Font Info
- [x] PostScript, Windows character set, I think this ought to be a table with checkmarks for each item, not a singleton selector list.

Python, Scripting Window
- [x] when I enter `print("Hello World")` and press apple-r, nothing happens. I think at a minimum, there should be an output window; but having said that,
- [ ] ideally I would like to see trufont use iPython Qt Notebook (Or Jupyter or whatever its called these days) by default for its default scripting environment.

Window, Groups
- [x] When I open a UFO and add a new group, this crashes

**Comment by madig** [comment]
Regarding PS->Windows character set, the spec says it's an integer attribute. So the font can only be assigned one character set.

**Comment by davelab6** [comment]
Ah, I was thinking of OS/2 codepages. :)

**Comment by davelab6** [comment]
@adrientetar perhaps to move forwards on these, it would be helpful if you ran down the checkmarks and ticked the ones you agree are issues that should be fixed, and then I can file issues for tracking each one (or directly pull requests where its papercut stuff)

**Comment by adrientetar** [comment]
No, it should stay here. Thanks for the list.

**Comment by davelab6** [comment]
@adrientetar okay; are there any tasks here you do not want to see worked on?

**Comment by madig** [comment]
> The + and - buttons are weirdly long, and overall the layout is oddly grid-like and needs rethinking

I mocked up an attempt to clean up the glyph set dialog:
![bildschirmfoto vom 2016-03-20 14-50-59](https://cloud.githubusercontent.com/assets/380829/13904753/30e2b3d0-eeab-11e5-9574-6c30cfd27f74.png)
"Import" should have the option to import a set from the current font as well as from a file (FontLab's .enc files). The default Latin set should be non-removable and the fallback default if the user removes another default set. I'd like to use images for + and - like GTK and some Qt apps do, but there doesn't seem to be a built-in way to do that.

**Comment by adrientetar** [comment]
> There is also something weird going on with the pen tool, where these segments with 1 BCP have the point moved when the 2nd point is moved... Video here, https://youtu.be/KNw4M-3pAJ8

I couldn't reproduce this, can you explain how to get this behavior?

**Comment by davelab6** [comment]
I also can not reproduce. I don't remember doing anything unusual to get that state, though. .

I did find that the 'jumping' of BCPs when moving them and they are set up as tangents was a bit annoying, and I think the jump should happen earlier (when it it set, without needing to move it to trigger the update) https://youtu.be/H_ZgBQy7DN8

**Comment by pathumego** [comment]
@davelab6 @adrientetar If I move these things to single issues is it easier to discuss and track? Or do you prefer it like this. Some of the things @davelab6 mentioned here are already filed in separate issues.

**Comment by adrientetar** [comment]
I like when issues open when issues happen.

**Comment by davelab6** [comment]
@pathumego can you edit all issue comment texts? I think you can. If you can, I suggest to tick the item box on the above report and edit it to say (tracked in #whatever)

**Comment by pathumego** [comment]
@davelab6 Yep, thats what I was doing so far, I will stick with that :)
