### ISSUE TITLE
Moving files from FontForge

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#251]
@adrientetar I have working `sfd` files of a project that I'm working on. I would like to switch to Trufont. But when I open the UFO's exported from FF I keep getting this.
<img width="419" alt="screen shot 2016-03-15 at 5 45 09 pm" src="https://cloud.githubusercontent.com/assets/6846609/13787888/b0f6c748-ead5-11e5-810b-f6ab252aa83e.png">

I realise this is because of how I've placed the off curve points. Is there a way to fix/spot the problematic glyphs using FF and python?

**Comment by adrientetar** [comment]
I have no idea (never heard of this happening in FontForge) but I don't think it can be fixed inside since the UFO codegen happens on export.

**Comment by davelab6** [comment]
cc @kelvin13 , who is also trying to migrate projects from SFD/FF to UFO/TF

**Comment by adrientetar** [comment]
I will work on that on the near future. It will take some non-trivial changes to ufoLib.

**Comment by khaledhosny** [comment]
In case anyone is interested, I wrote https://github.com/khaledhosny/sfd2ufo to move some of my fonts to UFO, it does not handle everything (only glyphs and some font information for now) and need FontForge Python module.

**Comment by adrientetar** [comment]
cc @frank-trampe

**Comment by frank-trampe** [comment]
@pathumego, would you post the file? It would be much simpler in addressing this problem to know whether the file is corrupt or if TruFont is at fault.

**Comment by frank-trampe** [comment]
@khaledhosny, what does your tool do that exporting U. F. O. from FontForge misses? Are there any features from it that we ought to integrate into FontForge?

**Comment by pathumego** [comment]
@frank-trampe https://github.com/pathumego/matd-project/blob/gh-pages/sources/sfd/experiment-sinhala-0.sfd

**Comment by frank-trampe** [comment]
Could you put the U. F. O. somewhere too?

**Comment by pathumego** [comment]
@frank-trampe  here it is: [files-for-ff2tfbug.zip](https://github.com/trufont/trufont/files/225779/files-for-ff2tfbug.zip)

**Comment by frank-trampe** [comment]
@adrientetar, can you break on the error message and tell me which glyph it is? (I'm at the airport.)

**Comment by adrientetar** [comment]
The UFO file in the zip opens up fine, actually.

**Comment by frank-trampe** [comment]
I love issues like this!

**Comment by pathumego** [comment]
@frank-trampe @adrientetar Some of my files anyway worked fine. I did a full cleanup of files earlier and maybe it fixed the thing. Ill dig up a file that has the error. I didn't realise what I posted worked. :)

**Comment by khaledhosny** [comment]
> what does your tool do that exporting U. F. O. from FontForge misses?

It exports guidelines, unicodes (altuni in FontForge lingo). But the idea is that it is simpler to use existing UFO libraries with FontForge Python API than to fight the C code in FontForge, and you end up with UFOs much closer to what everyone else have without much effort. Note that sfd2ufo is not complete as it does not export font features, anchors or kerning because I don’t currently need that, but it should be much easier to extend it than hack C code.
