### ISSUE TITLE
Make a "Diving Into TruFont Development" tutorial?

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#252]
As part of the effort to grow the developer community, would something like http://www.lihaoyi.com/post/DivingIntoOtherPeoplesCode.html have impact? :) 

cc @eliheuer

**Comment by adrientetar** [comment]
Check out my talk next week.

**Comment by davelab6** [comment]
I'd like to keep this open and assigned to me until the talk notes etc are on the website :)

**Comment by eliheuer** [comment]
What would be a good first task for for a "Diving Into TruFont Development" tutorial? I want to start working on this issue. 

I'm thinking editing the drawing tools would be a good place to start. Like, changing the shortcut key or the color of the ruler line.

**Comment by davelab6** [comment]
The recent PR for a 'hand tool' by Cosimo was cool - although Adrien implemented it slightly differently to a regular extension (because its a core feature, I guess) - so I would suggest writing a step by step that shows how to create a simple drawing tool for making rectangles or ellipses. 

(The way hotkeys are defined at the moment is (AFAICT) ad-hoc, and I guess it will require some refactoring to centralize and make run-time reconfigurable; similarly for canvas colors and other attributes.)
