### ISSUE TITLE
Package booleanOperations with pyqtdeploy

### ISSUE THREAD

**Issue by adrientetar** [trufont/trufont#257]
Apparently pyqtdeploy traditionally didn't support those modules directly but they can be compiled or included with [a directive in Other Modules](https://github.com/GreatFruitOmsk/pyqtdeploy/blob/master/NEWS#L19).

For reference, here's the OSX pyqtdeploy file: https://gist.github.com/adrientetar/f53febbdb05615078bc0341f1657aeca 
(Qt and Python paths should point to statically compiled libs, see pyqtdeploy getting started instructions.)

**Comment by anthrotype** [comment]
Here they say that pyqtdeploy also allows to embed extension modules as dynamically loaded libraries (`foo.so` or `foo.pyd`), not just as than statically compiled ones (`foo.a` or `foo.lib`):

http://pyqt.sourceforge.net/Docs/pyqtdeploy/tutorial.html

> pyqtdeploy also supports the dynamic loading of extension modules that are installed adjacent to the application executable (i.e. in the same directory as the application executable). This is useful for packages that are implemented as a combination of pure Python modules and extension modules where the extension modules do not support being statically compiled...
