### ISSUE TITLE
0.3/0.4 Showstoppers

### ISSUE THREAD

**Issue by kelvin13** [trufont/trufont#258]
Hi, i'm a designer who is taking a look at this editor (i'm working with dave @davelab6 btw) and there's a few things that are keeping me from really using this editor to develop an actual font
- [x] Lack of Ctrl-Z/Ctrl-Y in the glyph editor window. Sorry, gotta have that key shortcut. (Ctrl-S would also be nice but I can live with going File → Save)
- [x] Integer snapping. Why is it whenever I move a point it gets mangled into floats? And there is no round points to int function either. (Or I haven't discovered it, which isn't much better in terms of UI design) _Absolute_ showstopper—no font of decent quality can be made without integer tools
- [ ] No HV curve points. HVs were my favorite thing about fontforge. They make life so much easier when editing fonts. Editing curves without HV control is very very difficult, and without integer snapping, impossible.
- [x] No guidelines or bg layers. Trufont seems to have layers, but I can only view one layer at a time. This makes the layers pretty much useless except for stashing junk in. Guidelines are especially critical, no alphabet can be drawn in any consistent manner without guidelines. If guidelines are already in Trufont, they are not discoverable.
- [x] No coordinates. When working on any serious design you need to know the math on each of your points. Fontforge provided this (somewhat cumbersomely) in the Get Info dialog. Trufont doesn't have this; it doesn’t even have a ruler on the side. I need to know the numerical coordinates of all of my points. Similarly, I can find no option to display the sidebearing values of the glyph. Trufont seems very weak in the math department, and perhaps this is its greatest weakness as an editor (after the lack of integer snapping).
- [x] Control points are too difficult to select. Why is the selection radius like 2px? That is way too small. And I can find no option to increase the selection radius in the preferences.
- [x] Metrics window only goes down to 50pt. When I'm designing a text face, I need to know what my design looks like at small sizes. I see no reason why the Metrics window doesn't allow an arbitrary point size to be entered into it.
- [x] No panning in the glyph view. This is probably the least annoying of the showstoppers, but it can create situations where I am literally unable to pan the view over to see my glyph (see below where the h scrollbar is all the way to the right but I still can't see the rest of my glyph despite an abundance of space to the left) (in #275)
  ![selection_019](https://cloud.githubusercontent.com/assets/2556986/14550407/79a97834-0296-11e6-8c76-02f23174f94b.png)

sorry if i'm being a pain in the butt but i think these things really need to be fixed before trufont is usable for any real font development or even editing.

If most of these problems are related to the glyph view, that is because 96% of a font developer's time is spent in the glyph view, and Trufont's glyph view seems rather sparse.

**Comment by adrientetar** [comment]
> Lack of Ctrl-Z/Ctrl-Y in the glyph editor window.

It's there:

![undo](https://cloud.githubusercontent.com/assets/1250894/14552409/659297ac-02de-11e6-94a3-9ee3f4c85b1b.PNG)

On GNU it's Ctrl+Shift+Z to redo.

> No guidelines or bg layers.

0.4.0 shows all layers until more is done in this area.

> No coordinates.

There's a mode to display numbers aside of the point but no way to enable it for now. And enabling it for all point and all zoom sizes creates clutter. TL;DR there is work to do.

> Control points are too difficult to select.

I noticed that too and I've been thinking about what formula I should use. Maybe I'll add one more pixel to selection radius compared to display radius.

> Metrics window only goes down to 50pt.

It's doesn't, the lower limit is 6pt. That's the predefined values in the combobox but Ctrl+scrolling over the glyphs widget will scroll in small steps otherwise you can click on the combobox text and type a custom point size value.

> see below where the h scrollbar is all the way to the right

First time I see this, it's maybe a problem when resizing the window... normally the width is the glyph width (in white) + 1000 units on each side.  
Can you try 0.4.0 and if it persists send me the font and steps to reproduce? My address is written [here](http://adrientetar.github.io/doc/cv/CV_en.pdf). Thanks.

**Comment by davelab6** [comment]
> On GNU it's Ctrl+Shift+Z to redo.

Please explain why? :)

**Comment by davelab6** [comment]
> No panning in the glyph view

This works for me using the scroll functions of the trackpad on my mac

**Comment by davelab6** [comment]
Also a lot of this stuff can be done with extensions, which are coming soon
:)

**Comment by adrientetar** [comment]
> Please explain why? :)

It's the default in GNOME and KDE (well, in Qt shortcuts at least) e.g. gedit uses Ctrl+Shift+Z.

**Comment by kelvin13** [comment]
> On GNU it's Ctrl+Shift+Z to redo.

Yes, but Ctrl-Z does not work at all, much less Ctrl-Shift-Z. When I press Ctrl-Z, nothing happens. Which is very misleading how the menu has “Ctrl Z” written next to “Undo”.

> 0.4.0 shows all layers until more is done in this area.'

0.4, which I assume is the current repo, fails to run. 

> There's a mode to display numbers aside of the point but no way to enable it for now. And enabling it for all point and all zoom sizes creates clutter. TL;DR there is work to do.

Is there a way to mark certain points to display coordinates and deltas? And still no side ruler or sidebearing display

> I noticed that too and I've been thinking about what formula I should use. Maybe I'll add one more pixel to selection radius compared to display radius.

Good idea. Any sense when this will be in Trufont?

> It doesn't, the lower limit is 6pt. 

Gotcha. Would be nice if autocomplete was disabled when typing in the box though.

> Can you try 0.4.0 and if it persists send me the font and steps to reproduce?

I'll try but i think 0.4 is down atm

This still doesn't address Integer snapping and HV points which were arguably the most important showstoppers…

**Comment by kelvin13** [comment]
@davelab6 
>Also a lot of this stuff can be done with extensions, which are coming soon

Perhaps Round Glyph To Int can be made into an extension but integer snapping and HV points really sound like things that should be hard coded into the editor. There are very very few instances where you would want to preserve floats, usually only when dealing with intermediate transformations (rotation, scale, etc.). I don't know how your extension system is set up, but i think this is too low-level for extensions to handle.

**Comment by graphicore** [comment]
> There are very very few instances where you would want to preserve floats, usually only when dealing with intermediate transformations (rotation, scale, etc.).

Are there any technical reasons for this? It sounds a bit like a preference to me. I'm just curious about the reasoning.

**Comment by adrientetar** [comment]
> Are there any technical reasons for this? It sounds a bit like a preference to me. I'm just curious about the reasoning.

This says it all tbh: http://blog.typekit.com/2015/10/01/smoother-curves-with-decimal-coordinate-values/

But it's good to remove floats when you don't need them as they take extra space.

Related bug in ufo2ft: https://github.com/googlei18n/ufo2ft/issues/24 (smart pruning of floats at compile-time)

**Comment by kelvin13** [comment]
Rounding should be done as you edit, so floats never get introduced in the first place and designs are much easier to handle and edit

**Comment by kelvin13** [comment]
@graphicore it also helps in design, to keep stem widths consistent, for example. And it helps give designers piece of mind, knowing that their 90 ‰ stem isn’t actually 90.4‰

**Comment by madig** [comment]
I'd second a snap-to-integers mode. How about a making it an option in the menu that's on by default and assigning a modifier key so that people can float if they need to but keep to simple integers in all other cases? Or snapping to integer by default and using a modifier key for floating point placement?

**Comment by kelvin13** [comment]
@madig I think that is a very good idea.

**Comment by adrientetar** [comment]
f7166a15751f25f76c30e1af4bacfabc69c92e97 should make selection radius inline with display. Parameters will come-in later on.

**Comment by kelvin13** [comment]
thanks!!

**Comment by adrientetar** [comment]
I think everything in this issue is taken care of. There won't be HV points built into the editor, though.
