### ISSUE TITLE
Trufont 0.4 Windows fails to run

### ISSUE THREAD

**Issue by jtanx** [trufont/trufont#261]
I'm not sure if I'm missing files, but if I try to run it, I get:

![trufont](https://cloud.githubusercontent.com/assets/5137410/14560832/c2dfdec2-0344-11e6-8aad-2af1b3125342.png)

**Comment by anthrotype** [comment]
Same here.

**Comment by adrientetar** [comment]
Yeah, I couldn't track it until today's workshop. When running from the source it works fine so I'm not yet sure what's wrong here.

**Comment by adrientetar** [comment]
By the way I'm still using pyinstaller from Windows and GNU and I expect using pyqtdeploy will address this.

**Comment by adrientetar** [comment]
Fixed build is inbounds.

**Comment by davelab6** [comment]
I suggest that next time, rather than adding a 0.4.0.fixed.zip, making a
0.4.1 :)
