### ISSUE TITLE
Missing metrics values in the font into leads to a crash in the font view

### ISSUE THREAD

**Issue by kelvin13** [trufont/trufont#268]
If the font view is zoomed in enough and the designer has not specified certain metrics (like Cap height), trufont will crash.

Easily fixable by replacing 
```

        lines = set((0, font.info.descender, font.info.xHeight,
                     font.info.capHeight, font.info.ascender))
```
on line 136 of `src/defconqt/Lib/defconQt/representationFactories/glyphCellFactory.py` with
```
        lines = set(k for k in (0, font.info.descender, font.info.xHeight,
                     font.info.capHeight, font.info.ascender) if k is not None)
```

but this line of code seems to magically appear during build so i don't know how to fix it in source

**Comment by adrientetar** [comment]
Thanks. https://github.com/adrientetar/defconQt/commit/d08bc9fa2f4caac0365487cd9e291d1cba04514c should fix this.
