### ISSUE TITLE
Why does half the codebase live in GH:adrientetar/defconQt ?

### ISSUE THREAD

**Issue by kelvin13** [trufont/trufont#269]
Trufont’s UI seems to live in @adrientetar ’s defconQt repo which makes it very difficult to propose even small changes to many parts of Trufont. Some 70% of trufont's functionality is squirrelled away in the defconQt repo which gets downloaded from github each time we build trufont. This doesn't make a lot of sense to me.

**Comment by kelvin13** [comment]
For example, if I want to make improvements to the glyph line widget, I can't do that because that code is controlled by the remote defconQt repo, and it’s a very awkward workaround to have to make a second fork of defconQt, push to that publicly, swap out adrien’s repo for my own fork at buildtime and then change it back before pushing to trufont remote

**Comment by anthrotype** [comment]
Keeping a separate defconQt library is actually a great idea. It allows others to write defcon+PyQt font editing applications which are not necessarily tied to Trufont. 
You simply need to fork defconQt, clone it and 
    pip install -e defconQt
from your cloned repo's folder. The you do your edits, commit, push to your remote e send pull requests.

**Comment by anthrotype** [comment]
Didn't mean to be so brutal ;)
I was writing from my phone and I inadvertently pushed the "close and comment" button..
I mistyped the command above, it should read:

    pip install -e .

The dot means the current working directory of course.

**Comment by kelvin13** [comment]
well that is complicated and confusing but i guess i'll go with it. I do wish it didn't have to go through the global python package install because that's a lot of installs to have to do & a lot of things can go wrong, especially if you have many versions of python and pip installed. If they were in the same repo, DefconQt could just be imported from within the folder, and trufont could be self contained and not rely on an egg link in the system python3.5 folder

**Comment by khaledhosny** [comment]
It is not as bad as you make it. I had to hack something in Trufont the other day and it was just a few minutes of minutes to find that I code I need is in defconQt, hack it (I already had it cloned and `pip install -e`’d as part of installing Trufont), try it and send a pull request.

**Comment by anthrotype** [comment]
You should not use the global system Python. I think we do recommend in the REAMDE to install in a self contained virtual environment.

**Comment by khaledhosny** [comment]
I don’t even use virualenv myself, I install the few Python module I need with `pip install --user` since they are rarely in conflict with each other.

**Comment by anthrotype** [comment]
For PyQt5, you can copy the apt-get-installed one inside your virtualenv directory, if you really wish to make it self contained.

**Comment by anthrotype** [comment]
Whatever suits you best. On OSX and Windows it is now possible to pip install pyqt5 directly from PyPi without no brew and stuff inside a real virtualenv, btw.

**Comment by kelvin13** [comment]
okay i get it now. Wouldn't it be a good idea to move the repo under the trufont umbrella at least though

**Comment by davelab6** [comment]
On 17 April 2016 at 16:10, Kelvin <notifications@github.com> wrote:

> Wouldn't it be a good idea to move the repo under the trufont umbrella at
> least though
>

+1

**Comment by kelvin13** [comment]
@adrientetar are you ok with this?

**Comment by anthrotype** [comment]
I really don't see what is the problem with defconQt package being under @adrientetar's name, instead of "trufont"...

**Comment by kelvin13** [comment]
because there are now multiple people working on it and it makes sense for it to be under the shared project umbrella

**Comment by davelab6** [comment]
>> Why does half the codebase live in GH:adrientetar/defconQt ?
> 
> I really don't see what is the problem with defconQt package being under @adrientetar's name, instead of "trufont"...

It makes it harder to understand the project's footprint and progress

**Comment by adrientetar** [comment]
defconQt can (and probably will) be used as a basis of all defcon+Qt applications, not just TruFont. For this reason it is separate from the TF packages.

**Comment by davelab6** [comment]
Sure, having a separate repo for it makes sense. But why not move it to the trufont org?

**Comment by kelvin13** [comment]
defconQt is inextricably related to trufont. It may be true that other projects may want to use defconQt, in which case there is no problem if the repo is hosted here. But it makes no sense to have to search for your private repo every time someone wants to look at defconQt

**Comment by kelvin13** [comment]
is there going to be a decision on this or is it just gonna get pocket vetoed

**Comment by davelab6** [comment]
I agree with Kelvin; it is kind of weird to have the trufont org set up
with a team of people who can review and commit things, and then have a
major piece that community is gathered around be in the project lead's
repo.

**Comment by davelab6** [comment]
why not move it to the trufont org?

**Comment by davelab6** [comment]
https://github.com/adrientetar/defconQt still lives in your user; I guess you will not transfer it to https://github.com/defcon . Oh well :)
