### ISSUE TITLE
[windows] no button icons in glyphWindow toolbar

### ISSUE THREAD

**Issue by anthrotype** [trufont/trufont#271]
I used pip to install the latest `pyqt5-5.6.dev1604121819` wheel available from PyPI inside a fresh virtual environment. I then installed all the requirements as well as the TruFont app itself.
However, the icons in the glyphWindow's toolbar are not showing. I'm not sure why.

![screenshot](https://www.dropbox.com/s/h1jos2yuf2d27dp/Trufont-no-buttons-win.png?raw=1)

**Comment by anthrotype** [comment]
I also tested with the PyQt5 5.5.1 official Windows installer and Python 3.4 (x64). The glyph toolbar icons are not being displayed. The operating system is Windows 7 Pro SP1.

**Comment by adrientetar** [comment]
The reason it may fail is if the SVG module is absent, but I think it's in the Windows installer at least..

**Comment by anthrotype** [comment]
Hmm. How did you install/configure PyQt5 on your Win10 machine? And which PyQt and python versions are you using?

**Comment by adrientetar** [comment]
Python 3.4 32bit with the PyQt 5.5.1 installer.

**Comment by anthrotype** [comment]
It looks like it's the virtual environment. If I run it using the globally installed PyQt5 it works. If I install PyQt5 inside the virtualenv (or make a `--system-site-packages` sort of env), it cannot find the paths to the plugins.
Still investigating.

**Comment by anthrotype** [comment]
ok, it was __not__ the fact I was using virtualenv, nor the pyqt5 wheel package that was missing anything.

The problem is that the `{virtualenv}\Lib\site-packages\PyQt5` folder must be in the users `%PATH%` in order for PyQt to work properly on Windows.

The official Windows installer from Riverbank's website prepends the PyQt5 folder location to the system's PATH environment variable: `C:\Python34\Lib\site-packages\PyQt5`
On the other end, pip *does not* do that, and in fact it cannot do it.

So the solution I found if one wants to run TruFont on Windows with pip-installable pyqt5 is to make sure the PyQt5 folder is added to one's PATH before launching the app. E.g.:
```batch
SET PATH=C:\UsersLocal\cosimo.lupo\Documents\venv\trufont\Lib\site-packages\PyQt5;%PATH%
```
In my case, the PyQt5 folder was installed in the virtual env's site-packages. If one `pip install pyqt5` system-wide, then it will be found in `C:\Python35\Lib\site-packages\PyQt5` or similar.

We should probably update the README.md as well (again)...

**Comment by adrientetar** [comment]
Oh well. The README had gotten too compact to be real.

**Comment by pathumego** [comment]
@adrientetar lol maybe after all it is a good idea to keep the README as a readme and move the install stuff to `./INSTALL.md `

**Comment by anthrotype** [comment]
there is another workaround, but it requires patching the `PyQt5.__init__.py` module...
Basically, you insert the PyQt5 folder in the environment `%PATH%` variable, before the rest of the DLLs are loaded.

I proposed it in the PyQt mailing list. Let's see what they reply:
https://www.riverbankcomputing.com/pipermail/pyqt/2016-April/037313.html

```python
import os as _os
import platform as _platform

if _platform.system() == "Windows":
    # on Windows we need to ensure PyQt5 is in the %PATH% for DLLs to be loaded
    _pyqt5_dir = _os.path.dirname(__file__)
    _env_path = _os.environ.get("PATH", "")
    if _pyqt5_dir not in [pth.rstrip(_os.sep) for pth in _env_path.split(_os.pathsep)]:
        _os.environ["PATH"] = _os.pathsep.join([_pyqt5_dir, _env_path])
```

**Comment by anthrotype** [comment]
> PyQt5 v5.6 wheels for 64-bit Linux, 64-bit OS X and 32 and 64-bit Windows can now be installed from PyPI

https://www.riverbankcomputing.com/pipermail/pyqt/2016-April/037388.html

**Comment by anthrotype** [comment]
I confirm that the current issue (the svg button icons not showing up) is now fixed with the latest PyQt5 5.6 wheel for Windows.

Also the Linux 64-bit wheel works. I tested on a Ubuntu 14.04 VM, same as the one we were using on travis to run the tests. We could setup Travis to test both OS X and Linux.

**Comment by adrientetar** [comment]
> We could setup Travis to test both OS X and Linux.

Great news! Would you work on this? Otherwise we should open up an issue for it.

**Comment by anthrotype** [comment]
i'll do that.
