### ISSUE TITLE
Font view bug

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#272]
On size 90, the font view look like this. Less than 90 its not broken. On Mac, HEAD
<img width="1920" alt="screen shot 2016-04-20 at 10 28 45 pm" src="https://cloud.githubusercontent.com/assets/6846609/14691114/512962ec-0747-11e6-9e9d-f4421edac800.png">

**Comment by adrientetar** [comment]
Yes it draws the metrics in larger sizes. I guess it shouldn't do so for template glyphs.

**Comment by davelab6** [comment]
Doesn't look broke to me ;)

On 20 April 2016 at 17:34, Adrien Tétar <notifications@github.com> wrote:

> Yes it draws the metrics in larger sizes. I guess it shouldn't do so for
> template glyphs.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trufont/trufont/issues/272#issuecomment-212616814>
>



-- 
Cheers
Dave

**Comment by adrientetar** [comment]
c3f6cfc7fb65d5df2769200a984e1869b54070cc

**Comment by pathumego** [comment]
👍
