### ISSUE TITLE
Matrics window more key functions

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#274]
Now with tab key I can jump focus to next glyph on the table. Can we enable jumping up and down to to R and L value? `alt+UP/DOWN` could be used

**Comment by adrientetar** [comment]
Actually Alt+Up/Down is already there by default on Windows, but not on OSX. I noticed that a while ago when I did some testing.

**Comment by pathumego** [comment]
Nice! Have you seen this? https://www.youtube.com/watch?v=lPhzrUc6bq0

**Comment by adrientetar** [comment]
Metrics window is on the way out.
