### ISSUE TITLE
Pan in preview mode 

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#275]
Hold spacebar to pan in Glyph view. 
This is requested in #176 #250 #258.

**Comment by anthrotype** [comment]
Preferably, not just the space bar (like FF), but space bar *and* mouse click-drag, with the cursor toggling to "hand" tool (like Glyphs.app)

**Comment by pathumego** [comment]
@anthrotype 👍

**Comment by adrientetar** [comment]
You can click mouse wheel to pan. Spacebar to pan isn't yet implemented.

**Comment by adrientetar** [comment]
baed42489c673e04e61303bd99c65b7ace2342e0
