### ISSUE TITLE
"Smart"-sorting feature

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#28]
"Smart sort" does not intuitively describe the feature.

What does it do? We should choose a more descriptive name for this feature.
Behdad suggests avoiding "super"/"Smart"-feature naming scheme in general because it is typically meaningless.
- [ ] Specify the desired feature (for documentation purposes)
- [ ] Choose a better name for it

**Comment by adrientetar** [comment]
> What does it do?

It's called "canned design" in defcon, basically it's a combination of multiple sorts with some rather arbitrary criteria that yield an optimized sorting order that resembles Tal Leming's preferred order.

Documentation says "Canned sorts are combinations of simple, complex and custom sorts that give optimized ordering results."

**Comment by felipesanches** [comment]
Should we call it "Canned sort" as well then? Or even something better?
Maybe we should add tooltip text to these options, so that we can better inform the users.

Anyway... the long description you just provided does not seem much more meaningful to the users than "This feature does a lot of magical sorting stuff" :-)

**Comment by adrientetar** [comment]
> Should we call it "Canned sort" as well then?

Canned is a bit obscure, smart sort says this is an optimized default that was arbitrarily chosen as a good ordering.

> Maybe we should add tooltip text to these options, so that we can better inform the users.

Yes, I will do that with a description.
