### ISSUE TITLE
trufont/defcon/python3-ufo3 does not work with current ufoLib

### ISSUE THREAD

**Issue by anthrotype** [trufont/trufont#280]
a few days days ago, Tal added a commit to upstream ufoLib:
https://github.com/unified-font-object/ufoLib/commit/185c04220d2832ce5c2186c2f43c4504a5901cda

Among other things, this changed the signature of `ufoLib.validators.kerningValidator` function: it now takes only one positional parameter.

The problem is the `trufont/defcon` fork -- the one specified in Trufont's requirements.txt -- still attempts to call `kerningValidator` with two positional arguments, thus raising:

```
TypeError: kerningValidator() takes 1 positional argument but 2 were given
```

https://github.com/trufont/defcon/blob/python3-ufo3/Lib/defcon/objects/font.py#L700

BTW, the upstream defcon/ufo3 no longer calls the `kerningValidator` function in the `font` module:
https://github.com/typesupply/defcon/commit/ac81bd742a0b2f6238d59f7b4267ffe808360d44

We either need to freeze the ufoLib commit in the requirementx.txt to the commit before the above mentioned change, or we update the trufont/defcon fork to not call that function any more.

Or we finally have one single upstream, py23-ufo3 defcon (@moyogo is working on that).

**Comment by adrientetar** [comment]
https://github.com/trufont/defcon/commit/db1105245c0c7ec6f98b45342c1d94bc5a8d4fd6

Until upstreaming is done.
