### ISSUE TITLE
How to delete a glyph?

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#287]
There are menu items to cut, copy, paste or add new glyphs, but nothing to delete an existing glyph. Am I missing something or is there no way currently to delete a glyph? The closest I can find is cut, but is clears the glyph and don’t delete it.

Assuming the answer to my last question is yes, what would be the best way to implement this, a new delete menu item or to modify cut to also delete the glyphs (the later seems logical to me, cut should remove the glyphs it cut completely).

**Comment by adrientetar** [comment]
Shift+Del?

**Comment by davelab6** [comment]
Would be great to have pull downs for all hotkey actions so that hotkeys
are discoverable :)

**Comment by khaledhosny** [comment]
Shift+Delete does nothing here, or do you suggest using that for the new delete functionality?

**Comment by adrientetar** [comment]
Works for me.

**Comment by khaledhosny** [comment]
I can’t find where the code that is responsible for this to debug it, any pointers?

**Comment by adrientetar** [comment]
a664a111fffbdab34d6b6c286b07cf6ca28aed26
