### ISSUE TITLE
connecting paths and documentation

### ISSUE THREAD

**Issue by guidoferreyra** [trufont/trufont#288]
Hi! I can't join two paths. I tried overlapping the nodes but nothing happens. I don't have idea how to do it. Also I think it would be great something like a manual on how use the app or drawing paths.

Best regards!

**Comment by adrientetar** [comment]
Yeah you can't break or join paths currently, I should make it work.

> Also I think it would be great something like a manual on how use the app or drawing paths.

I personally don't have time for this at the moment but if someone wants to work on it I'll take it in.

**Comment by guidoferreyra** [comment]
Hi Adrien! Thanks for the answer. I think join paths is vital or the possibility to continue a path. Is imposible to draw a shape without this.

**Comment by adrientetar** [comment]
> I think join paths is vital

I do, too. I'll get it in. Thanks for your interest!

**Comment by adrientetar** [comment]
It is now possible to

1. break contour by pressing Alt+Del (or Ctrl+X) with an onCurve selected
2. join contour by dragging an onCurve at the edge of an open contour onto another

**Comment by guidoferreyra** [comment]
Fantastic Adrien! Is this available right now or in the next release? 

Regards.

**Comment by adrientetar** [comment]
> Is this available right now or in the next release?

Right now in the master branch, or in the next release. ;)  Thanks.
