### ISSUE TITLE
How to improve zooming?

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#289]
In _Pinch to zoom in OS X_ (#244) @adrientetar said,

> I think the formula for calculating isn't the greatest though as on scale levels < 1 it starts to slow down...

So this issue is to track improving zoom in various ways. 

Eg, 
- [ ] improving the formula for calculating the rate of zoom change on pinch #244;
- [x] showing a grid when zoomed beyond a certain level;
- [x] not allowing to zoom out past a certain level; 

<img width="900" alt="screen shot 2016-06-17 at 15 59 26" src="https://cloud.githubusercontent.com/assets/261579/16162933/864fbb08-34a4-11e6-9244-4e01b36a8495.png">

Other ideas?

**Comment by madig** [comment]
- [ ] Zooming by Ctrl+mouse wheel should zoom where the mouse pointer is

**Comment by pathumego** [comment]
See #240 too

**Comment by pathumego** [comment]
All fixed and being discussed elsewhere
