### ISSUE TITLE
rename python module from "defconQt" to "trufont"

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#29]

**Comment by davelab6** [comment]
I'm not sure about this, since this name is logical; it is comparable to defconAppKit, and potentially the trufont editor project will grow to include other python classes that should not live within the defconQt module.

**Comment by adrientetar** [comment]
Yes. Also, TruFont is just a brand-name. You can install the defconQt module and use the widgets independently of TruFont itself. defconAppkit works similarly except that in our case the whole application is open-source so (at least now) there is no difference between the package and the application.

**Comment by felipesanches** [comment]
Cool!
