### ISSUE TITLE
0b3770206dfa1b2fa657b7f4f6d667a75844eacc introduced a SyntaxError

### ISSUE THREAD

**Issue by ctrlcctrlv** [trufont/trufont#290]
Commit https://github.com/trufont/trufont/commit/0b3770206dfa1b2fa657b7f4f6d667a75844eacc by @adrientetar just introduced a SyntaxError on line 158. It should be `is not None`.
```
[osboxes@osboxes trufont]$ python3 Lib/trufont/__main__.py Traceback (most recent call last):
  File "Lib/trufont/__main__.py", line 3, in <module>
    from trufont.objects.application import Application
  File "/home/osboxes/Workspace/trufont/Lib/trufont/objects/application.py", line 4, in <module>
    from trufont.drawingTools.selectionTool import SelectionTool
  File "/home/osboxes/Workspace/trufont/Lib/trufont/drawingTools/selectionTool.py", line 158
    if self._itemTuple not None:
                              ^
SyntaxError: invalid syntax
```

When that error is corrected it crashes anyway.

![2016-07-07-125608_2736x1624_scrot](https://cloud.githubusercontent.com/assets/838783/16680141/920b3e0e-44e4-11e6-8f39-26f55afd3360.png)

Please guys, run your code at least once before pushing to master. I'm in the process of porting libspiro to TruFont and this momentarily broke my development environment. What's worse now TF is broken for everyone who installs via GitHub.

**Comment by anthrotype** [comment]
It would have taken you less time if you just fixed it by sending a PR... 😜

**Comment by ctrlcctrlv** [comment]
@anthrotype Perhaps you missed the last part...it's still broken even with the SyntaxError repaired. I'm not really sure what this commit was going for: no other comment other than a vague commit message so refrained from attempting to fix it.

**Comment by ctrlcctrlv** [comment]
And in case you're curious about the `libspiro` port, that's going fine, thanks :stuck_out_tongue_winking_eye: 

```MOVETO -100.0 0.0 0
CURVETO -100.00000000072427 26.179938779949882 -89.22269036152042 52.19866587652838 -70.71067811894564 70.71067811865606
CURVETO -52.19866587637087 89.22269036078374 -26.17993877994988 99.9999999995088 0.0 100.0
CURVETO 26.17993878028982 100.0000000004912 52.19866587753248 89.22269036235397 70.7106781204033 70.71067812004159
CURVETO 89.22269036327414 52.19866587772922 100.0000000020094 26.179938780289824 100.0 0.0
CURVETO 99.99999999799059 -26.179938778899142 89.22269035685055 -52.198665872977216 70.71067811473525 -70.7106781140784
CURVETO 52.198665872619955 -89.2226903551796 26.179938778899135 -99.99999999523367 0.0 -100.0
CURVETO -26.179938782197837 -100.00000000476633 -52.1986658838917 -89.22269037041644 -70.71067812887988 -70.71067812752307
CURVETO -89.22269037386806 -52.19866588462969 -100.00000001046111 -26.179938782197837 -100.0 0.0
<CDLL 'libspiro.so', handle 1e2a830 at 0x7fdc9a758eb8>
```

**Comment by anthrotype** [comment]
Oh I see, sorry. I'm sure Adrien will fix it in a minute.
Btw, good job about the libspiro port! 👍

**Comment by khaledhosny** [comment]
I can’t reproduce the second issue, need steps to reproduce.

**Comment by ctrlcctrlv** [comment]
Use the selection tool, open a glyph and click anywhere.

**Comment by adrientetar** [comment]
> Please guys, run your code at least once before pushing to master.

Sorry about that, I refactored the code before committing and left blanks.

b2a74eee6b92cca4d04b2b4c92a99b3b4ad04e0d
