### ISSUE TITLE
In README, port to venv instead of virtualenv

### ISSUE THREAD

**Issue by behdad** [trufont/trufont#294]
I ended up having to upgrade to python3.5 so I can pip install pyqt5.  The Ubuntu ppa I'm using for python3.5  does not provide virtualenv, but I found that I don't need it since the system-module venv does the same.

**Comment by teddywing** [comment]
This issue appears to be resolved by https://github.com/trufont/trufont/pull/347/commits/4529cdad1a3650bbb118ba8729f26417ad4963c5
