### ISSUE TITLE
Adding point to an existing contour

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#296]
Nothing I tried seems to allow the pen tool to add a point to an existing contour (clicking on it, clicking with alt pressed, ctl, shift, cmd). So am I doing something wrong or this is an unimplemented feature?

**Comment by adrientetar** [comment]
Knife tool does this.

**Comment by khaledhosny** [comment]
I just discovered this a moment ago (was, desperately, trying to use the knife to split the contour and join it again). I think this counter intuitive, but the only vector drawing tools I ever seriously used FontForge and Inkscape so people might have different expectations.

**Comment by adrientetar** [comment]
Yeah Ill probably revisit this.

**Comment by davelab6** [comment]
Agree with khaled

**Comment by adrientetar** [comment]
Would you advocate removing the Knife tool entirely?

**Comment by davelab6** [comment]
No, its a standard tool :)

**Comment by khaledhosny** [comment]
I think knife tool should just split the curve.

**Comment by moyogo** [comment]
In Glyphs, Robofont and FontLab Studio, the knife tool adds a point without opening the contour. The FontForge behaviour, opening the contour, makes more sense to me but may be unusual to many type designers if they expect the same behaviour as most popular font editors.
Vector graphics applications usually have the knife tool slicing a contour (along a line, a freehand curve or a bezier curve) into multiple contours, some with the option to keep them open.

**Comment by moyogo** [comment]
Actually FontLab’s knife tool can do the following with or without modifiers
- when dragging a line:
  - add points (through one segment: no modifier, through segments: Alt)
  - split contours into closed contours (through segments: no modifier)
  - open contour (Alt+Ctrl or Alt+Cmd)
- when clicking:
  - remove clicked segment
  - open contour at clicked point

Glyphs does the following:
- add points (through one segment: no modifier, through segments: Alt)
- split contours into closed contours (through segments: no modifier)

Robofont seems to only allow adding points.

So maybe it would be good to have the knife tool do the following:
- add points
- split into open contours
- split into closed contours

**Comment by davelab6** [comment]
On 14 July 2016 at 04:51, Denis Moyogo Jacquerye <notifications@github.com>
wrote:

> So maybe it would be good to have the knife tool do the following:
>
>    - add points
>    - split into open contours
>    - split into closed contours
>
>
Agree! Thanks for checking Denis! :)

**Comment by pathumego** [comment]
Agree with Denis on Knife.  But following on @khaledhosny, I think the Pen tool should be able to add points. It dose make sense when drawing. GlyphsApp show a small `+` next to Pen when the pointer is on a curve and you can just add a point. I couldn't do that with Robofont.
