### ISSUE TITLE
Collapsing svg start and end points

### ISSUE THREAD

**Issue by ivanlouette** [trufont/trufont#308]
Hi, I am FontForge user and I love cutting and pasting between Inkscape and FF. But I have a long lasting problem : that adds a zero length segment between end and start points of closed shapes (probably because it's part of the SVG specification). FF doesn't even see it, but when I save PDF files generated by LibreOffice with my fonts that moves one of these two points away and give ugly results.
I have seen today that TruFont shows correctly these two overlaid points and preserves the zero length segment. Is there a quick way to collapse this segment and make only one point with the start and end ones ?

**Comment by adrientetar** [comment]
```
font = CurrentFont()

for glyph in font:
    for contour in glyph:
        first, last = contour[0], contour[-1]
        if first.x == last.x and first.y == last.y:
            contour.removePoint(last)
```

**Comment by ivanlouette** [comment]
Thanks a lots ! I imported the otf font, then opened Python/Scripting window, pasted these lines and re-exported the otf. And it seems that it works !
Is that what I was intended to do (I never worked with scripts…)

**Comment by ivanlouette** [comment]
It works fine ! The issue with LibreOffice generated PDFs is solved !
That will be my first unavoidable use of TruFont after creating my fonts with Inkscape and FF. And be sure I will follow the evolution of your program !

**Comment by davelab6** [comment]
What do you use off for?

**Comment by ivanlouette** [comment]
Sorry for my bad english ; what do you mean by "use off"?

**Comment by davelab6** [comment]
Sorry I meant "use fontforge" :)

**Comment by ivanlouette** [comment]
Ah yes I understand now :) Thanks ! I use FontForge for encoding the fonts I draw, and manage kerning, substitutions (mainly ligatures at the moment) and hinting. And I use also its drawing tools to do things that Inkscape is unable to do. FontForge drawing tools are nice and performing, but I was never able to adapt my needs for drawing freedom to the "only one use" windows of type drawing programs. In the past I used Type Designer, Fontographer 4 and Fontlab 4 and now I use FF for about three years. But always I felt some kind of claustrophoby while using their UI. I come from vector drawing applications with illustration ability (at first time Illustrator and Corel Draw, then for a long time Xara and for a longer time now Inkscape). I wasn't even successful at using Inkscape facilities for drawing svg fonts because they are buggy and would deserve more attention. An Inkscape page is like a (not too cleanly organised) desktop for me : it can contain a line of glyph shapes drawn at their real size (which correspond to a 750 pts line of text at 96 dpi), several versions of some glyphs freely dispersed on screen, several bitmap scans of whole pages of printed text if I work on a revival, text blocks at different sizes of the current font I am drawing and anything I need or I like to see while I am drawing. I know that this is not what every type designer needs or even wish. And I know also that Inkscape doesn't contain the precision drawing utilities of FF and type design programs, but my method works if I don't need to draw things as rigid as TrueType fonts. I know that perhaps my technique isn't very professional (and I respect professionals very much) but it's mine and it gives me joy at drawing fonts. However I think a better integration between vector drawing programs and type design ones could draw a very nice future ! Imagine for example that you are encoding and managing a font in a program like FF or TruFont and your text block refresh automatically (or on demand) at the same time in an Inkscape window without having to pass by re-installing the font and reloading the document… ;-)

**Comment by ivanlouette** [comment]
Sorry ! I didn't want to close…

**Comment by davelab6** [comment]
Nice :) Your description of drawing on the text block is one of the ideas
yet to be implemented in metapolator :)

**Comment by ivanlouette** [comment]
Thanks. Glad to see you work on TruFont ! I will probably migrate to it progressively. Its UI is clean and pleasant to use.
