### ISSUE TITLE
Button icons are not rendered

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#31]
The SVG icons are not rendered at all. I tried replacing one of them with a corresponding PNG and it worked. There is some problem with SVG support in the Qt widget used for these buttons...

This was tested on GNU+Linux with code fetched from current git master (commit ec2cda36e2e12301dbd96afcf21e30298f95c83e).

**Comment by adrientetar** [comment]
Looking at [the docs here](http://doc.qt.io/qt-5/qimagereader.html#supportedImageFormats), you need the Qt SVG module in order to use SVG icons. 
Is this module installed on your machine?

**Comment by davelab6** [comment]
I have a clean GNU system, I will test

**Comment by adrientetar** [comment]
ping @davelab6

**Comment by felipesanches** [comment]
I got it working by installing this:
```
sudo apt-get install python3-pyqt5.qtsvg
```

@davelab6  told me that he will add this info to the dependencies session in the toplevel README.md file of this repo
