### ISSUE TITLE
Make sure all defcon objects are put into the clipboard

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#313]
I think it should.

**Comment by davelab6** [comment]
Is this a duplicate of the issue about select all not selecting anchors?

**Comment by khaledhosny** [comment]
No, even when they are selected they are not copied, only outlines and contours are copied. If I copy the whole glyph in the font window they get copied, but I want to be able to copy just the selected anchors w/ the outlines.

**Comment by pathumego** [comment]
I think it should be `Copy everything selected`. When we have more stuff like guidlines, should be copy-enabled.

**Comment by adrientetar** [comment]
You can now copy anchors, but there are more objects like guidelines that should be copy-enabled.

**Comment by adrientetar** [comment]
> You can now copy anchors, but there are more objects like guidelines that should be copy-enabled.

good in wx
