### ISSUE TITLE
Trufont crash-hangs when deleting a layer from a .ufo from the cmdline.

### ISSUE THREAD

**Issue by madig** [trufont/trufont#315]
I got a .sfd-stored font that I wanted to load into Trufont. I used Khaled's sfd2ufo tool to convert it, but the tool also converts the back layer that I primarily use as a scratch buffer. Trufont has no build-in layer management yet as far as I can see, so I just rm'ed `c-r.ufo/glyphs.B_ack/`. Loading the .ufo now prompts a

```
Traceback (most recent call last):
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.4.0-py3.5.egg/trufont/objects/application.py", line 139, in openFile
    font = TFont(path)
  File "/home/nikolaus/.local/lib/python3.5/site-packages/trufont-0.4.0-py3.5.egg/trufont/objects/defcon.py", line 31, in __init__
    super().__init__(*args, **kwargs)
  File "/home/nikolaus/Entwicklung/trufont/src/defcon/Lib/defcon/objects/font.py", line 146, in __init__
    layerNames = reader.getLayerNames()
  File "/home/nikolaus/Entwicklung/trufont/src/ufolib/Lib/ufoLib/__init__.py", line 422, in getLayerNames
    layerContents = self._readLayerContents()
  File "/home/nikolaus/Entwicklung/trufont/src/ufolib/Lib/ufoLib/__init__.py", line 415, in _readLayerContents
    raise UFOLibError(error)
ufoLib.UFOLibError: A glyphset does not exist at glyphs.B_ack.
```

And lets it hang there.

**Comment by anthrotype** [comment]
You probably removed the glyphs.B_ack folder but forgot to also update the layercontents.plist.

AFAIK TruFont does have some support for UFO3 layers. There is a drop down menu in the Glyph window where you can select the active layer, for example.

**Comment by madig** [comment]
That's what I did, but Trufont shouldn't hang just because I'm being cluelessly heavy handed ;)

**Comment by anthrotype** [comment]
But you already know that. I see know you want to remove a layer from within the application itself. O guess that's not possible yet.

**Comment by adrientetar** [comment]
ufoLib does not accept malformed fonts.

**Comment by khaledhosny** [comment]
We could load the font inside a try statement and give a nicer error message than just hanging.

**Comment by davelab6** [comment]
> ufoLib does not accept malformed fonts.

Fine - but TruFont must not hang or crash :)

**Comment by khaledhosny** [comment]
We sorta show a nice error message (though a bit cryptic), but the application just hangs there (which happens with other errors as well) instead of quitting, and even a ctl+c won’t kill it.

**Comment by adrientetar** [comment]
6d597fdb8001312c2a7996c4d03a20e174efb99b
