### ISSUE TITLE
Importing Clear Sans (TrueType): path of 'C' seems to be broken but displays correctly?

### ISSUE THREAD

**Issue by madig** [trufont/trufont#316]
1. Download https://01.org/clear-sans/downloads/2013/clear-sans-1.00
2. Import regular weight in Trufont
3. Look at 'C'
![bildschirmfoto vom 2016-07-31 10-34-25](https://cloud.githubusercontent.com/assets/380829/17275482/664d0e5e-570a-11e6-9211-3455f0ba661f.png)
4. Press space bar to see it rendered correctly
5. ???

**Comment by adrientetar** [comment]
c3a02e01d5075b7f823251ff58a1dd62c78d4acd
