### ISSUE TITLE
Crash #5 (new version)

### ISSUE THREAD

**Issue by insanetesterftw** [trufont/trufont#319]
Windows 7 (64)
TruFont (repository version, downloaded in the 27th)

> Traceback (most recent call last):
>   File "g:\applications\trufont\lib\trufont\windows\glyphWindow.py", line 734, in mouseMoveEvent
>     self._redirectEvent(event, self._currentTool.mouseMoveEvent, True)
>   File "g:\applications\trufont\lib\trufont\windows\glyphWindow.py", line 794, in _redirectEvent
>     callback(event)
>   File "g:\applications\trufont\lib\trufont\drawingTools\knifeTool.py", line 42, in mouseMoveEvent
>     line.setP2(pos)
> AttributeError: 'NoneType' object has no attribute 'setP2'

PS: The error window really needs to be bigger and resizable is these crashes continue to happen :)

**Comment by adrientetar** [comment]
Can you give steps to reproduce this? It seems a mouse move event happened without a mouse press event before and that's why it errors.
