### ISSUE TITLE
”Quit” should really quit

### ISSUE THREAD

**Issue by brawer** [trufont/trufont#322]
Open two separate UFO files in TruFont, then choose “Quit”.

* Expected: TruFont should quit.
* Observed: TruFont only closes the frontmost window.

(TruFont 0.4.0 on MacOS 10.11.6)

**Comment by khaledhosny** [comment]
+1. I think there should be two different action, “Close” which closes the current font, and “Quit” which quits the application.

**Comment by adrientetar** [comment]
(This is fixed locally.)

**Comment by adrientetar** [comment]
383b41f3e10da5cf620e6e164cbedec472404ad2
