### ISSUE TITLE
Global menu tasks

### ISSUE THREAD

**Issue by adrientetar** [trufont/trufont#323]
Tracking issues after 383b41f3e10da5cf620e6e164cbedec472404ad2.
- [x] retrofit to Windows
- [ ] (fontCellView) add mark colors in context menu
- [x] merge open and import on OSX
  - open binary fonts
  - open + validate .tfExt (check min. version etc. open on Windows?)
- [ ] (glyphWindow) figure out what to do of Deselect, Glyph menu
- [x] enable global menu on relevant GNU targets
- [ ] simplify the whole mechanism, add shortcuts. see https://github.com/qtproject/qt-creator/blob/7f49457e9d6e190656c3f620e51b489c0d0fd900/src/plugins/coreplugin/actionmanager/actionmanager.cpp

Also:
- [ ] consider folding save/save all in QApp or TFont
- [x] (cleanup) maybe filter focusChanged into windowChanged

**Comment by khaledhosny** [comment]
I get no menus at all on GNOME 3.

**Comment by adrientetar** [comment]
Yeah, I know. Does it work now?

**Comment by khaledhosny** [comment]
Yes.
