### ISSUE TITLE
[Glyph window] Find dialog bug

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#330]
In Find dialog even if I select `Contains`, it filters glyphs that `Begins with` the input.

<img width="962" alt="screen shot 2016-08-10 at 11 30 58 pm" src="https://cloud.githubusercontent.com/assets/6846609/17573487/8a30af42-5f52-11e6-8de0-b1a968c63ea1.png">

**Comment by adrientetar** [comment]
c81063f365a7ef9e56ad2545171e093047356171
