### ISSUE TITLE
Map more glyph names to Unicode points?

### ISSUE THREAD

**Issue by madig** [trufont/trufont#331]
Not sure if this is done by Trufont or a component, but I tried pasting https://github.com/google/fonts/blob/master/tools/encodings/GF%202016%20Glyph%20Sets/filter%20lists/GF%20Latin%20Plus.txt into the "Add Glyphs..." dialog. It took quite some time and then added various empty glyph points when they actually existed before in the font under their Unicode point names (e.g. "uhookabove" vs. "uni1EE7"). I guess the human-readable names are a Glyphs thing?

**Comment by pathumego** [comment]
@madig see https://github.com/trufont/trufont/issues/122#issuecomment-154738483

**Comment by pathumego** [comment]
but I think support for `.nam` would be better.

**Comment by pathumego** [comment]
Closing in favor of  #528
