### ISSUE TITLE
Can’t open any menus

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#333]
On Gnome 3 the menus close immediately whenever I open them (it is closed so quickly most of time that it appears like nothing is happening).

**Comment by adrientetar** [comment]
Can you bisect? I'll try but I have Cinnamon in the office and I need to install all the deps.

**Comment by khaledhosny** [comment]
Bisected to 65a6a0a4316216d4774e9dae8864cd6978f9546d.

**Comment by adrientetar** [comment]
Interesting, so if you use the current code but changing to focusChanged it works?

**Comment by khaledhosny** [comment]
Yes, after reverting that commit menus are back to normal.

**Comment by adrientetar** [comment]
Ok I can repro.

**Comment by adrientetar** [comment]
0d6862ff29effc2e70df22223ef40c17a37c8f24

**Comment by adrientetar** [comment]
There's also a segfault on exit, ha. time to look at that too.

**Comment by madig** [comment]
@khaledhosny: Can you describe your issue again? The workaround for this bug leads to crashes: #423. I can't quite reproduce what you wrote...

**Comment by khaledhosny** [comment]
I think the issue summary is as clear as it gets, not sure what else needs explanation. That being said, I can’t reproduce the issue anymore after reverting 0d6862ff29effc2e70df22223ef40c17a37c8f24.

**Comment by madig** [comment]
Note to self: Should this issue come up again, try saving the window hash instead of a reference.
