### ISSUE TITLE
Put simple install instructions in README

### ISSUE THREAD

**Issue by adrientetar** [trufont/trufont#337]
The "simple way" should be something like:

```
pip3 install PyQt5
git clone https://github.com/trufont/trufont
cd trufont
pip3 install -r requirements.txt
python3 setup.py install
trufont
```

venv only needs be used in certain cases.

**Comment by anthrotype** [comment]
`pip install trufont` FTW

**Comment by adrientetar** [comment]
> pip install trufont FTW

Feel free to help with that ;)

**Comment by anthrotype** [comment]
Looking at the list of Trufont's requirements, only defconQt and extractor are not yet on PyPI.
I'll do that in the following days.

**Comment by anthrotype** [comment]
Arrgghh.. of course, "extractor" name is already taken on PyPI :(
https://pypi.python.org/pypi/Extractor/0.5

how shall I name the package? "ufo-extractor" maybe?

I wonder if it could be a good idea to merge extractor into ufo2ft... 
They are kind of complementary, one goes from fonttools objects to ufo, the other from ufo to fonttools objects.

**Comment by anthrotype** [comment]
or even better, ufoLib itself...

**Comment by adrientetar** [comment]
> how shall I name the package? "ufo-extractor" maybe?

Sounds good, yea. Thanks!

**Comment by davelab6** [comment]
> I wonder if it could be a good idea to merge extractor into ufo2ft... or even better, ufoLib itself...

I like this idea, of having both ufo2ft and ft2ufo classes in ufoLib :)

**Comment by anthrotype** [comment]
Let's think about that a bit more...

In the meantime, [defconQt](https://pypi.python.org/pypi/defconQt) and [extractor](https://pypi.python.org/pypi/ufo-extractor) are out.

I had to name extractor "ufo-extractor" to avoid the name clash.
So one would `pip install ufo-extractor`, but still `import extractor`.
Not ideal, but something to start with.

Now, on to TruFont itself.

**Comment by anthrotype** [comment]
I pushed c8fd8dccc9176985e5c624e81fd117cff563f3d8

Next time you push a tag, it should trigger the `deploy` stage on Travis CI, which will publish the distribution packages to the Python index.

It also creates a Github Release from the pushed tag, if it doesn't already exist. No files are uploaded automatically to Github, at least for now.

Maybe we can make it so it runs pyqtdeploy to create the Mac and Linux app bundles (and same for Windows on Appveyor), but I don't know how to use pyqtdeploy.

**Comment by adrientetar** [comment]
> Maybe we can make it so it runs pyqtdeploy to create the Mac and Linux app bundles (and same for Windows on Appveyor), but I don't know how to use pyqtdeploy.

Thanks. I have plans to make a trufont-pkg repository with a script that generates pyqtdeploy package on a blank computer and all needed assets.

**Comment by anthrotype** [comment]
Sgtm.
I just noticed I had forgotten to add the the README.rst as `long_description`. Done just now da518375a376809abff9bf99ad5b356ce72d87e9

**Comment by adrientetar** [comment]
Done in the wx branch.
