### ISSUE TITLE
Is operating philosophy behind trufont same as RoboFont?

### ISSUE THREAD

**Issue by GitBruno** [trufont/trufont#344]
http://doc.robofont.com/documentation/welcome-to-robofont/robofont-design-principles/

I hope so! ;)

Use wiki for documentation?

**Comment by adrientetar** [comment]
Well the primary idea is not to put "magic" in the editor (some things like glyph names, metrics, some additional tools depend on workflow and project) but we may have a "batteries included" approach for the default distribution in the future (similar to GitHub Atom for instance). And you can make extensions that help the project you are working on (I think like the [Obsidian talk](https://vimeo.com/124062807) puts out).

> Use wiki for documentation?

I'm thinking the website with Markdown but it can be migrated from wiki when I actually work on it.
