### ISSUE TITLE
Copying glyph should not copy its Unicode values

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#346]
When copying a glyph, we copy its Unicode value (overriding that if the destination glyph), but this means we end up with duplicate code points which results in hard to debug bugs.

We should either avoid copying the Unicode values at all, or copy it only if:
* Destination has no Unicode value, and
* There is no other glyph in the font with the same Unicode value.

**Comment by adrientetar** [comment]
4d061065390f14cbd4de8c9ea9da6eee20cccdaa
