### ISSUE TITLE
Need a way to edit anchor coordinates

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#351]
Currently clicking on an anchor allows one to rename it, but there is no way to edit the X and Y positions (apart from moving the anchor itself).

**Comment by GitBruno** [comment]
Agree, I think an updated inspector palette would be great. I think the transform tool is meant to work with selection?

**Comment by adrientetar** [comment]
Yes. I have started working on these things but I've been busy with other matters, hoping to get back on it within a month or two. Thank you for your feedback!
