### ISSUE TITLE
Add selection transformation dialogue box

### ISSUE THREAD

**Issue by tisimst** [trufont/trufont#365]
It would be very helpful to have a dialogue box that allows you to apply a simple mathematical transformation to whatever is selected, be it a point, curve, or an entire glyph (or multiples of them):
- Translate (e.g. move)
- Scale (uniformly or x/y independent; flip up/down, left/right shortcuts would be nice)
- Rotate (clockwise or counter-clockwise)
- Skew (clockwise or counter-clockwise in x or y direction)
- etc.

Ideally, there would be input/check boxes that allow you to decide:
1. Where the "origin" of the transformation to be (e.g., the true glyph origin, the selection center, or some other manually input location).
2. Whether to round the results to integers or not
3. Whether to apply the transformation to all layers
4. Whether the transformation affects the advance width

**Comment by adrientetar** [comment]
The sidebar (Ctrl+Alt+P) operations should work on the selection, that's just not implemented right now (it always targets the whole glyph). Internally it calls the glyph methods, e.g. glyph.skew(..) which works on the whole glyph. Looking at other editors I don't see their scripting APIs targetting selection so presumably the code would need to be duplicated?

That's what I was thinking of the last time I worked on these things.

**Comment by adrientetar** [comment]
HAven't thought about your 3. and 4. thus far.

**Comment by tisimst** [comment]
Thanks @adrientetar! Also, the ability to preview the operation (showing both before & after) would be nice. I'll pull the latest commits and see what I think so far.

**Comment by tisimst** [comment]
I'm thinking the actual transformation operations should be pushed all the way down to the point level rather than at the contours? That way the contours or glyphs can simply propagate the transformation down to them. Or does this lose their reference as part of the contour?

**Comment by adrientetar** [comment]
> I'm thinking the actual transformation operations should be pushed all the way down to the point level rather than at the contours? That way the contours or glyphs can simply propagate the transformation down to them. Or does this lose their reference as part of the contour?

You always need the contour when doing operations because points do not send notifications, so you need to do contour.dirty = True after changing points.

**Comment by tisimst** [comment]
> You always need the contour when doing operations because points do not send notifications, so you need to do contour.dirty = True after changing points.

Suspicion confirmed. Never mind, then.

**Comment by pathumego** [comment]
This is fixed now, right?
