### ISSUE TITLE
Tabbed ui tasks

### ISSUE THREAD

**Issue by adrientetar** [trufont/trufont#367]
- [ ] (bug) opening a tab then switching back to the font view scrolls the view
- [ ] subscribe to Glyph.NameChanged, LayerSet Changed etc.
- [ ] what happens when a glyph is deleted with a tab open?
- [x] handle setCurrentTool returning False (the glyphView NAKs a tool change during mouseDown, but the toolbar doesn't echo that)

- [ ] "glyphWindowWillOpen", "glyphWindowOpened", "glyphWindowWillClose"
  tab API replacements?

**Comment by tisimst** [comment]
@adrientetar, I pulled the latest master this morning excited to see this, but I don't see any of the new tab functionality in the UI. What am I missing?

**Comment by pathumego** [comment]
I had to clear pyc files from earlier

**Comment by madig** [comment]
- [ ] Add scroll bars to the glyph view.

**Comment by adrientetar** [comment]
> Add scroll bars to the glyph view.

There are no scroll bars anymore, the size of canvas is infinite. You can click mouse wheel and drag to scroll or space/click/drag or zoom out and back in.

**Comment by madig** [comment]
Ah! Good to know, although hard to discover.
