### ISSUE TITLE
Menus should be the same regardless of context

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#37]
@dcrossland says that he wishes the whole application had the same set of menu-options regardless of which window is currently active.

**Comment by adrientetar** [comment]
That is how robofont works and I imagine that it's how it is on the Mac. Any better reason to do this?

**Comment by adrientetar** [comment]
As it stands the "should" in the title sounds a bit dogmatic.

**Comment by davelab6** [comment]
(Should is appropriate rather than must because there may be valid
exceptions.)

I propose this because muscle memory and mental model psychology is very
strong in learning a new application.

Hot keys similarly are inconsistent atm

**Comment by davelab6** [comment]
I suggest menus that dont make sense in some window are greyed out

**Comment by pathumego** [comment]
I think this should be worked out along with #24.

**Comment by davelab6** [comment]
@pathumego agree
