### ISSUE TITLE
Ability to change behavior of contour points in glyph editor

### ISSUE THREAD

**Issue by tisimst** [trufont/trufont#371]
While editing glyph contours, it is helpful (vital?) to be able to change how the _behavior_ of points is manipulated. The glyph editor already recognizes when corner, tangent, and smooth on-curve points were intended, but there isn't currently a way to change them from one type to another except when they are created/imported.

**Comment by adrientetar** [comment]
You can double-click a point to change its type, or type enter with a selection (but it seems to change every point type at the moment, that's a bug). Tangent and smooth are the same thing, smooth just means that the connection should be continuous.

**Comment by tisimst** [comment]
Ok. I'll have to take a look at that. Either way, having a button/shortcut for doing this would be helpful, too, since it isn't obvious (at least to me) that double-clicking on a point would change its behavior.

**Comment by tisimst** [comment]
Oh, and just to be clear, I was aware that tangent and smooth were the same thing, just a variation on the theme of smooth points to define how associated points can be manipulated.
