### ISSUE TITLE
Additional point types in glyph editor

### ISSUE THREAD

**Issue by tisimst** [trufont/trufont#372]
In addition to being able to change between the standard kinds of on-curve point types (i.e., corner, tangent, and smooth, see #371), I think the glyph editor could really benefit from some other helpful types of points:

- [ ] **Vertical/Horizontal** - Forces the off-curve points to either have the same x or y value as the on-curve point, but can be easily switched between the two directions.
- [ ] **Smooth-Symmetric (C2)** - Forces the off-curve points on either side of the on-curve point to be equidistant from it.
- [ ] **Smooth-Curvature (G2)** - Forces the curvature of the joining curves to be equal at the on-curve point. _(I've worked out the math already for this one, if interested)_

All of those types fall under the UFO "smooth" point type and can be determined hierarchically just like the others when it loads the contours into the glyph editor.

**Comment by adrientetar** [comment]
Wont be doing this.
