### ISSUE TITLE
Support for user-defined parameters & constraints

### ISSUE THREAD

**Issue by tisimst** [trufont/trufont#373]
As an engineer and designer, I've learned the power of being able to use constraints to drive design because it can simplify many things. I'm wondering if such a philosophy/capability would be useful in type design as well? 

The UFO standard already allows the storage of arbitrary data in `lib.plist`, the `lib` element in the individual GLIF file, or if necessary in the font's `data` directory. Points would likely need to make use of the `name` or `identifier` property so that each is uniquely identifiable.

This really opens a whole world of options (even to the extent of allowing the user to define their own custom constraint equations to drive design decisions). Here are some basic constraints that would be really useful, in my opinion:

- [ ] **Offset/Distance:** a point must be a specific distance from another
- [ ] **Horizontal/Vertical:** a point must have the same x or y coordinate as another
- [ ] **Parallel:** a straight line or curve's "leg" points in the same direction as another or a guide line
- [ ] **Perpendicular:** a straight line or curve's "leg" points 90deg to another or a guide line
- [ ] **Fixed angle:** a straight line or curve's "leg" is at some angle to another or a guide line
- [ ] **Fixed Location:** a point's position is not affected by other constraints
- [ ] **Equal Length:** a straight line or curve's "leg" is the same length as another
- [ ] **Symmetric:** the location of a point is symmetric to another across a straight line, curve "leg" or guide line

Those are just some thoughts based on my own experience designing things parametrically in many different CAD systems. I realize this is no small task and is definitely not a top priority. Just thinking they would be helpful.

**Comment by jenskutilek** [comment]
I have written my thoughts about adding a constraints system directly to the UFO specification here: https://github.com/unified-font-object/ufo-spec/issues/43

I have only looked at constraints that could be used to generate hinting programs, and I think your constraint type suggestions would also be good to have in the UFO standard.

**Comment by adrientetar** [comment]
It could be interesting for someone to work on a constraints system, and I have plans in the future to add hints to tfont which could be used to define relationships between points. Jens, what you posted is useful, thanks for the link. For now I'm gonna tag this as future and close the issue as no work will be made on this in the coming future.
