### ISSUE TITLE
Make the starting point/direction more visible.

### ISSUE THREAD

**Issue by tisimst** [trufont/trufont#375]
When glyph interpolation becomes a possibility, matching starting points will be critical and being able to see them easily will be helpful.

**Comment by adrientetar** [comment]
What would you want to see?

**Comment by pathumego** [comment]
👍  
- Starting point
- Point direction
- Contour order

**Comment by pathumego** [comment]
This was discussed here #47

**Comment by davelab6** [comment]
It is a possibility today with mutatormath :) while that kind of
"prepolation" feature seems more like an extension than a core feature to
me, I agree that start point and winding direction and showing contour
order should be ootb

**Comment by tisimst** [comment]
Since the only distinguishing point shapes currently being used (I think) are squares and circles, I think it would make sense to change the current starting shape from a half-circle to something more like an arrow (a triangle like Glyphs?) or add a floating arrow next to the point (like FontForge, my personal preference). 

If there is any intention of adding other point shapes in order to support my suggestions for other end point conditions (like Vertical/Horizontal, C2, and G2, as described in #372 ), then maybe using a triangle as the starting point & winding direction indicator isn't the best idea.

**Comment by adrientetar** [comment]
Start points are arrow shaped already.

> adding other point shapes

I don't think we'll bring more point types into the core editor for the time being.

**Comment by tisimst** [comment]
Ok. Did it change recently? I may need to update my local master, but all I see is a light grey half circle.

**Comment by adrientetar** [comment]
> light grey half circle.

I think you need to update defconQt.

**Comment by tisimst** [comment]
Ah! I'll do that. Thanks!

**Comment by anthrotype** [comment]
In general I'd recommend to always `pip install -r requirements.txt` after pulling the latest changes from upstream.
