### ISSUE TITLE
Select active layer in the layers panel

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#377]
I’m not sure how one switches to different layer in the new UI, clicking the layer name on the side panel does nothing.

**Comment by adrientetar** [comment]
Ctrl+Shift+Up/Down for now, I need to add a visual command still.

**Comment by adrientetar** [comment]
You can also do View>Layer Up/Down.

**Comment by khaledhosny** [comment]
I discovered that right after I posted this. I previously assumed they move layers up and down like e.g. in GIMP which makes no sense of course :) but I guess the wording can be improved, may be “switch to previous/next layer” or something like that.

**Comment by adrientetar** [comment]
Well, layers form a stack so I thought previous and next don't make a lot of sense in that context.

**Comment by khaledhosny** [comment]
In thought Layer Up/Down would be changing the order of the layers in the font, so the problem in not in up/down themselves. May be “Switch to layer above/below”?

**Comment by adrientetar** [comment]
No, entries of the "View" menu do not mutate the font, they just change how you look at it. The sidebar has arrow icons to change layer order (or you can drag and drop). The sidebar also always displays the layers per the layer order.

**Comment by adrientetar** [comment]
d1823ac22571f21354b5413fcc225dca1b3e3b6f
