### ISSUE TITLE
context view tasks

### ISSUE THREAD

**Issue by adrientetar** [trufont/trufont#378]
- [x] draw all backgrounds (drawGlyphBackground, drawBackground), then all foregrounds
- [ ] replace drawingToolRegistered/Unregistered with addDrawingTool/setDrawingTools (+insert?) and drawingToolsChanged notification
- [ ] add clipboard support and selection in text tool
- [ ] originForIndex(..) is not very useful considering drawing is done in canvas coordinates, remove it?
- [ ] rename glyphView* notifications to canvas*?
- [x] make sure text tool works with non-default layers
- [ ] maybe not hide stack widget widget, just disable the tool before setParent
- [ ] add centerOn/ensureVisible to context view, and
- [ ] scroll caret into view
- [x] Ctrl+Shift and move seems impaired
- [x] Have unencoded glyphs as '/foo ' in the tab title, and
- [ ] maintain an input string in text tool and have text tool fire the names changed signal with its string
- [x] Use advanceWidth/Height in glyphRecord to store default layer widget and not have to hunt for it everytime it's needed (LayoutEngine does that already)
- [x] Switch to paintBackground in the text tool
- [x] ~~Change drawFillAndPoints/drawStroke to drawFill/drawPointsAndStroke~~ and enable partial aliasing only if drawGlyphOnCurvePoints
- [ ] add spacing/kerning visuals and commands and remove metrics window
- [x] mapFrom/ToCanvas/originForIndex also need to factor in the xP of the last glyph index

**Comment by davelab6** [comment]
Small question: Will it be possible to make an extension that recreates the
"classical" multi window ui?
