### ISSUE TITLE
feature to add your own custom space center strings

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#38]

**Comment by adrientetar** [comment]
Edit > Settings... in the Space Center tab you can input your own strings.

**Comment by davelab6** [comment]
What if you could enter a url, including a file:// url?

What if you  can drag and drop a file?

And then each line is available in the drop-down

**Comment by pathumego** [comment]
@adrientetar on e509dfb  on Mac on preferences adding custom string dose not work. Nothing happens when I click on the `+` mark or `-`. But I can edit the default strings.

**Comment by adrientetar** [comment]
@pathumego That's not just on the Mac actually, fixed in 9551e20b7c92c79906815a66b99757c322db518b

**Comment by pathumego** [comment]
@adrientetar It works now!

**Comment by davelab6** [comment]
So, when spacing text in the window titled `Space center`, there are pre-loaded strings in the drop down:

![report issue to loading text file with premade strings](https://cloud.githubusercontent.com/assets/261579/10988647/d9dd41f8-8470-11e5-8a5e-7c4287dc5070.png)

If you go to Preferences, the window titled `Settings` opens, with a tab titled `Metrics Window` and a list:

<img width="598" alt="screen shot 2015-11-06 at 13 07 16" src="https://cloud.githubusercontent.com/assets/261579/10990588/65b52c8e-8487-11e5-975f-7d5fceca11cf.png">

Each of those lines is available in the drop-down. I'd like to be able to load a text file with strings into this list from the local filesystem or a URL. @adrientetar will you accept a patch for this?

There are a few other minor string tweaks suggested in the above screenshots:

- [ ] rename `Space center` to `Space Center`
- [ ] rename `Settings` to `Preferences`
- [ ] rename `Metrics Window` to `Space Center`

**Comment by pathumego** [comment]
@davelab6 Rename `Window > Metrics Window` to `Space Center` too? I think all these should be addressed in solution for #24. A naming system and menu system based on a logical system is needed :)

**Comment by adrientetar** [comment]
Are you runninig the latest version?

**Comment by davelab6** [comment]
I am. 

![screen shot 2015-11-06 at 23 19 15](https://cloud.githubusercontent.com/assets/261579/11002000/d23ce694-84dc-11e5-9d78-693beffa7fd0.png)

**Comment by pathumego** [comment]
Me too running the same

**Comment by adrientetar** [comment]
![c](https://cloud.githubusercontent.com/assets/1250894/11002050/cb96e9c0-84aa-11e5-915e-1f2ec17f1544.PNG)

**Comment by pathumego** [comment]
@adrientetar So it says `Metrics Window` on your screenshot too.

**Comment by adrientetar** [comment]
It was not the case in the screenshot posted before.

**Comment by pathumego** [comment]
@adrientetar Ah ok, so no more `Space Center`. Its `Metrics Window` :+1:

**Comment by adrientetar** [comment]
Space center on the way out.
