### ISSUE TITLE
Drag-and-drop SVG files

### ISSUE THREAD

**Issue by brawer** [trufont/trufont#382]
It would be nice if one could drag-and-drop SVG files (like [these](https://github.com/googlei18n/noto-emoji/tree/master/svg)) into TruFont. When dropping an SVG into the glyph editor, it would add the path geometry from the dragged SVG file; when dropping an SVG into the font view, it would add the glyph. See https://github.com/googlei18n/noto-emoji/issues/61#issuecomment-284862828 by @DeeDeeG.

**Comment by DeeDeeG** [comment]
Wow, I can't believe this is suddenly supported! Thanks @santhoshtr and everyone who reviewed/merged.

**Comment by colmoneill** [comment]
Hi, I'm trying to use this feature, I have v0.6.5 running here, but I can't seem to find any way of pasting in svg to TruFont in any way. Is this feature enabled yet? Am I missing something a step in the process? Is this feature only available with development versions of TruFont?
I really hope I can work this out, I'd love to use TruFont.
Thanks and all the best,

**Comment by santhoshtr** [comment]
Works fne for me. Here is a video showing it in action: https://imgur.com/0KNK3dy 
I am at commit:  bb0548cf899146269d3ef00cc1df47e3bf86f587

Do you see any errors while you drag and drop?
