### ISSUE TITLE
Renaming a glyph keeps the old one

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#386]
When renaming a glyph (by changing the name from the sidebar) the old glyph is kept but empty and the new name is inserted at the end of the font with the old outlines.

**Comment by adrientetar** [comment]
> the old glyph is kept but empty

I can't reproduce this.

**Comment by adrientetar** [comment]
> the old glyph is kept but empty

I'm thinking maybe that happens with glyphs that have multiple layers. Looking into it.

**Comment by khaledhosny** [comment]
Yes, the font (Reem Kufi) has multiple layers.

**Comment by adrientetar** [comment]
42f8ca8fb752398ee3d54ef84f04c602b982fb4e
