### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by enathu** [trufont/trufont#388]
Using the latest `Version 0.6.0 build f7f91f6` in Windows

When opening the glyph view by clicking on the glyph slots, trufont throws an error. Please see the screenshot below. And the "Show details" button reveals this,
```
Traceback (most recent call last):
  File "c:\users\tharique\appdata\local\programs\python\python36-32\lib\site-packages\defconQt\controls\glyphView.py", line 593, in paintEvent
    self.drawGlyphLayer(painter, glyph, layerName, default)
TypeError: drawGlyphLayer() takes 4 positional arguments but 5 were given
```
Thank you.
![trufont1](https://cloud.githubusercontent.com/assets/62147/23756191/e4187092-0508-11e7-82ea-127ccc9d390a.PNG)

**Comment by adrientetar** [comment]
This isn't the latest trufont, you need to update defconQt and trufont.
