### ISSUE TITLE
make measure tool behave like the Inkscape's one

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#39]
which is basicaly the same as Glyphs' measure tool as well.

**Comment by davelab6** [comment]
I think since the lasr time we reviewed Glyphs, it added a 'measure mode'
that shows all points coordinates, and turns all guidelines into measuring
lines.

**Comment by felipesanches** [comment]
Please, assign it to me.

**Comment by davelab6** [comment]
@adrientetar please invite felipe to the org

**Comment by adrientetar** [comment]
8c063ed
