### ISSUE TITLE
Output window does not show in the window list under Gnome

### ISSUE THREAD

**Issue by khaledhosny** [trufont/trufont#390]
I’m not sure if this is by design, but output windows does not show in the window list under Gnome, and if the font window is maximized it will open hidden behind it and one will think nothing happened. You have to minimize and move the font window to be able to find it (this used to happen to the properties window as well, but it is gone now).

**Comment by adrientetar** [comment]
It's declared a tool window (Qt.Tool), or a supplementary window. Depending on the platform it means it's getting a smaller title bar, disappears when the app is out of focus.

I'm thinking there should be a check box to force it on top, or remove the Qt.Tool altogether.
