### ISSUE TITLE
Unclear how to install the development/master version of TruFont

### ISSUE THREAD

**Issue by DeeDeeG** [trufont/trufont#404]
Hello,

I would like to test that the "qcurve" support is working, since it would help with a small project I am working on. For that, I need to run the master branch of TruFont.

I can follow the install instructions from README.md, but since they use a standard `pip install`, I believe I am only getting the latest "release" version, not the latest from Github master.

Is there something I am missing?

Thank you.

**Comment by DeeDeeG** [comment]
Also, when trying the developer install instructions, my `pip install --upgrade -r requirements.txt" is unable to find pyqt5, and `pip install pyqt5` doesn't find it either.

`pip3 install --upgrade -r requirements.txt` fetches every requirement, but errors out when trying to install the first one, brotli.

I am on Linux Mint 18.1, which is based on Ubuntu 16.04

**Comment by anthrotype** [comment]
> since they use a standard pip install, I believe I am only getting the latest "release" version, not the latest from Github master

correct, but they should be pretty much up to date, as Adrien and I try to tag quite often. Feel free to ping us if that's not the case.

> pip install pyqt5 doesn't find it either

https://pypi.python.org/pypi/PyQt5/5.8.1

The pre-compiled manylinux1 wheels on PyPI for PyQt5 are 64 bit only, and are compatible with python 3.5, 3.6 and 3.7. Make sure the python version your pip command linked with is one of them. And in order to install the precompiled manylinux1 wheels you need a quite recent version of pip that understand that tag. The current pip is 9.0.1, I think manylinux1 support was introduced with pip 7.

Brotli should be an optional requirement, only required if you export WOFF2. What is the actual error? Note that there are no pre-compiled Linux wheels for brotli at the moment, at least not from the official google/brotli repo (only for mac and windows). There is https://pypi.python.org/pypi/brotlipy/0.6.0 which is another python bindings for Brotli which has precompiled linux wheels and works as a drop-in replacement for the `brotli` module (but has a runtime dependency on `cffi`, was made for pypy mostly).
So, if you want brotli and are on Linux, currently you need a standard C compiler (gcc), which should be easily available from your distro package manager.

**Comment by anthrotype** [comment]
The pyqt5 installation issue is probably a mistake from the pyqt5 maintainers, as they called the wheel "5.8.1.1" but the metadata for that version is "5.8.1", which seems to confuse PyPI and pip.

https://pypi.python.org/pypi/PyQt5/5.8.1

The commit a1240a8 above should fix this. Let me know if you still can't install it.

**Comment by DeeDeeG** [comment]
I'm trying to install now, thank you.

I forgot to mention that a recent commit addressed qcurves, so I know it's not in the python archives yet. Here is the commit that fixed the qcurve issue: https://github.com/trufont/trufont/commit/02ae32dfbdca902edd881adb45cefe0ec06db03f

**Comment by DeeDeeG** [comment]
It didn't work. Of course, it might just be because my machine is mis-configured, so if that's the case I won't bother you more about it. I suppose I should try on an Ubuntu 16.10 LiveCD or something like that.

I have python 3.5 installed at the moment, and also python 2.7. I'm not sure which is linked to pip, but I believe pip3 is specific to python 3. Neither worked when I tried.

**Comment by anthrotype** [comment]
Trufont only works with hpython 3.5 and above, python2.7 is not supported.
Can you please post here the error message you're getting?

Also what do you get when you do:

```
$ pip3 --version
```

If your pip is too old, it will not support pre-compiled manylinux1 wheels.

**Comment by davelab6** [comment]
pip3 install -e .

When you run this command, the source code in the current working directory
is installed

Does that work?

**Comment by DeeDeeG** [comment]
testing on a Ubuntu 17.04 LiveCD.

pip3 is version 9.0.1

pip3 install -e ran and finished without errors, but I can't figure out how to actually launch trufont.

pip3 install --upgrade -r requirements.txt speeds through the install with cached requirements, and finishes without errors. still can't figure out how to launch it, though?

I might try it on a stable release like 16.10 or 16.04 next.

**Comment by adrientetar** [comment]
trufont or python -m trufont.

**Comment by DeeDeeG** [comment]
just did it on Ubuntu 16.10.

Here is what I get:

```
ubuntu@ubuntu:~/trufont$ pip3 install --upgrade -r requirements.txt 
Collecting pyqt5==5.8.1.1 (from -r requirements.txt (line 1))
  Using cached PyQt5-5.8.1.1-5.8.0-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl
Requirement already up-to-date: fonttools==3.9.1 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: ufoLib==2.0.0 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: defcon==0.3.1 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: defconQt==0.5.3 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: ufo-extractor==0.2.0 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: ufo2ft==0.4.1 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: booleanOperations==0.7.0 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: hsluv==0.0.2 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: brotli==0.5.2 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: sip<4.20,>=4.19 in /home/ubuntu/.local/lib/python3.5/site-packages (from pyqt5==5.8.1.1->-r requirements.txt (line 1))
Requirement already up-to-date: compreffor>=0.4.4 in /home/ubuntu/.local/lib/python3.5/site-packages (from ufo2ft==0.4.1->-r requirements.txt (line 7))
Requirement already up-to-date: cu2qu>=1.1.1 in /home/ubuntu/.local/lib/python3.5/site-packages (from ufo2ft==0.4.1->-r requirements.txt (line 7))
Requirement already up-to-date: pyclipper>=1.0.5 in /home/ubuntu/.local/lib/python3.5/site-packages (from booleanOperations==0.7.0->-r requirements.txt (line 8))
Installing collected packages: pyqt5
  Found existing installation: PyQt5 5.8.1
    Uninstalling PyQt5-5.8.1:
      Successfully uninstalled PyQt5-5.8.1
  Rolling back uninstall of PyQt5
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/PyQt5-5.8.1.dist-info'
```

I usually try with sudo when I get permission errors.

when I do that, it installs without errors but can't be launched:

```
ubuntu@ubuntu:~/trufont$ sudo pip3 install --upgrade -r requirements.txt 
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyqt5==5.8.1.1 (from -r requirements.txt (line 1))
  Downloading PyQt5-5.8.1.1-5.8.0-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl (96.1MB)
    100% |████████████████████████████████| 96.1MB 10kB/s 
Requirement already up-to-date: fonttools==3.9.1 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: ufoLib==2.0.0 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: defcon==0.3.1 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: defconQt==0.5.3 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: ufo-extractor==0.2.0 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: ufo2ft==0.4.1 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: booleanOperations==0.7.0 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: hsluv==0.0.2 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: brotli==0.5.2 in /home/ubuntu/.local/lib/python3.5/site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: sip<4.20,>=4.19 in /home/ubuntu/.local/lib/python3.5/site-packages (from pyqt5==5.8.1.1->-r requirements.txt (line 1))
Requirement already up-to-date: compreffor>=0.4.4 in /home/ubuntu/.local/lib/python3.5/site-packages (from ufo2ft==0.4.1->-r requirements.txt (line 7))
Requirement already up-to-date: cu2qu>=1.1.1 in /home/ubuntu/.local/lib/python3.5/site-packages (from ufo2ft==0.4.1->-r requirements.txt (line 7))
Requirement already up-to-date: pyclipper>=1.0.5 in /home/ubuntu/.local/lib/python3.5/site-packages (from booleanOperations==0.7.0->-r requirements.txt (line 8))
Installing collected packages: pyqt5
  Found existing installation: PyQt5 5.8.1
    Uninstalling PyQt5-5.8.1:
      Successfully uninstalled PyQt5-5.8.1
Successfully installed pyqt5-5.8.1
ubuntu@ubuntu:~/trufont$ tru
true      truncate  trust     
ubuntu@ubuntu:~/trufont$ trufont
trufont: command not found
ubuntu@ubuntu:~/trufont$ sudo trufont
sudo: trufont: command not found
```

**Comment by DeeDeeG** [comment]
Okay, `sudo pip3 install -e .` works, from within the cloned `trufont` directory. :thumbsup:

**Comment by anthrotype** [comment]
don't use `sudo` with pip, you risk screwing your distro's python installation; that's the realm of the distro package manager, pip should not touch that. Install trufont inside a virtual environment as explained in the readme.

**Comment by DeeDeeG** [comment]
I guess I'll reboot the LiveCD and see if I can get it to work in a VENV.

**Comment by anthrotype** [comment]
let us know if there's anything missing or not clear from the installation instructions in the readme, or maybe send a PR, thanks!

**Comment by DeeDeeG** [comment]
I can confirm it works in a VENV. Making/activating a VENV, then running `pip3 install -e .` from within the trufont directory works.
