### ISSUE TITLE
Crash Report: Set color to None causes a crash

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#41]
I open a font, go to Edit menu, Mark Color, Red, and then again, Mark Color, None, and get a crash:

```
Traceback (most recent call last):
  File "/Users/dcrossland/src/github.com/trufont/trufont/Lib/defconQt/fontView.py", line 1025, in markColor
    color.getRgbF() if color is not None else None)
  File "/usr/local/lib/python3.5/site-packages/defcon/objects/color.py", line 19, in __new__
    r, g, b, a = value
TypeError: 'NoneType' object is not iterable
Abort trap: 6
```

**Comment by felipesanches** [comment]
The bug seems to be upstream on defcon.

**Comment by graphicore** [comment]
> The bug seems to be upstream on defcon.

So it should get fixed on my fork.

**Comment by davelab6** [comment]
You mean the trufont fork?

**Comment by felipesanches** [comment]
current code is:
```
                color.getRgbF() if color is not None else None)
```

If I do this, it stops crashing and actually makes it become clear color:
```
                color.getRgbF() if color is not None else [0, 0, 0, 0])
```

But we loose the placeholder :-(

**Comment by graphicore** [comment]
> You mean the trufont fork?

No, I meant my the defcon fork. But @adrientetar forked it to here: https://github.com/trufont/defcon/tree/python3-ufo3 Which is a far better place anyways.

**Comment by anthrotype** [comment]
I must say I'm a bit confused about the state of the many robofab's forks and branches (python3, ufo3k, Lasse's, Adrien's, etc.)... Ideally, one would like to see this or any bug-fix merged into the upstream repository, whatever that is.
WDYT?

**Comment by anthrotype** [comment]
excuse my slip of the tongue, I meant defcon, not robofab (but my argument applies equally to both of them).

**Comment by graphicore** [comment]
@anthrotype there are different layers of this problem. Essentially we have two versions of robofab and defcon, that's for each the UFO_v2 and the UFO_v3 branches. Robofab changed in the transition to UFO_v3 a lot, and so all it's dependencies must. For each of these versions we have on top a python_v3 branch.

The `robofab/ufo_v3 python_v3` was made by Adrien, so the `defcon/ufo_v3 python_v3` branch. Note that Adrien added only the python_v3 support ufo_v3 was already there. I don't know if it still supports python2.7. We had some additions and bugfixes on `defcon/ufo3-python3` And it would be cool to get that back into upstream. However, I think that python2 support was dropped, which I can imagine would be a problem for Tal. Further, as I understand, Tal has not so much time for defcon at the moment.

Ideally, everybody would stop using ufo_v2 libraries and update to ufo_v3. Then we should make the ufo_v3 libs compatible for python 2 and 3, much like fontTools does at the moment. But as it seems this is not going to happen soon, at least all the traditional users of robofab don't show much interest in updating (which is a serious problem for the future of UFO if you ask me).

**Comment by moyogo** [comment]
I have a defcon/py23-ufo3 branch that can be merged into trufont/python3-ufo3. I'm not happy with it because the unittest are broken, but that’s in every branch.

**Comment by adrientetar** [comment]
@moyogo can you get that in mainline, rather? This does not buy us much as a fork since we use Python 3.

**Comment by adrientetar** [comment]
@moyogo We want to get other patches into mainline so py23 support would be a great first step for that.

**Comment by moyogo** [comment]
@adrientetar Yeah, Python 2 is only to merge back upstream.

**Comment by anthrotype** [comment]
@graphicore thank you for the clarification, Lasse. Needless to say, I agree with you this is a serious problem for the future (even the present) of UFO. A `py23_ufo3` branch for defcon and robofab would likely speed up the transition to UFO3 (as most editors are stuck with Python 2.7), so it's a good idea to focus on that.
