### ISSUE TITLE
Ruler tool: find intersections at sidebearings

### ISSUE THREAD

**Issue by eliheuer** [trufont/trufont#410]
I'm not sure if this is a design decision, but RoboFont's measurement tool adds intersections at the side bearings. I think this is a helpful feature. 

![robofont-ruler](https://cloud.githubusercontent.com/assets/5162664/24831669/2d7d779e-1c6c-11e7-9183-304954c8f5c4.png)

**Comment by eliheuer** [comment]
I'm slowly working on a PR for this, it's just taking me awhile to get familiar with the code base. :)

Any suggestions on the best approach would be appreciated.

**Comment by eliheuer** [comment]
FontForge handles this in a slightly different way, the ruler tool doesn't add intersections at the sidebearings, but snaps to them instead:

![fontforge](https://cloud.githubusercontent.com/assets/5162664/24976982/8e2d8bc6-1f99-11e7-9d1e-4ed546c9c903.png)

**Comment by adrientetar** [comment]
> Any suggestions on the best approach would be appreciated.

There's just one approach: changing RulerTool._findIntersections()
