### ISSUE TITLE
[glyphview] Winding direction shown on BCP

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#44]
In the glyph view, the winding direction indicator can appear on a BCP; instead it could only appear on the 'parent' point of the BCP?

<img width="1392" alt="screen shot 2015-10-21 at 12 11 38" src="https://cloud.githubusercontent.com/assets/261579/10641639/cc7e9a9a-77f8-11e5-9766-e855567559f8.png">

**Comment by adrientetar** [comment]
What was this font made with? Is it common to have offCurves as start points?

**Comment by graphicore** [comment]
With the point pen protocol this is legal. It's `BasePointToSegmentPen` where a rotation is being made to start with the first on curve point: https://github.com/trufont/robofab/blob/python3-ufo3/Lib/robofab/pens/pointPen.py#L72

**Comment by davelab6** [comment]
I'm not saying that it should be illegal, I'm simply saying that the winding direction indicator is traditionally the first point in a contour, and that while in UFO format (and the point pen protocol) the first point can be a BCP, if so, the UI ought to display the winding indicator on the last point. 

I believe the UFO was made with Glyphs 2.1, so this is likely to be common.

**Comment by graphicore** [comment]
> I'm not saying that it should be illegal

I didn't think so. I was just pointing to the relevant code.

**Comment by adrientetar** [comment]
The only issue is that moving to the offCurve obscures the starting point. Sometimes when prepolating the contours look the same but the start point is on an offCurve on one of the masters,, and both Robofont and Prepolator hide this.

**Comment by moyogo** [comment]
It’s actually clearer if the starting point is shown the starting point.

**Comment by davelab6** [comment]
> It’s actually clearer if the starting point is shown as the starting point.

I'm sorry, do you mean what I show about is an improvement over the convention? I'm willing to accept this ;) However, do you rather mean that there should be an indicator for the starting point, that shows the starting point even if a BCP, and the traditional winding direction indicator?

> when prepolating

Prepolation requires more than just the starting point and winding direction; when trufont sets out a milestone to grow from a font editor to a font family editor, then it will need a UI for the purpose of interpolating :) Do you foresee using layers to develop interpolatable families? Or separate UFOs? Either way, I think its something that the glyph drawing UI needs to support more thoroughly, as Glyphs and Prepolator do. 

Non-interpolatable:

![compatible-10](https://cloud.githubusercontent.com/assets/261579/10643460/bac8e086-7801-11e5-8167-be37034f5170.png)

and interpolatable:

![teaser](https://cloud.githubusercontent.com/assets/261579/10643459/bac3853c-7801-11e5-9819-d3dae0b5af86.png)

G2 also has a nice dialog for reordering glyph elements:

![compatible-2-1](https://cloud.githubusercontent.com/assets/261579/10643483/ed4d49c0-7801-11e5-9db4-aaec29976480.png)

My point is that the contours looking the same is a bad way to check interpolation compatibility, and so is looking at the start points and winding directions :)

(images from https://glyphsapp.com/tutorials/multiple-masters-part-2-keeping-your-outlines-compatible)

**Comment by adrientetar** [comment]
Please stay on-topic, it's not because I wrote the word "prepolating" that this issue suddenly became about prepolation support at large.

**Comment by davelab6** [comment]
> Please stay on-topic

;)

The topic is, is the convention to only show the winding direction on the point wise? 

I think so, if we support a view mode that only shows BCPs for selected points.

**Comment by davelab6** [comment]
@moyogo ping :)

**Comment by moyogo** [comment]
@davelab6 You’re right. The direction should be on an on curve point. Whether that is the first point or not is a different issue, but there’s a convention in place.

**Comment by adrientetar** [comment]
This has changed in #150.
