### ISSUE TITLE
Postscript fields "BlueValues", "*Blues", and "StemSnapH/V" are always present

### ISSUE THREAD

**Issue by madig** [trufont/trufont#454]
Not sure if this is a Trufont or defcon bug, but I noticed that the mentioned fields are *always* present in the font info and can't be removed, they're empty at best. I think this can confuse other tools and is annoying when editing other people's fonts that don't have these values set, as you have to remove them manually before submitting stuff.

**Comment by adrientetar** [comment]
Closing in favor of #510.
