### ISSUE TITLE
Delete glyph confirmation dialog: default selection is "Yes" on Windows, "No" on Linux.

### ISSUE THREAD

**Issue by madig** [trufont/trufont#457]
Windows users live dangerously in more than one way.

**Comment by adrientetar** [comment]
That's consistent with platform behavior. Is this an actual issue?

**Comment by madig** [comment]
No, I just figured that Windows users might more easily lose data. Will look this up later.

**Comment by madig** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/dn742470(v=vs.85).aspx

Hm. Not sure if I'd classify this as a routine confirmation (default: yes) or a risky one (default: no). I guess if there would a way to undo the operation, it would be more like a routine confirmation.

Will close this for now, maybe revisit at some point.
