### ISSUE TITLE
use setuptools_scm to get package version from git?

### ISSUE THREAD

**Issue by anthrotype** [trufont/trufont#458]
https://github.com/pypa/setuptools_scm

Among TruFont's dependencies, only booleanOperations is currently using setuptools_scm to manage the package version.

Most of the other ones are using `bump2version` to manually bump the version before/after a release:
https://github.com/c4urself/bump2version 

I prefer using setuptools_scm because it removes that extra piece of manual intervention, and lets you deploy a new release by simply pushing a git tag. That can be done even from your mobile while sitting on the bus: i.e. just create a new Github Release, and then sit and watch Travis do the rest of the chore.

I can work on PR if you like the idea.

PS: The reason it didn't work when I attempted to add this functionality to fonttools, was that over there people already had entrenched habits on how they "install" the library (e.g. copying a git-cloned fontTools directory to a directory that is then bundled with py2app, etc.) which didn't play well with a git-generated package version. All of that doesn't apply to TruFont.

**Comment by adrientetar** [comment]
done in wx
