### ISSUE TITLE
placeholder disapears when changing markcolor

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#46]

**Comment by adrientetar** [comment]
When you edit the template glyph it becomes a real glyph.

**Comment by davelab6** [comment]
Funny, I was going to report this also, but then I realised what Adrien said; perhaps if the glyph's public.default layer has no elements, the placeholder should still be rendered, but I think its better than if the glyph exists at all, it does not have a placeholder. Therefore setting a glyph's color instantiates it and thus the placeholder is gone.

<img width="931" alt="screen shot 2015-10-21 at 13 54 48" src="https://cloud.githubusercontent.com/assets/261579/10644618/5b5099ee-7808-11e5-94b2-a1aa06c4d8f3.png">

**Comment by davelab6** [comment]
@felipesanches does this make sense? If so, I suggest to close

**Comment by felipesanches** [comment]
I think that simply highlighting a glyph box should not hide the placeholder. I think that the placeholder continues to be useful while we still do not have any glyph outline drawn. So I suggest that placeholders should only be hidden once we have a non-void outline to be rendered in the box.

**Comment by adrientetar** [comment]
robofont does nothing when setting mark color on a template glyph.
