### ISSUE TITLE
Speedpunk-like curvature visualization

### ISSUE THREAD

**Issue by madig** [trufont/trufont#480]
I started using this plugin in Glyphs and hot damn is it eye opening. For the first time, I understand my curves and have control over them! Very useful to have, should be a core option or at least a bundled extension.

**Comment by adrientetar** [comment]
Out of scope for the app. Comb is a useful visualization but by no means a universal thing (a good font doesn't necessarily have continuous curvatures all over).

**Comment by probonopd** [comment]
I second this. Would like to run the now open source https://github.com/yanone/speedpunk on Linux, but it seems one needs to integrate it into some sort of GUI and at first sight it seems to be something TruFont could (easily?) do.

It is written on Python:
https://github.com/yanone/speedpunk/blob/master/SpeedPunk.roboFontExt/lib/deYanoneRoboFontSpeedpunk/speedpunklib.py
> Formerly a commercial plug-in sold by Yanone, it is free & open source software as of December 2019 courtesy of Google Fonts, published under the Apache 2.0 license.

https://github.com/yanone/speedpunk

**Comment by madig** [comment]
I don't have the time and energy to port the plugin over. I also don't know how easy it would be.

**Comment by probonopd** [comment]
> someone made a plugin like this for FontForge somewhere on GitHub iirc.

Interesting, do you remember any of the details? Because this is being discussed as a FontForge feature request as well https://github.com/fontforge/fontforge/issues/4318#issuecomment-623172563 and people there don't seem to be aware of this functionality already being available for FontForge.

**Comment by madig** [comment]
D'oh, I tried to look it up again and found that there was a curve balancer plugin, but not a curvature visualizer plugin. Sorry for the confusion.

**Comment by probonopd** [comment]
Thanks, np.
