### ISSUE TITLE
Icon disappearing

### ISSUE THREAD

**Issue by diegommaldo** [trufont/trufont#5]
The icon appeared when I opened Trufont for the second time, and disappeared after I closed it.

**Comment by adrientetar** [comment]
What OS are we speaking of?

**Comment by diegommaldo** [comment]
Sorry about that – Mac OS 10.11

**Comment by adrientetar** [comment]
Thanks. For me the icon didn't display at all. I'll investigate more.

**Comment by adrientetar** [comment]
Okay it seems I need to provide an icns icon for Mac builds. This will be fixed in the next builds hopefully.

**Comment by adrientetar** [comment]
Can you try https://github.com/trufont/trufont/releases/download/v0.1.0/TruFont-0.1.0-darwin-10.9.5-x64.zip and tell me if this fixes it for you?

**Comment by pathumego** [comment]
@adrientetar had the same issue, fixed in one you posted

**Comment by diegommaldo** [comment]
worked for me too.
