### ISSUE TITLE
Improve handling componants 

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#503]
- [ ] Doble click on componant should trigger `Got to Glyph`
- [ ] Rename `Go to Glyph` to `Edit Componant`?

**Comment by adrientetar** [comment]
> Rename Go to Glyph to Edit Componant?

Why? Editing the glyph does not change the component.

**Comment by pathumego** [comment]
Editing the origin glyph change the componant right? So I thought it makes sense to say the `Edit Compoanat` 
PS: There is a good chance Im confused about words here :)

**Comment by adrientetar** [comment]
done in wx
