### ISSUE TITLE
Tools for quickly creating simple geometric shapes

### ISSUE THREAD

**Issue by balthild** [trufont/trufont#504]
For example, it's hard to draw a perfect circle only with pen tools.

Showing anchors' coordinates is also a good workaround.

**Comment by pathumego** [comment]
Are these tools going to be implmented as Extentions? I think the `Circle` and `Rectagle` should be there out of the box. In Glyphs app it under one tool `Premitives`

**Comment by pathumego** [comment]
Are these tools going to be implmented as Extentions? I think the `Circle` and `Rectagle` should be there out of the box. In Glyphs app it under one tool `Premitives`

**Comment by balthild** [comment]
Great! Is there any documentation or sample for implementing an extension at present?

BTW, I think showing coordinates of anchors is still usefully.

**Comment by eliheuer** [comment]
I have a shapes tool with basic rectangle drawing functionality implemented here: https://github.com/eliheuer/trufont/tree/shapes-tool

![trufontshapestoolrecttest01](https://user-images.githubusercontent.com/5162664/34329203-6bc93144-e8c4-11e7-8007-2fbb95c4ce8c.gif)

I'm working on adding an ellipse and some other functionality from the robofont shapes tool: https://github.com/typemytype/RoboFontExtensions/blob/master/shapeTool/ShapeTool.roboFontExt/lib/drawShapesTool.py

**Comment by eliheuer** [comment]
I updated the shapes tool branch with a feature that draws an ellipse when the right mouse button is pressed: https://github.com/eliheuer/trufont/tree/shapes-tool

![trufontshapestoolrecttest02](https://user-images.githubusercontent.com/5162664/34363061-a036e0c4-ea46-11e7-9aaf-df1c8a93285a.gif)

It still needs some work on things like a constraint to draw a perfect square or circle, but it's basicaly usable at this point.

**Comment by pathumego** [comment]
@eliheuer this is awesome! Thanks!

**Comment by davelab6** [comment]
Awesome job!!

**Comment by balthild** [comment]
Great works!

**Comment by eliheuer** [comment]
I just pushed a new update to this tool here: https://github.com/eliheuer/trufont/tree/shapes-tool

This new update has a feature that lets the user hold the shift key down while drawing to equalize the width and height of the shape. Similar to the shift constraint used by the ruler tool:

![trufont504_01](https://user-images.githubusercontent.com/5162664/34527479-ae41fedc-f073-11e7-89b4-e566dfba87da.gif)

Also, the way ellipses are draw has been improved to avoid round diamonds.
