### ISSUE TITLE
empty guidelines and PS blues are added on save to fontinfo.plist

### ISSUE THREAD

**Issue by anthrotype** [trufont/trufont#510]
this is a minor thing, I post it here so that I don't forget about it.

I noticed that if when I open a UFO that does not have any global `guidelines` or does not define any postscript blues in the fontinfo.plist, whenever I save it back with Trufont, empty arrays automatically get added for those values in the fontinfo.plist.

```diff
--- a/tests/data/RobotoSubset-Regular.ufo/fontinfo.plist
+++ b/tests/data/RobotoSubset-Regular.ufo/fontinfo.plist
@@ -2,6 +2,27 @@
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
        <dict>
+               <key>guidelines</key>
+               <array>
+               </array>
+               <key>postscriptBlueValues</key>
+               <array>
+               </array>
+               <key>postscriptFamilyBlues</key>
+               <array>
+               </array>
+               <key>postscriptFamilyOtherBlues</key>
+               <array>
+               </array>
+               <key>postscriptOtherBlues</key>
+               <array>
+               </array>
+               <key>postscriptStemSnapH</key>
+               <array>
+               </array>
+               <key>postscriptStemSnapV</key>
+               <array>
+               </array>
                <key>unitsPerEm</key>
                <integer>2048</integer>
```

I think those elements are optional, so it'd be nice if TruFont didn't add them if they are not already there, and the user didn't use them either.

**Comment by moyogo** [comment]
This seems to be a lower level issue. `Font().save('test.ufo')` will generate a fontinfo.plist with those empty plist items.

**Comment by anthrotype** [comment]
I see, thanks. Let's move this over to defcon then

**Comment by mashabow** [comment]
https://github.com/typesupply/defcon/issues/173

**Comment by madig** [comment]
Defcon issue.
