### ISSUE TITLE
Let status bar handle all zoom level state

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#521]
When I zoom in or out with keystrokes the zoom level indicator is not updated.

<img width="412" alt="screen shot 2017-12-11 at 2 38 14 am" src="https://user-images.githubusercontent.com/6846609/33809406-5f55a10c-de1c-11e7-9712-86f473303f55.png">

**Comment by thomgb** [comment]
Why is this code in an else?
https://github.com/trufont/trufont/blob/c0ae5bfe1c3581d90f8473bbb26e20e83d8eb438/Lib/trufont/windows/fontWindow.py#L877-L886

if the else code is not in the else the zoom works.

**Comment by adrientetar** [comment]
Fixed d069a3275b50fdd8ecf3da4c666de861e220bc03, but now the buttons don't have the proper zoom unlike the shortcuts.

@thomgb font/glyph tabs work differently, arguably the statusBar should know how to zoom or rather manage state from a single code path.

Also zoom should be centered on cursor even with shortcuts if cursor is hovering over the canvas. new trufont will do better (doesn't try to have one statusBar for all tabs, that's a one state many codepaths mess).

**Comment by pathumego** [comment]
@adrientetar Thanks!
