### ISSUE TITLE
Glyph names and data

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#528]
What is the best way to handle glyph names and Unicode data in TruFont? Do you have a plans for supporting GlyphData.xml format from GlyphsApp? Or do we stick with current structure `A;0041, one per line` as mentioned in https://github.com/trufont/trufont/issues/122#issuecomment-154738483 ?

This was discussed partially in #122, #436 and #331

**Comment by adrientetar** [comment]
I'm thinking of something for the new TruFont, but right now I'm working on file formats.

**Comment by pathumego** [comment]
@adrientetar Awesome! Thanks

**Comment by adrientetar** [comment]
Closing in favor of #436 let's stick just one issue for this
