### ISSUE TITLE
Not launching on Windows 10

### ISSUE THREAD

**Issue by ngoo5tsong5sik** [trufont/trufont#531]
Trufont 0.6.0.dev0 failed launching. Nothing happens when running `trufont`.
I’ve also tried the installer but only got an error.
![default](https://user-images.githubusercontent.com/16879992/34619571-882f8c3a-f27d-11e7-8b03-8be42c336f3a.png)
How can I get the log?

**Comment by adrientetar** [comment]
~~~
git clone https://github.com/trufont/trufont
cd trufont
pip3 install -r requirements.txt
python setup.py install
python -m trufont
~~~

**Comment by ngoo5tsong5sik** [comment]
![default](https://user-images.githubusercontent.com/16879992/34622328-b67e7a74-f287-11e7-8e81-1455048d7a8b.png)
Python crashes after `python -m trufont`. Reinstalling didn’t fix the problem.

**Comment by adrientetar** [comment]
pip install PyQt5

**Comment by ngoo5tsong5sik** [comment]
I already have PyQt5 5.9.2 installed, Python still crashes at launching. 😦

**Comment by StefanPeev** [comment]
![image](https://user-images.githubusercontent.com/12949369/36243808-1f51617e-122c-11e8-8844-1bba8f4db48f.png)
