### ISSUE TITLE
Font info dialog: minor version should be zero-padded.

### ISSUE THREAD

**Issue by madig** [trufont/trufont#534]
The versioning schemes I have seen use a `M.mpp` format, e.g. `1.005`. Since major and minor version are just integers, Glyphs pads the minor version with zeros, so that major 1 and minor 5 display as `1.005`. Trufont should do the same.

**Comment by adrientetar** [comment]
The compiler does that yes: https://github.com/googlei18n/ufo2ft/blob/33fb9495b9a58af09e217f8baa2460b9c6d6ea33/Lib/ufo2ft/outlineCompiler.py#L233

What is the issue?

**Comment by madig** [comment]
The display of the minor version. Trufont currents shows a "5" and I'd like it to show "005" instead.

**Comment by madig** [comment]
Closed by #673.
