### ISSUE TITLE
Can we update the README to use git and not pip?

### ISSUE THREAD

**Issue by EwonRael** [trufont/trufont#535]
Right now cloning from git seems like the way to get TruFont, so can the instructions in the README reflect this instead of using pip?

Small thing I know

**Comment by eliheuer** [comment]
I always install in editable mode, even when I'm using TruFont to work on UFOs. This is what I usually do:

```
python3 -m venv ENV_DIR
source ENV_DIR/bin/activate
cd ENV_DIR
git clone git@github.com:trufont/trufont.git
cd trufont
pip install --upgrade -r requirements.txt
pip install --editable .
trufont
```
Is that what you are suggesting @EwonRael?

**Comment by davelab6** [comment]
I think it's a good idea

**Comment by eliheuer** [comment]
@EwonRael I made a new branch in my fork with updated install instructions: https://github.com/eliheuer/trufont/tree/issue-535

Let me know if this looks good to you and I will make a pull request. 

Also, I made a YouTube video demonstrating the quick install chain method, which I use **all the time**: https://youtu.be/sLvm5185_ak

**Comment by madig** [comment]
Installing from PyPI is now the way to go, unless you want to hack on TruFont.
