### ISSUE TITLE
After upgrade Trufont couldn't be start on Windows 8.1

### ISSUE THREAD

**Issue by StefanPeev** [trufont/trufont#543]
I receive this message after latest upgrades: see the picture...
![trufont_01](https://user-images.githubusercontent.com/12949369/36160816-cd9e51ee-10ea-11e8-980b-95179f51f100.jpg)

**Comment by adrientetar** [comment]
Looks like an issue with PyQt/Qt, which version is it? does `import PyQt5` works?

**Comment by adrientetar** [comment]
Also trufont itself should be installed from git as in: https://github.com/trufont/trufont/issues/531#issuecomment-355618187
