### ISSUE TITLE
Curve Comb Tool

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#544]
https://beta.observablehq.com/@dhotson/drawing-better-looking-curves explains how Curve Comb Tools work, which have become common to many designer workflows :)

**Comment by eliheuer** [comment]
I'm finishing up a calculus class now, so I think building this might be be within my abilities since I have this type of math fresh in my mind. I'll start looking into it.

**Comment by adrientetar** [comment]
Out of scope for the app. Comb is a useful visualization but by no means a universal thing (a good font doesn't necessarily have continuous curvatures all over).
