### ISSUE TITLE
Offer fontParts API

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#549]
I'd like to propose that TruFont support the fontParts API, since most users coming to TruFont will be familiar with it and will want to port their scripts that use it.

https://github.com/davelab6/type-notes/blob/master/2018-03-08_robothon.md#fontparts

https://www.dropbox.com/s/5qi00qpynptgsjh/fontparts_robothon_18.pdf?dl=0

**Comment by benkiel** [comment]
FontParts should be stable enough to put in now. RoboFont is currently using it. We're working on getting a 1.0 release with full tests out. If you look at the nonelab (or, by the time you see this, perhaps fontshell) reference implementation of it, you should be able to copy most of it as that is built on Defcon. Do look at the (yes it needs docs) ui.py for the simple kit of UI widgets to provide scripters (yes, folks can build much more complicated things if they want, this if for those who don't want to, and they are optional if you don't want to include them)

**Comment by pathumego** [comment]
This will partially fix #172 and #436

**Comment by benkiel** [comment]
@pathumego What you want is typemytype's Glyph Constructor. Robofab had a `compileGlyph` and `generateGlyphs` methods, but they were rather limited and really fussy to use. We took them out of FontParts. One could build on top of FontParts for this, or TruFont could offer it's own environment specific method if it wanted to.

**Comment by pathumego** [comment]
@benkiel thanks! Isn't glyph constructor part of FontParts?  It says so in Daves notes.
 Would make sense to just provide it through FontParts instead of duplicating.

**Comment by benkiel** [comment]
@pathumego It isn't, the notes (through no fault of Dave, I talk quickly!) aren't quite right. We don't want to provide it, as it's something that is difficult to abstract in a way that works for a broad variety of use cases without building something as large as TypeMyType's GlyphConstructor. Whatever we would put into FontParts would be smaller than that, disappoint many, and duplicate much of GlyphConstructor, so it's better that it be there than FontParts — hopefully that makes sense
