### ISSUE TITLE
QGtKstyle dependency error - blank menus

### ISSUE THREAD

**Issue by n7s** [trufont/trufont#6]
Please provide more details about the QGtKstyle dependency. Certain distros don't ship that part of QT by default and the result is blank menu entries. 

It seems something with the theme engine is unhappy or simply missing. Switching the theme configuration with qt-config doesn't seem to fix it.  

On Ubuntu MATE:
"QGtKstyle could not resolve GTK. Make sure you have installed the proper libraries." 

It works on Debian unstable though.  Thanks!

**Comment by adrientetar** [comment]
I don't depend on it explicitly in the code, it's a Qt theme. It is dispatched depending on the platform, I don't know how pyinstaller behaves in this department tbh.

**Comment by adrientetar** [comment]
It might be that I froze the linux build on Xubuntu which has GTK-style interface. If anyone has guidance on how to make a binary that will work with all desktop environments, feel free to post here.

**Comment by n7s** [comment]
I suspect the issue was down to having the wrong version of python and its deps installed. The improved INSTALL.txt should help.
