### ISSUE TITLE
Space center does not auto-update when loading new font file

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#61]
steps to reproduce:
* open trufont
* open the space center dialog
* click file->open and load a new UFO

bad behaviour:
* the space center dialog does not render the text
* we have to close the dialog and reopen it in order to make it render correctly

expected result:
* simply render the text automatically using the new loaded fontface

**Comment by adrientetar** [comment]
> the space center dialog does not render the text

I don't see this on my computer, can you post a screenshot? (Also the space center is a window, not a dialog.)
