### ISSUE TITLE
Version on PyPI is outdated

### ISSUE THREAD

**Issue by probonopd** [trufont/trufont#622]
https://pypi.org/project/trufont/#history has 0.5.1.dev1  as the "latest". It cannot be installed due to the known `ModuleNotFoundError: No module named 'defconQt.controls.accordionBox'`
 issue.

Reference:
https://github.com/linuxdeploy/linuxdeploy-plugin-conda/issues/11#issuecomment-450837246

**Comment by adrientetar** [comment]
Duplicate of #442
