### ISSUE TITLE
ModuleNotFoundError: No module named 'fs'

### ISSUE THREAD

**Issue by probonopd** [trufont/trufont#623]
Getting `ModuleNotFoundError: No module named 'fs'`.
Probably it should be listed in https://github.com/trufont/trufont/blob/master/requirements.txt.

Reference:
https://github.com/linuxdeploy/linuxdeploy-plugin-conda/issues/11

**Comment by doums** [comment]
same issue here, how I can fix this ? (I'm a noob in python)

**Comment by chrissimpkins** [comment]
Workaround until fixed is 

```
pip3 install fs
```

then run again.

**Comment by probonopd** [comment]
Probably `fs` should be listed in https://github.com/trufont/trufont/blob/master/requirements.txt then?

**Comment by madig** [comment]
The requirements are very out of date. Technically you have to install `fontTools[ufo]` to get the dependency.

**Comment by santhoshtr** [comment]
#636 resolved this.
