### ISSUE TITLE
Green round vs blue square nodes? (New to TruFont)

### ISSUE THREAD

**Issue by jamadagni** [trufont/trufont#641]
Hello I am new to TruFont and opening this issue since I don't see any other mailing list or forum linked to from the home page http://trufont.github.io/. (Please point me out to any such forum intended for such things if this is not the place for such queries.)

See for example this glyph in one of my TTF fonts imported:

![Screenshot_20190407_100659](https://user-images.githubusercontent.com/948170/55678779-e9eb9e80-591c-11e9-9cf2-504dd695b1c6.png)

It would seem to me that the green round nodes are “smooth” ones and blue square nodes are “corner” ones. There are no handles (off curve points) between two blue nodes whereas there can be a handle between a blue and a green nodes or two green nodes. If I manipulate the handle to one side of a green node the handle on the other side gets rotated (and if the handle stands between two green nodes then the handles of the other sides of both get rotated). This is what I have observed, and it is sort of self-evident which is nice.

However, it is not clear how to create green nodes because if I open an empty glyph I am only able to create blue nodes.

And is this only because for the TTF font I have imported there are only quadratic curves? I mean, here there is only one handle between two nodes, so how can I create a spline with cubic Béziers ie two handles to each node? 

Thanks!

**Comment by santhoshtr** [comment]
You can double click a node to toggle between green and blue ones.
