### ISSUE TITLE
Why are the children of contours points not segments? Why no bPoints?

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#66]
RoboFab has traditionally had contours that contain segments which contain points, and also that have bPoints. Eg in RoboFont I can run,

```py
glyph = CurrentGlyph()
contour = glyph[0]

# access segments as children
for segment in contour:
    print(segment)
    for point in segment:
        print(point)

# access points from list of points
for point in contour.points:
    print(point)

# access bPoints
for bPoint in contour.bPoints:
    print(bPoint)
```

But today in Trufont, points are the direct children of contours, and bPoints don't exist:

```py
glyph = CurrentGlyph()
contour = glyph[0]

# access contours from list of segments
for segment in contour.segments:
    print(segment)
    for point in segment:
        print(point)

# access points as children
for point in contour:
    print(point)

# access bPoints
for bPoint in contour.bPoints:
    print(bPoint)
```

raises `AttributeError: 'TContour' object has no attribute 'bPoints'`

@adrientetar why is this? :)

**Comment by adrientetar** [comment]
defcon was made to get rid of unnecessary levels of abstraction that slow things down and get in your way. If you want to build segments from the points, that is what contour.segments does indeed.

**Comment by davelab6** [comment]
I see. How is robofab used in trufont?

**Comment by moyogo** [comment]
> How is robofab used in trufont?

Almost not at all. Only AbstractPointPen is imported.

**Comment by adrientetar** [comment]
> Only AbstractPointPen is imported.

Yes and there are similar uses in defcon.

**Comment by davelab6** [comment]
On Oct 25, 2015 2:39 PM, "Denis Moyogo Jacquerye" <notifications@github.com>
wrote:
>>
>> How is robofab used in trufont?
>
> Almost not at all. Only AbstractPointPen is imported.

Ah. Could we remove this dependency and in line that pen?

**Comment by adrientetar** [comment]
It would still be needed for defcon and fontTools. Eseentially the pens part. That's mainly what's used besides ufoLib.

**Comment by adrientetar** [comment]
Not fontTools, only defcon my mistake.

**Comment by adrientetar** [comment]
Migrating remaining pens from robofab to fonttools and splitting ufoLib might be a thing.

**Comment by davelab6** [comment]
Ok cool

I guess we will need a "porting from robofab to defcon" guide that lists
these differences.

Looks like i can use the  inspect module to list the methods of both.
