### ISSUE TITLE
Dragging a glyph in fontView is slow

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#67]
Dragging a glyph in fontView is slow.

https://youtu.be/8mRquIryH1E

**Comment by adrientetar** [comment]
It doesn't slow down on my own system.

**Comment by moyogo** [comment]
It’s significantly slow on OS X but fast on Ubuntu for me.
On OS X the glyph names hover and lag catching up to to the cursor. There are no glyph names displayed on Ubuntu.

**Comment by adrientetar** [comment]
And I get

```
QNSView mouseDragged: Internal mouse button tracking invalid (missing Qt::LeftButton)
```

at the command-line.

**Comment by pathumego** [comment]
Im seeing the same issue on OSX

**Comment by pathumego** [comment]
It works fine in the HEAD

**Comment by davelab6** [comment]
Good :)
