### ISSUE TITLE
jupyter qtconsole and notebook

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#68]
https://jupyter.org qtconsole is a powerful REPL, that would be great to have in addition to the current scripting window. 

The jupyter notebook would also be wonderful to have, especially as it could provide a 'live' introductory tutorial system.

**Comment by adrientetar** [comment]
Can be a plugin.

**Comment by davelab6** [comment]
I agree. https://www.reddit.com/r/Python/comments/1q9tq7/what_is_the_big_deal_about_ipython_notebooks/ has some good notes on why this is tasty
