### ISSUE TITLE
python 2 or 3?

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#688]
Robofab and BooleanOperations are listed on README.md as some of the TruFont dependencies.

----
If I try installing robofab on a **python 3** virtualenv I get this error:
<img width="1242" alt="Captura de Tela 2020-01-30 às 09 31 22" src="https://user-images.githubusercontent.com/213676/73450098-6f748b00-4343-11ea-9f3e-05b1f5a513e3.png">
According to https://github.com/robotools/ufo2fdk/issues/33#issuecomment-473038914 this seems to mean robofab is stuck (forever?) on python 2.

----
Then setting up a **python 2** virtualenv, I get this:
<img width="1237" alt="Captura de Tela 2020-01-30 às 09 30 30" src="https://user-images.githubusercontent.com/213676/73450330-ef025a00-4343-11ea-8ebb-d3d985a0d019.png">

**Comment by felipesanches** [comment]
while investigating this, I also noticed some problems on the requirements.txt and README, so I tried to fix them on https://github.com/trufont/trufont/pull/689

**Comment by madig** [comment]
The Readme is out of date then, the actual deps are in https://github.com/trufont/trufont/blob/master/setup.cfg. Py 3.6+ only.

**Comment by felipesanches** [comment]
sorry, my mistake!
