### ISSUE TITLE
Include booleanOperations

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#69]
To include https://github.com/typemytype/booleanOperations there are a couple of things that seem obvious to me:

- [ ] Update the module to work on python 2 and 3 (@anthrotype is already working on this :)
- [ ] set up PyInstaller to correctly package the C++ part 
- [ ] a convenience API (similar to http://doc.robofont.com/api/mojo/mojo-tools/)
- [ ] buttons on the inspector (similar to https://github.com/typemytype/pathOperatorRoboFontExtension)

**Comment by adrientetar** [comment]
It doesn't have to be part of the main program &ndash; I'd rather we get a proper plugin system. This and supporting all ufo3 attributes are # 1 things to do at the moment.

**Comment by davelab6** [comment]
I can't see how this isn't core, and it is core to RoboFont. 

Maybe trufont and defconQt ought to be split?

**Comment by adrientetar** [comment]
OK for removeOverlap I guess, there's an old version of the package embedded in defcon.
