### ISSUE TITLE
On MacOS, TruFont shows up as "python3.7" on the top menubar

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#690]
<img width="290" alt="Captura de Tela 2020-01-30 às 09 53 54" src="https://user-images.githubusercontent.com/213676/73451534-93859b80-4346-11ea-8ff3-0147da36eb98.png">

**Comment by madig** [comment]
Yeah. Haven't bothered with finding out why yet. You also need to double Cmd-Q to quit,

**Comment by felipesanches** [comment]
it seems that this one was a duplicate of #555 and was fixed by #720 

Thanks, @hskim08 :-D
