### ISSUE TITLE
download being tagged as infected with a virus

### ISSUE THREAD

**Issue by misterphil** [trufont/trufont#696]
Tried to download - antivirus blocks it - Severe risk. Download failed - virus detected.

running EST endpoint ant virus

**Comment by madig** [comment]
Downloaded what exactly?

**Comment by misterphil** [comment]
the folder TruFont.exe.fixed.zip 

https://github.com/trufont/trufont/releases/tag/0.4.0

**Comment by madig** [comment]
According to https://www.virustotal.com/gui/file/1edf3680857206896e0ac3e83d38c14414dca1c5737e16611154b8db463daa0e/detection, many engines do not detect anything. The file has existed for years, so I'm inclined to write it off as a false positive. Does your AV point to a specific file?

**Comment by madig** [comment]
Meh. I have removed the release files, https://trufont.github.io/ is out of date anyway.
