### ISSUE TITLE
Deleting points in OSx

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#7]
In OSx 10.10.5, To delete points I have to hold `fn+Delete` Expected key is just Delete.

**Comment by davelab6** [comment]
> Expected key is just Delete

ie, backspace

**Comment by diegommaldo** [comment]
Beyond that, if I try to delete off curve points, in a broken angle bezier, when I delete one, it deletes the the other instead. When the bezier off curve is aligned, works fine.

Mac OS 10.11

**Comment by moyogo** [comment]
There is no ⌦ Delete key on Mac Book keyboards, fn + ← Backspace is what you have to use for the Delete key. The ⌦ Delete key is on 105-key keyboards next to ↖ Home, ↘ End, ⭻ Page Up, ⭽ Page Down.
@pathumego Do you want Backspace to behave like the Delete key and delete selected nodes, etc.?

> Beyond that, if I try to delete off curve points, in a broken angle bezier, when I delete one, it deletes the the other instead. When the bezier off curve is aligned, works fine.

@diegommaldo This sound like a separate issue.

**Comment by diegommaldo** [comment]
for sure it is, but we are talking about deleting points, right @moyogo ?

**Comment by adrientetar** [comment]
> in a broken angle bezier

I do not understand this.

**Comment by pathumego** [comment]
:+1:
