### ISSUE TITLE
End-user marketing (screenshots, list of features, comparison to FontForge/Birdfont)

### ISSUE THREAD

**Issue by hartwork** [trufont/trufont#704]
Hi!

I only ran into TruFont today by accident. Very cool project!
Right now the readme only targets installation and contribution by developers.
It would be nice to also offer:
- a few screenshots
- a list of features offered by TruFont
- a high-level comparison to FontForge and Birdfont

Thank you!

**Comment by madig** [comment]
The problem is that the project is essentially 1) alpha quality still and 2) on ice. I have other things to do and only very occasionally have time for a bit of hacking...

**Comment by hartwork** [comment]
Okay. How should we best move forward?

**Comment by madig** [comment]
I don't know. The software is not ready for production, which probably makes end-user marketing pointless right now.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
