### ISSUE TITLE
[0.6.3] "All supported files" in Open/Import dialog 

### ISSUE THREAD

**Issue by hartwork** [trufont/trufont#705]
Hi!

The current open/import dialog has a single filter labelled "All supported files". So I need to read code to find out what files are supported:
https://github.com/trufont/trufont/blob/a5d0282420b44268e45c1e12fa9cfe4e63c69b29/Lib/trufont/objects/application.py#L403-L414

With regard to UX, that's a bit unfortunate. It would be great to have one filter per type so that as a user I can open the dropdown and get a sense of supported types.

PS: The split between open and import seems artificial from a UX point of view to me. Maybe these two dialogs can be merged?

Thanks and best, Sebastian

**Comment by madig** [comment]
Open and import are similar, yeah. One day.
