### ISSUE TITLE
Can't try it as downloading TruFont.exe.fixed.zip triggers Threat blocked in Windows 10

### ISSUE THREAD

**Issue by onetoomanyonesandzeroes** [trufont/trufont#708]
Trojan:Win32/FormBook.O!MTB
Please fix this.

**Comment by madig** [comment]
You are the second person to report a virus in there (https://github.com/trufont/trufont/issues/696), but virustotal.com can't find something significant. I have opted to just delete these files for now. https://trufont.github.io/ is out of date anyway.

**Comment by lorenzogatti** [comment]
I can confirm the issue, as of today, with the built-in antivirus of Windows 10 Professional (version 20H2, well updated), but there is a simple and obvious solution: not bothering with the executable and installing the bare Python package.

pip install trufont

**Comment by alerque** [comment]
Is there by chance a copy of the Harfbuzz source being bundled somewhere in the packaging?

**Comment by madig** [comment]
I wouldn't know of that 🤔
