### ISSUE TITLE
Missing downloads / macOS support?

### ISSUE THREAD

**Issue by nbromberg** [trufont/trufont#713]
As linked from the homepage under "Mac OS Install", https://github.com/trufont/trufont/releases/download/0.4.0/TruFont.app.zip does not exist. Also, after installing from pip on macOS 10.12.6, I get a similar error to #210:

`Traceback (most recent call last):
  File "/Users/*****/Library/Python/3.7/bin/trufont", line 5, in <module>
    from trufont.__main__ import main
  File "/Users/*****/Library/Python/3.7/lib/python/site-packages/trufont/__main__.py", line 4, in <module>
    from PyQt5.QtCore import QCommandLineParser, QLibraryInfo, QLocale, Qt, QTranslator
ImportError: dlopen(/Users/*****/Library/Python/3.7/lib/python/site-packages/PyQt5/QtCore.abi3.so, 2): Symbol not found: _futimens`

This is probably just because my OS is out of date, I guess. But any way I can get this program running would be appreciated.

**Comment by madig** [comment]
I deleted the old releases, the home page is unfortunately way out of date and I didn't have time to update it yet. Please install via pip or pipx.

**Comment by nbromberg** [comment]
Okay — would installing an older release from pip solve the above error?

**Comment by madig** [comment]
Possibly, I haven't tried.

**Comment by nbromberg** [comment]
It looks like the problem was with the PyQt5 library. Installing older version 5.13.0 fixed the issue, thanks for your help!
