### ISSUE TITLE
Can't load .ufo file (folders) on Linux

### ISSUE THREAD

**Issue by probonopd** [trufont/trufont#715]
Similarly to 

> Can't load .ufo file (folders) on macOS #681

This is with TruFont 0.6.4 on Ubuntu 18.04.4 LTS. When trying an `.ufo`, it is treated as a directory, and I am not able to select it for being loaded. Instead, the folder is opened within the file chooser, and the contents of the folder are shown.

Workaround: Provide the path to the `.ufo` as an argument to `trufont` on the command line.

**Comment by madig** [comment]
You must select the metainfo.plist file on Linux and Windows, because only macOS can treat folders like files.

**Comment by probonopd** [comment]
Thanks @madig. Maybe it's a nitpick, but possbly a "Open UFO directory..." menu entry with with something like this

```
QFileDialog dialog;
dialog.setFileMode(QFileDialog::DirectoryOnly);
dialog.setOption(QFileDialog::DontUseNativeDialog, true);
dialog.setOption(QFileDialog::ShowDirsOnly, false);
dialog.exec();
qDebug() << dialog.directory();
```

could be used?

Reference:
https://forum.qt.io/topic/62138/qfiledialog-choose-directories-only-but-show-files-as-well/13

**Comment by madig** [comment]
Thanks for looking that up. Possibly, feel free to send a PR if you have the time (or anyone else).

**Comment by probonopd** [comment]
First need to find the PyQt equivalents I guess. The above is C++ Qt but possibly there are matching Python calls.

**Comment by madig** [comment]
I think the Python bindings match the C++ names for the most part in both PySide2 and PyQt5.
