### ISSUE TITLE
Port Vanilla to PyQt5?

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#73]
While PyQt already wraps various platform APIs, and has a standard library with good documentation and tutorials all over the web, it may not be as convenient as Vanilla is (especially for those already familiar with Vanilla.) 

Making an API compatible with Vanilla will make it easier to maintain extensions for both RoboFont and Trufont, and for making simple dialogs quickly.

Fontlab Ltd may or may not contribute to this effort, as @twardoch has been supportive, but Yuri Yarmola said on Facebook, "It would be cool to 'port' Vanilla to Qt, but full collection of Qt widgets and classes is OK anyway, whatever the platform." [source](https://www.facebook.com/photo.php?fbid=914633451885000))

Who else thinks this would be a good idea?

**Comment by adrientetar** [comment]
Qt is essentially a vanilla already, I agree with yyar and I will not engage into this.
