### ISSUE TITLE
[Question] Crash reports from Mac?

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#76]
Im running 0.1.0 and crashed while opening a ufo. Would summery from Mac OS help to track the problem?

**Comment by davelab6** [comment]
I also saw a lot of crashes in the release package of 0.1.0, but they are
fixed in the git master.

In the INSTALL file clear enough for you about how to run the unpackaged
version from source?

**Comment by pathumego** [comment]
Im having problems with setting up pyQT5 with homebrew. Couldn't actually figure out what's the problem. Ill try again.

**Comment by pathumego** [comment]
but question remains these crash reports are no use? if so is there a way to get a useful backtrace?

**Comment by davelab6** [comment]
This worked for me:

    brew install python3; brew install pyqt5

I agree that a backtrace reporter would be good to do early to push up a
quality perception early.

**Comment by pathumego** [comment]
Ok, Its something wrong with my homebrew, pyqt5 takes ages to install and I think its failing because of that. Closing since this is not relevant here.

**Comment by davelab6** [comment]
Did you pass any options to the brew install pyqt5 command? If you do it
will compile from source and take ages and maybe fail. If you don't it will
install from a bottle (precompiled) and be fast.

**Comment by pathumego** [comment]
No figured there are some issues with my homebrew, and it is trying to
compile without installing bottle. This is the error.
```
You have an outdated version of /usr/bin/install_name_tool installed.
```

 I found a solution will try :)
