### ISSUE TITLE
Our logo icon is currently under a non-free license

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#77]
The Non-Commercial aspect of this license is problematic (for several reasons, one of which is the packaging of the program in free software operating system distributions). We should consider changing the licensing terms to a libre license. I suggest adopting the Creative Commons By-SA license for these image resources.

Tasks:
- [x] Get authorization from the authors of the logo artwork for relicensing it under a libre license (such as CC BY SA)
- [ ] Delete https://github.com/trufont/trufont/blob/master/Lib/defconQt/resources/CC-BY-NC-SA-4.0.txt
- [ ] Edit the toplevel README.md file to include a session describing the overal licensing of the program and of its assets

**Comment by jbmorizot** [comment]
As one of the authors, I authorize the relicensing under a libre license: CC BY SA.

**Comment by felipesanches** [comment]
Great!

It would be good to have explicit authorization from the other author as well :-)

**Comment by jjjlllnnn** [comment]
Here is ma authorization, CC BY SA works for me.

**Comment by felipesanches** [comment]
Cool, thanks!
