### ISSUE TITLE
bad executable name for GNU+Linux package

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#79]
A user complained that he was confused about the naming of the executable file on the GNU+Linux zip release.

It is called **\_\_main\_\_** while I believe that calling it **trufont** would be much better.

**Comment by n7s** [comment]
This should already be fixed by the revised setup.py.

**Comment by adrientetar** [comment]
Actually the packaging is something different from setup.py, lets keep this open until it is confirmed fixed.

**Comment by felipesanches** [comment]
I got another complaint about it today from a different user.

**Comment by adrientetar** [comment]
Should be fixed in latest release.
