### ISSUE TITLE
Display the program's version number in the UI

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#81]
This will be important in the future for bug-reports whenever we have more than one publicly available stable release.

The version number can/should be added to:
- [x] the "About" dialog
- [ ] the active window title bar

**Comment by davelab6** [comment]
About dialog is done. 

<img width="420" alt="screen shot 2015-11-10 at 14 44 45" src="https://cloud.githubusercontent.com/assets/261579/11056961/9f8b5606-87b9-11e5-81e2-3b1f3cf23d45.png">

**Comment by adrientetar** [comment]
That should be enough.
