### ISSUE TITLE
Documentation for the python scripting API

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#82]
Users and script developers will need at least an overview of the API.
In the long run, we'll need detailed documentation in order to foster a growing extensions development community.

**Comment by felipesanches** [comment]
Documentation shuld eighter be bundled in the program itself or, if available online, then the URL of the online resources should be proeminently displayed whenever the user opens the scripting window.

It could/should also be added to the help menu since it is the most obvious place where people will be looking for technical info.

**Comment by adrientetar** [comment]
Closing in favor of #520.
