### ISSUE TITLE
Licensing madness :-P

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#88]
We have a file called SIL.txt with the following confusing header:

```
cursor.svg, curve.svg and ruler.svg are licensed under the following terms:

Copyright (c) 2014, Austin Andrews (http://materialdesignicons.com/),
with Reserved Font Name Material Design Icons.
Copyright (c) 2014, Google (http://www.google.com/design/)
uses the license at https://github.com/google/material-design-icons/blob/master/LICENSE

This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is copied below, and is also available with a FAQ at:
http://scripts.sil.org/OFL
```

Then it has a copy of the text of the SIL licensing terms.

This is confusing because:

* the license referenced by https://github.com/google/material-design-icons/blob/master/LICENSE is actually not SIL, but CC-BY instead.
* the header mentions both a person and Google. So I assume that this person is the author, who probably works for Google, and then the copyright belongs to Google. But maybe it can also mean that this person made a derivative of a work originally provided by Google (or vice-versa).
* when it says "This Font Software" it is not clear what it is refering to. I understand that fonts can be considered to be equivalent to software for licensing purposes, but the files we're dealing with here are neighter software nor a font. These are SVG files (i.e. vector graphics). I would use different wording here to avoid confusion. Maybe I would say "these graphics assets" instead of "this font software".
* additionaly, the "font software" wording can lead to a misunderstanding, given that this repository actually hosts a font editor application called TruFont and we don't want to make people mistalenly think that its source code is licensed under SIL :-)

**Comment by n7s** [comment]
BTW, I think what you really mean is OFL (SIL is the name of the organisation and it produces various pieces of software under many different licenses).  You are right, part of this is under CC-BY but a few - the community icons - are apparently also under OFL: https://github.com/Templarian/MaterialDesign  

Do you need this extra set? 
Worth asking upstream if they are willing to adjust their terms. 

IMHO icons "fonts" (really just SVG with no smarts) should really be under a simpler license.

**Comment by felipesanches** [comment]
yeah, indeed I meant SIL OFL

**Comment by adrientetar** [comment]
> the license referenced by https://github.com/google/material-design-icons/blob/master/LICENSE is actually not SIL, but CC-BY instead.

Yes but the files mentioned are not from this repository, they are from: https://github.com/Templarian/MaterialDesign

**Comment by adrientetar** [comment]
If you wish to change the license for these files (something I tend to agree with) please discuss with upstream, nothing can be done with that here.

**Comment by felipesanches** [comment]
yeah, sure! :-)

**Comment by felipesanches** [comment]
I intend to at least make the licensing statements clearer here (while not changing their legal meaning).

**Comment by pathumego** [comment]
just a reminder @adrientetar I remember that @larsenwork Offered to work on icons and UI in a fontforge thread few months ago.

**Comment by pathumego** [comment]
And thinking about the extension/plugin structure discussed on that call, using a icon set from a project like https://github.com/Templarian/MaterialDesign makes sense i guess, given that licensing is clear.

**Comment by davelab6** [comment]
> https://github.com/Templarian/MaterialDesign makes sense i guess, given that licensing is clear.

Sadly isn't though, so I can't recommend using that project. https://github.com/Templarian/MaterialDesign/issues/779

**Comment by davelab6** [comment]
> We have a file called SIL.txt

Where is that file? :) I found https://github.com/trufont/trufont/commits/master/Lib/defconQt/resources/SIL-OFL.txt but no SIL.txt

**Comment by pathumego** [comment]
Yeah I meant we use it if licensing is clear. How about using icons from
noun project?

**Comment by felipesanches** [comment]
Yes, I actually meant this SIL-OFL.txt file, sorry! I am not very familiar with this license, so I ended up mistakenly referint to it by the SIL name (forgeting the actual license name: OFL).
