### ISSUE TITLE
[spacecenter] Show live values

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#9]
In space center, when I adjust the width, the Left and Right values are not updated, even when I click them. 

![screen shot 2015-10-12 at 5 14 36 pm](https://cloud.githubusercontent.com/assets/261579/10438943/b7330554-7104-11e5-846d-741fad20cff9.png)

The values should be 'live'

**Comment by adrientetar** [comment]
Fixed by eae22214e405e7101e61333786a3bfcc9b44b8c5.
