### ISSUE TITLE
High DPI Rendering

### ISSUE THREAD

**Issue by jackjennings** [trufont/trufont#92]
Currently the application GUI looks pretty out of place on my recent MacBook which has a high-density display. Attached is a screenshot of what I'm seeing; compare the DPI of the UI to the text rendering in the background. I assume that this might be an issue with using Qt?

<img width="772" alt="screen shot 2015-10-29 at 8 11 42 am" src="https://cloud.githubusercontent.com/assets/46891/10822763/b4b93fdc-7e15-11e5-8565-9f9a34d84cfb.png">

**Comment by anthrotype** [comment]
This should be already fixed with #58. I presume you are running the pre-compiled 0.1.0 release.
Could you try to pull the latest HEAD and see it that fixes it for you?

(Related #54)

**Comment by davelab6** [comment]
I think we should make a new release pretty soon, as 0.1.1

**Comment by jackjennings** [comment]
I just downloaded the binary from the TruFont website, yes. I can check against HEAD later today.

**Comment by pathumego** [comment]
its fixed in HEAD
