### ISSUE TITLE
Unable to open an UFO via GUI "Open" dialog

### ISSUE THREAD

**Issue by felipesanches** [trufont/trufont#94]
Steps to reproduce:
- Open the program (a default UFO will be loaded)
- Click File->Open (the "Open file" dialog will appear)
- Select an UFO
- Click "Open"

Actual wrong result:
- As UFOs are folders the "Open" button opens the folder and shows its contents in the "Open File" dialog.
- Presumably because the "Open File" dialog was designed to open files instead of opening a folder.

Expected correct result:
- To have defconQt load the UFO in the given folder.

**Comment by felipesanches** [comment]
This has been tested on Trisquel GNU/Linux running GNOME and confirmed as not fixed yet on current master (5d62be8c4dfb601b92f9153400e3e1cc8712cf94).

**Comment by davelab6** [comment]
You have to load the metainfo.plist file. This should be obvious from the
open dialog; per
https://github.com/trufont/trufont/blob/master/Lib/defconQt/util/platformSpecific.py#L11

**Comment by felipesanches** [comment]
Interestingly, that's what I see:

![open file_trufont](https://cloud.githubusercontent.com/assets/213676/10837474/0a184e74-7ea1-11e5-95c4-c0b90c828bf8.png)

**Comment by felipesanches** [comment]
OK. What happens is that GTK uses the last portion of that formats string to filter which files it shows in the file browser. But it removes it from the format desciption. So the user only sees "UFO Fonts" instead of "UFO Fonts (metainfo.plist)". So it is not so obvious.

At least now I see a way to load UFOs without having to resort to the command line. But I disagree that it is intuitive something based on the current open dialog design.

**Comment by pathumego** [comment]
@felipesanches Is this fixed for you now?
